const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let calc,getTenGod,getBranchTenGod;let sex='female';let P=null;
const HIDDEN={자:[['계',1]],축:[['기',.6],['계',.25],['신',.15]],인:[['갑',.6],['병',.25],['무',.15]],묘:[['을',1]],진:[['무',.6],['을',.25],['계',.15]],사:[['병',.6],['무',.25],['경',.15]],오:[['정',.7],['기',.3]],미:[['기',.6],['정',.25],['을',.15]],신:[['경',.6],['임',.25],['무',.15]],유:[['신',1]],술:[['무',.6],['신',.25],['정',.15]],해:[['임',.7],['갑',.3]]};
const LONG={서울:126.9780,인천:126.7052,부산:129.0756,대구:128.6014,대전:127.3845,광주:126.8526,울산:129.3114,세종:127.2890,제주:126.5312};
const groupMap={재성:['정재','편재'],식상:['식신','상관'],비겁:['비견','겁재'],관성:['정관','편관'],인성:['정인','편인']};
function show(id){['landing','loading','result','checkout'].forEach(x=>$('#'+x)?.classList.add('hide'));$('#'+id)?.classList.remove('hide');scrollTo(0,0)}
function setEngine(msg,ok=true){const el=$('#engineStatus');if(!el)return;el.textContent=msg;el.className='notice '+(ok?'ok':'')}
try{const lib=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm');calc=lib.calculateFourPillars;getTenGod=lib.getTenGod;getBranchTenGod=lib.getBranchTenGod;setEngine('✓ KASI 정본 기반 만세력 엔진 연결됨 · 임의 점수/랜덤 팔자 사용 안 함');}catch(e){console.error(e);setEngine('만세력 엔진을 불러오지 못했습니다. 네트워크 연결 후 새로고침해주세요.',false)}
$$('.sex').forEach(b=>b.onclick=()=>{$$('.sex').forEach(x=>x.classList.remove('on'));b.classList.add('on');sex=b.dataset.sex});
$$('.cal').forEach(b=>b.onclick=()=>{$$('.cal').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#calendar').value=b.dataset.cal;$('#leapWrap').classList.toggle('hide',b.dataset.cal!=='lunar')});
$('#unknown').onchange=e=>{const off=e.target.checked;$('#hour').disabled=off;$('#minute').disabled=off;$('#timeHelp').textContent=off?'시주와 시간에 민감한 대운 시작 시점은 제외·근사 처리합니다.':'출생증명서에 적힌 시각이 가장 좋습니다.'};
$('#city').onchange=e=>{$('#longitude').value=LONG[e.target.value]??126.978};
function n(v){return Number(v)}
function birthInput(){const isLunar=$('#calendar').value==='lunar',unknown=$('#unknown').checked;return{year:n($('#year').value),month:n($('#month').value),day:n($('#day').value),hour:unknown?12:n($('#hour').value),minute:unknown?0:n($('#minute').value),isLunar,isLeapMonth:isLunar&&$('#leap').checked,gender:sex,trueSolarTime:$('#solarTime').checked?{longitude:n($('#longitude').value),applyEquationOfTime:true,applyHistoricalDst:true}:undefined,dayBoundary:$('#boundary').value,unknown}}
function pillarText(p){return `${p.heavenlyStem}${p.earthlyBranch}`}
function addWeight(obj,g,w){if(!g||g==='일간')return;obj[g]=(obj[g]||0)+w}
function godWeights(r,hourKnown){const o={};[['year',r.year],['month',r.month],['day',r.day],['hour',r.hour]].forEach(([pos,p])=>{if(pos==='hour'&&!hourKnown)return;if(pos!=='day')addWeight(o,getTenGod(r.day.heavenlyStem,p.heavenlyStem),1.45);(HIDDEN[p.earthlyBranch]||[]).forEach(([s,w])=>addWeight(o,getTenGod(r.day.heavenlyStem,s),w));});return o}
function groups(weights){const out={};Object.entries(groupMap).forEach(([k,arr])=>out[k]=arr.reduce((a,g)=>a+(weights[g]||0),0));return out}
function moneyType(w,g){const zj=w['정재']||0,pj=w['편재']||0,sg=g.식상,bg=g.비겁,gs=g.관성;if(pj>zj*1.25&&pj>1.1)return['기회·사업형','편재 신호가 정재보다 두드러져 고정 급여 하나보다 거래·성과·프로젝트처럼 변동성이 있는 수입 구조에 관심이 가기 쉬운 명식입니다.'];if(zj>pj*1.25&&zj>1.1)return['축적·관리형','정재 신호가 상대적으로 두드러져 반복 가능한 수입과 관리 가능한 현금흐름을 만드는 쪽이 명리 구조상 더 선명합니다.'];if(sg>Math.max(g.재성,1.4))return['생산·수익화형','식신·상관의 비중이 높아 지식·기술·콘텐츠·영업처럼 내가 만들어낸 결과물을 수입으로 연결하는 구조가 중요하게 읽힙니다.'];if(gs>2&&g.재성>1)return['직장·책임형','관성과 재성이 함께 보여 조직 안의 책임·직책·전문성을 수입 안정성과 연결하는 해석이 가능합니다.'];if(bg>3&&g.재성<1.5)return['관계·경쟁 관리형','비견·겁재가 강하고 재성이 상대적으로 약해 돈의 크기보다 경쟁·동업·관계 속 자원 배분을 관리하는 것이 재물 해석의 핵심이 됩니다.'];return['균형 성장형','한 가지 재물 신호에 치우치기보다 재성·식상·관성 등을 함께 봐야 하는 구조입니다. 단일 키워드보다 대운과 세운에서 어떤 십신이 들어오는지 확인하는 편이 중요합니다.']}
function relations(r,hourKnown){const z=[['년',r.year.earthlyBranch],['월',r.month.earthlyBranch],['일',r.day.earthlyBranch]];if(hourKnown)z.push(['시',r.hour.earthlyBranch]);const clash=['자오','축미','인신','묘유','진술','사해'],combine=['자축','인해','묘술','진유','사신','오미'];let out=[];for(let i=0;i<z.length;i++)for(let j=i+1;j<z.length;j++){const pair=z[i][1]+z[j][1],rev=z[j][1]+z[i][1];if(clash.includes(pair)||clash.includes(rev))out.push(`${z[i][0]}-${z[j][0]} 충(${z[i][1]}·${z[j][1]})`);if(combine.includes(pair)||combine.includes(rev))out.push(`${z[i][0]}-${z[j][0]} 육합(${z[i][1]}·${z[j][1]})`)}return out}
function renderPillars(r,unknown){const data=[['년주',r.year],['월주',r.month],['일주',r.day],['시주',r.hour]];$('#pillars').innerHTML=data.map(([lab,p],i)=>i===3&&unknown?`<div class="pillar unknown"><small>${lab}</small><strong>미상</strong><em>출생시간 필요</em></div>`:`<div class="pillar"><small>${lab}</small><strong>${pillarText(p)}</strong><em>${i===2?'일간 '+p.heavenlyStem:(r.tenGods?.[['year','month','day','hour'][i]]?.stem||'')}</em></div>`).join('')}
function renderBars(g){const max=Math.max(...Object.values(g),1);$('#bars').innerHTML=Object.entries(g).map(([k,v])=>`<div class="barRow"><b>${k}</b><div class="bar"><i style="width:${Math.round(v/max*100)}%"></i></div><span>${v.toFixed(1)}</span></div>`).join('')}
function renderTen(r,unknown){const order=[['년간',r.tenGods.year.stem],['년지',r.tenGods.year.branch],['월간',r.tenGods.month.stem],['월지',r.tenGods.month.branch],['일지',r.tenGods.day.branch]];if(!unknown)order.push(['시간',r.tenGods.hour.stem],['시지',r.tenGods.hour.branch]);$('#tenGrid').innerHTML=order.map(([p,g])=>`<div class="ten"><small>${p}</small><b>${g}</b></div>`).join('')}
function fullAge(y,m,d){const now=new Date();let a=now.getFullYear()-y;if(now.getMonth()+1<m||(now.getMonth()+1===m&&now.getDate()<d))a--;return Math.max(a,0)}
function renderDayun(r,b){const lp=r.luckPillars;if(!lp){$('#dayun').innerHTML='<span class="desc">대운 데이터 없음</span>';return}const age=fullAge(b.year,b.month,b.day);$('#dayunMeta').textContent=`${lp.forward?'순행':'역행'} · 대운 시작 약 ${lp.startYears}년 ${lp.startMonths}개월 ${lp.startDays}일`;$('#dayun').innerHTML=lp.pillars.slice(0,10).map(x=>`<div class="dy ${age>=x.age&&age<x.age+10?'now':''}"><small>${x.age}세~</small><b>${x.korean}</b></div>`).join('')}
function currentYearGod(dayMaster){const y=new Date().getFullYear();const yr=calc({year:y,month:7,day:1,hour:12,minute:0,gender:'male'});return{year:y,pillar:pillarText(yr.year),stem:getTenGod(dayMaster,yr.year.heavenlyStem),branch:getBranchTenGod(dayMaster,yr.year.earthlyBranch)}}
function render(){const {r,b,w,g,type,rel,yr}=P;$('#rname').textContent=`${$('#name').value.trim()}님의 실제 만세력 기반 재물 구조`;$('#type').textContent=type[0];$('#typeDesc').textContent=type[1];renderPillars(r,b.unknown);$('#dayMaster').textContent=`${r.day.heavenlyStem}(${r.dayElement.stem})`;$('#void').textContent=(r.voidBranches||[]).join('·')||'없음';$('#calendarFact').textContent=b.isLunar?'음력 입력':'양력 입력';renderBars(g);renderTen(r,b.unknown);$('#relations').innerHTML=rel.length?rel.map(x=>`<span class="relation">${x}</span>`).join(''):'<span class="desc">원국 네 지지에서 육합·충이 바로 잡히지 않았습니다.</span>';renderDayun(r,b);$('#yearLuck').innerHTML=`<b>${yr.year}년 ${yr.pillar}</b> · 일간 기준 천간은 <b>${yr.stem}</b>, 지지는 <b>${yr.branch}</b>으로 계산됩니다.`;$('#raw').textContent=`원국 ${r.toString()} · ${b.unknown?'시주 미상/정오 대입으로 년·월·일주만 사용':'시주 포함'} · ${b.trueSolarTime?'진태양시 보정 ON':'KST 표준시 기준'} · 자시 경계 ${b.dayBoundary}`}
$('#f').onsubmit=e=>{e.preventDefault();if(!calc){alert('만세력 엔진이 아직 로드되지 않았습니다. 새로고침 후 다시 시도해주세요.');return}const b=birthInput();if(!b.year||!b.month||!b.day){alert('생년월일을 입력해주세요.');return}show('loading');setTimeout(()=>{try{const r=calc(b);const w=godWeights(r,!b.unknown),g=groups(w),type=moneyType(w,g),rel=relations(r,!b.unknown),yr=currentYearGod(r.day.heavenlyStem);P={r,b,w,g,type,rel,yr};render();show('result')}catch(err){console.error(err);show('landing');alert('입력값으로 만세력을 계산하지 못했습니다. 날짜·윤달 여부를 확인해주세요.')}},550)};
$('#buy').onclick=()=>show('checkout');$('#back').onclick=()=>show('result');$('#pay').onclick=()=>alert('현재는 실제 결제를 연결하지 않은 MVP입니다. 다음 단계에서 PG와 AI 심층 해석을 붙입니다.');