const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VERSION='13.0.0',DAILY_LIMIT=5;
const LONG={서울:126.9780,부산:129.0756,대구:128.6014,인천:126.7052,광주:126.8526,대전:127.3845,울산:129.3114,세종:127.2890,경기:127.0286,강원:127.7298,충북:127.4914,충남:126.6728,전북:127.1088,전남:126.4629,경북:128.5056,경남:128.6811,제주:126.5312};
const CLASH=['자오','축미','인신','묘유','진술','사해'],COMB=['자축','인해','묘술','진유','사신','오미'],HARM=['자미','축오','인사','묘진','신해','유술'],BREAK=['자유','묘오','진축','미술','인해','사신'];
const SELF=['진','오','유','해'];
const STEM_ELEMENT={갑:'wood',을:'wood',병:'fire',정:'fire',무:'earth',기:'earth',경:'metal',신:'metal',임:'water',계:'water'};
const BRANCH_ELEMENT={자:'water',축:'earth',인:'wood',묘:'wood',진:'earth',사:'fire',오:'fire',미:'earth',신:'metal',유:'metal',술:'earth',해:'water'};
const GENERATES={wood:'fire',fire:'earth',earth:'metal',metal:'water',water:'wood'};
const CONTROLS={wood:'earth',earth:'water',water:'fire',fire:'metal',metal:'wood'};
const EVENT_LABEL={career_change:'직장·역할 변화',role_pressure:'책임·평가 압박',independent_work:'독립·부업·사업',cashflow_shift:'수입·지출 구조 변화',contract_decision:'계약·거래 결정',relationship_shift:'가까운 관계 재정리',relationship_commit:'관계 확정·약속',relocation:'이사·생활권 변화',family_duty:'가족 책임 증가',study_docs:'시험·자격·문서'};
const EVENT_COPY={
 career_change:'직장 자체를 옮기거나 맡는 역할이 크게 달라지는 쪽',
 role_pressure:'일이 많아지는 것보다 책임·평가·윗사람 문제를 더 크게 체감하는 쪽',
 independent_work:'내 이름으로 벌거나 부업·사업처럼 수입 방식을 따로 만들려는 쪽',
 cashflow_shift:'버는 돈과 나가는 돈의 규모나 방식이 평소와 달라지는 쪽',
 contract_decision:'계약·거래·투자처럼 숫자와 조건을 보고 결정해야 하는 쪽',
 relationship_shift:'이미 가까운 사람과 거리를 다시 정하거나 관계의 모양을 바꾸는 쪽',
 relationship_commit:'연애를 실제 약속·동거·결혼처럼 현실적인 형태로 옮기는 쪽',
 relocation:'실제 이사·독립·합가·직장 이동으로 생활 반경이 바뀌는 쪽',
 family_duty:'부모·형제·자녀 등 가족 안에서 내가 맡을 몫이 커지는 쪽',
 study_docs:'시험·자격·공부·중요 문서처럼 준비하고 증명해야 하는 쪽'
};
const TOPICS=[['business','사업·창업'],['sidejob','부업·투잡'],['jobchange','이직·퇴사'],['promotion','직장·승진'],['money','재물·돈 흐름'],['investment','투자·계약'],['newlove','새 연애'],['reunion','재회'],['marriage','결혼 시기'],['compatibility','궁합'],['children','임신·자녀'],['relations','인간관계'],['exam','시험·합격'],['realestate','이사·부동산'],['family','가족 문제'],['annual','올해 전체운']];
const TOPIC_EVENTS={business:['independent_work','cashflow_shift','contract_decision'],sidejob:['independent_work','cashflow_shift'],jobchange:['career_change','role_pressure'],promotion:['role_pressure','career_change'],money:['cashflow_shift','contract_decision'],investment:['contract_decision','cashflow_shift'],newlove:['relationship_shift','relationship_commit'],reunion:['relationship_shift'],marriage:['relationship_commit','relationship_shift'],children:['family_duty'],relations:['relationship_shift'],exam:['study_docs'],realestate:['relocation','contract_decision'],family:['family_duty','relationship_shift'],annual:['career_change','cashflow_shift','relationship_shift','relocation']};
let lib,input,natal,profileKey,currentReading,selectedTopic;
const pair=(a,b,list)=>list.includes(a+b)||list.includes(b+a);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const show=id=>{['landing','loading','result','checkout','paid'].forEach(x=>$('#'+x)?.classList.add('hide'));$('#'+id)?.classList.remove('hide');scrollTo(0,0)};
function style(){const s=document.createElement('style');s.textContent=`#readingMount,#questionMount,#sealMount,#paidMount{max-width:760px;margin:auto}.hwPaper{margin:14px 0;padding:22px 20px;background:linear-gradient(180deg,#f2eadb,#e8decb);color:#211811;border:1px solid rgba(151,120,82,.38);box-shadow:0 18px 45px rgba(0,0,0,.2)}.hwLead{border-top:3px solid #7d2a23}.hwEy{font-size:10px;font-weight:900;letter-spacing:.12em;color:#812e27;margin-bottom:8px}.hwPaper h2{margin:0 0 12px;font-family:Georgia,'Noto Serif KR',serif;font-size:22px;line-height:1.45}.hwPaper h3{margin:0 0 8px;font-size:18px;line-height:1.55}.hwPaper p{margin:0;font-size:14px;line-height:1.9;color:#50483f;word-break:keep-all}.hwTiming{margin-top:14px;padding:10px 12px;border-left:3px solid #8a3027;background:rgba(132,46,38,.07);font-size:12px;line-height:1.7}.hwGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:16px 0}.hwTopic{border:1px solid #ab987a;background:rgba(255,255,255,.28);padding:12px 8px;font-size:12px;font-weight:800;color:#30261f}.hwTopic.on{background:#752820;color:#f4eade}.hwPreview{margin-top:16px;padding-top:16px;border-top:1px solid rgba(112,82,55,.25)}.hwBlur{position:relative;margin-top:14px;overflow:hidden}.hwBlurContent{filter:blur(5px);opacity:.55;user-select:none;padding:8px 0 165px}.hwLockedRow{padding:14px 0;border-bottom:1px solid rgba(112,82,55,.17)}.hwPaywall{position:absolute;left:0;right:0;bottom:0;padding:62px 14px 18px;background:linear-gradient(180deg,rgba(235,225,207,0),#eadfca 36%,#e7dcc7);text-align:center}.hwPaywall button{width:100%;border:0;background:#74271f;color:#f6ecdf;padding:15px;font-weight:900}.hwSeal{margin:16px auto;padding:16px 18px;background:#120c0a;border:1px solid #3d2a22;color:#d8cab8}.hwSeal small,.hwSeal span{display:block;font-size:10px;color:#958679}.hwSeal b{display:block;margin:6px 0;font-family:monospace;color:#eadfce}.hwFive{display:grid;gap:8px}.hwYear{display:grid;grid-template-columns:64px 1fr;gap:12px;padding:12px 0;border-bottom:1px solid rgba(112,82,55,.18)}.hwYear b{font-family:Georgia,serif;font-size:18px}.hwYear span{font-size:13px;line-height:1.7;color:#5b5046}.hwWarn{padding:12px;background:rgba(129,46,39,.06);border-left:3px solid #812e27;font-size:12px;line-height:1.75}.hide{display:none!important}@media(max-width:390px){.hwPaper{padding:19px 16px}.hwPaper h2{font-size:20px}}`;document.head.appendChild(s)}
function setup(){for(let i=0;i<24;i++)$('#hour').insertAdjacentHTML('beforeend',`<option value="${i}" ${i===12?'selected':''}>${String(i).padStart(2,'0')}시</option>`);$('#enterBtn').onclick=()=>$('#consult').scrollIntoView({behavior:'smooth'});$$('.sex').forEach(b=>b.onclick=()=>{$$('.sex').forEach(x=>x.classList.remove('on'));b.classList.add('on')});$$('.cal').forEach(b=>b.onclick=()=>{$$('.cal').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#calendar').value=b.dataset.cal;$('#leapWrap').classList.toggle('hide',b.dataset.cal!=='lunar')});$('#unknown').onchange=e=>{$('#hour').disabled=e.target.checked;$('#minute').disabled=e.target.checked};$('#back').onclick=()=>show('result');$('#restart').onclick=()=>location.reload()}
function getInput(){const unknown=$('#unknown').checked;return{year:+$('#year').value,month:+$('#month').value,day:+$('#day').value,hour:unknown?12:+$('#hour').value,minute:unknown?0:+$('#minute').value,gender:$('.sex.on')?.dataset.sex||'female',isLunar:$('#calendar').value==='lunar',isLeapMonth:$('#calendar').value==='lunar'&&$('#leap').checked,unknown,city:$('#city').value,name:$('#name').value.trim()||'당신',trueSolarTime:{longitude:LONG[$('#city').value]||126.978,applyEquationOfTime:true,applyHistoricalDst:true},dayBoundary:'midnight'} }
function valid(v){if(!v.year||v.year<1900||v.year>2100)return'출생연도를 확인해주세요.';if(v.month<1||v.month>12||v.day<1||v.day>31)return'생년월일을 확인해주세요.';if(!v.isLunar){const d=new Date(v.year,v.month-1,v.day);if(d.getFullYear()!==v.year||d.getMonth()!==v.month-1||d.getDate()!==v.day)return'존재하지 않는 날짜입니다.'}if(!v.unknown&&(v.minute<0||v.minute>59))return'태어난 시간을 확인해주세요.';return''}
async function hash(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function makeProfileKey(v){return(await hash(JSON.stringify([v.year,v.month,v.day,v.unknown?'unknown':[v.hour,v.minute],v.city,v.gender,v.isLunar,v.isLeapMonth]))).slice(0,18)}
function quota(id){const k='hyun13-'+new Date().toISOString().slice(0,10);let a=[];try{a=JSON.parse(localStorage.getItem(k)||'[]')}catch{}if(a.includes(id))return true;if(a.length>=DAILY_LIMIT)return false;a.push(id);localStorage.setItem(k,JSON.stringify(a));return true}
function branchRel(a,b){if(pair(a,b,CLASH))return{type:'clash',w:6};if(pair(a,b,HARM))return{type:'harm',w:3.3};if(pair(a,b,BREAK))return{type:'break',w:2.8};if(pair(a,b,COMB))return{type:'combine',w:2.7};if(a===b&&SELF.includes(a))return{type:'self',w:3.1};if(a===b)return{type:'repeat',w:1.5};return null}
function dayun(r,v,year){const age=year-v.year;return(r.luckPillars?.pillars||[]).find(x=>age>=x.age&&age<x.age+10)||null}
function pparts(x){if(!x)return{};const g=x.korean||x.ganji||'';return{stem:x.heavenlyStem||g[0],branch:x.earthlyBranch||g[1]}}
function natalStrength(r){const de=STEM_ELEMENT[r.day.heavenlyStem];let support=0,drain=0;const elems=[BRANCH_ELEMENT[r.month.earthlyBranch],BRANCH_ELEMENT[r.day.earthlyBranch],BRANCH_ELEMENT[r.year.earthlyBranch],STEM_ELEMENT[r.month.heavenlyStem],STEM_ELEMENT[r.year.heavenlyStem]];for(const e of elems){if(e===de||GENERATES[e]===de)support+=1;if(GENERATES[de]===e||CONTROLS[de]===e||CONTROLS[e]===de)drain+=.65}return support-drain}
function eventScores(r,v,year){const yr=lib.calculateFourPillars({year,month:7,day:1,hour:12,minute:0,gender:v.gender}).year;const sg=lib.getTenGod(r.day.heavenlyStem,yr.heavenlyStem),bg=lib.getBranchTenGod(r.day.heavenlyStem,yr.earthlyBranch);const scores={},ev={};const add=(e,pts,why)=>{scores[e]=(scores[e]||0)+pts;(ev[e]??=new Set()).add(why)};const positions=[['year',r.year.earthlyBranch],['month',r.month.earthlyBranch],['day',r.day.earthlyBranch]];if(!v.unknown)positions.push(['hour',r.hour.earthlyBranch]);for(const [pos,z] of positions){const rel=branchRel(z,yr.earthlyBranch);if(!rel)continue;const disruptive=['clash','harm','break','self'].includes(rel.type);if(pos==='month'){if(disruptive){add('career_change',rel.w,'직장자리');add('relocation',rel.w*.55,'생활권')}else add('role_pressure',rel.w*.7,'직장자리')}
 if(pos==='day'){if(disruptive){add('relationship_shift',rel.w,'가까운관계');add('relocation',rel.w*.55,'생활자리')}else if(rel.type==='combine')add('relationship_commit',rel.w*1.15,'가까운관계')}
 if(pos==='year'&&disruptive)add('family_duty',rel.w*.8,'가족자리');if(pos==='hour'&&disruptive)add('family_duty',rel.w*.75,'후반계획')}
 const gods=[sg,bg];for(const g of gods){if(['정관','편관'].includes(g)){add('role_pressure',3,'책임');add('career_change',1.4,'책임');add('study_docs',1.1,'공적문서')}if(['식신','상관'].includes(g)){add('independent_work',2.6,'성과');add('career_change',1.5,'변화욕구');add('cashflow_shift',1.2,'성과수입')}if(['정재','편재'].includes(g)){add('cashflow_shift',3,'돈');add('contract_decision',1.7,'거래');if(v.gender==='male')add('relationship_commit',1.1,'배우자별')}if(['비견','겁재'].includes(g)){add('cashflow_shift',1.8,'경쟁돈');add('independent_work',1.6,'독립성');add('relationship_shift',1.1,'경쟁관계')}if(['정인','편인'].includes(g)){add('study_docs',2.5,'문서배움');add('family_duty',1.1,'보호책임')}}
 const dp=pparts(dayun(r,v,year));if(dp.stem){const dg=lib.getTenGod(r.day.heavenlyStem,dp.stem);if(['정관','편관'].includes(dg)){add('role_pressure',2,'대운책임');add('career_change',1,'대운책임')}if(['식신','상관'].includes(dg)){add('independent_work',1.8,'대운성과');add('career_change',1,'대운변화')}if(['정재','편재'].includes(dg)){add('cashflow_shift',1.8,'대운돈');add('contract_decision',1,'대운돈')}if(['정인','편인'].includes(dg))add('study_docs',1.5,'대운문서')}
 if(dp.branch){const rel=branchRel(dp.branch,yr.earthlyBranch);if(rel){const w=rel.w*.6;add('career_change',w*.45,'대운세운');add('cashflow_shift',w*.35,'대운세운');add('relationship_shift',w*.35,'대운세운');add('relocation',w*.3,'대운세운')}}
 const strength=natalStrength(r);if(strength<-1){scores.role_pressure=(scores.role_pressure||0)*1.08;scores.cashflow_shift=(scores.cashflow_shift||0)*.92}else if(strength>1){scores.independent_work=(scores.independent_work||0)*1.08}
 const ranked=Object.keys(scores).map(k=>({event:k,score:scores[k],evidence:[...(ev[k]||[])],evidenceCount:(ev[k]||new Set()).size})).map(x=>({...x,confidence:Math.min(0.96,(x.score/12)*.64+(x.evidenceCount/4)*.36)})).sort((a,b)=>b.confidence-a.confidence||b.score-a.score);
 return{year,sg,bg,ranked};}
function monthScore(r,v,year,event){const out=[];for(let m=1;m<=12;m++){const p=lib.calculateFourPillars({year,month:m,day:15,hour:12,minute:0,gender:v.gender}).month;const sg=lib.getTenGod(r.day.heavenlyStem,p.heavenlyStem),bg=lib.getBranchTenGod(r.day.heavenlyStem,p.earthlyBranch);let s=0;const dayRel=branchRel(r.day.earthlyBranch,p.earthlyBranch),monthRel=branchRel(r.month.earthlyBranch,p.earthlyBranch);if(event==='career_change'&&monthRel)s+=monthRel.w;if(event==='relocation'&&(monthRel||dayRel))s+=(monthRel?.w||0)+(dayRel?.w||0)*.6;if(['relationship_shift','relationship_commit'].includes(event)&&dayRel)s+=dayRel.w;if(event==='role_pressure'&&['정관','편관'].includes(sg))s+=3;if(event==='independent_work'&&['식신','상관','편재'].includes(sg))s+=2.5;if(event==='cashflow_shift'&&['정재','편재','겁재'].includes(sg))s+=2.4;if(event==='contract_decision'&&['정재','편재','정인','정관'].includes(sg))s+=2;if(event==='study_docs'&&['정인','편인','정관'].includes(sg))s+=2.5;if(event==='family_duty'&&['정인','편인','정관'].includes(bg))s+=1.6;out.push({month:m,score:s})}return out.sort((a,b)=>b.score-a.score).slice(0,2).filter(x=>x.score>=2.4).sort((a,b)=>a.month-b.month).map(x=>x.month)}
function strongEvent(r,v,year,min=.62){return eventScores(r,v,year).ranked.find(x=>x.confidence>=min&&x.evidenceCount>=2&&(!['family_duty','study_docs'].includes(x.event)||x.evidenceCount>=3))||null}
function selectPast(r,v){const now=new Date().getFullYear(),c=[];for(let y=now-10;y<now;y++){const e=strongEvent(r,v,y,.66);if(e)c.push({year:y,...e})}c.sort((a,b)=>b.confidence-a.confidence);const picked=[];for(const x of c){if(picked.some(p=>p.event===x.event))continue;picked.push(x);if(picked.length===2)break}return picked.sort((a,b)=>a.year-b.year)}
function selectNow(r,v){const y=new Date().getFullYear(),a=strongEvent(r,v,y,.61),b=strongEvent(r,v,y+1,.68);if(a)return{year:y,...a};if(b)return{year:y+1,...b};return null}
function selectFuture(r,v){const y=new Date().getFullYear(),c=[];for(let i=1;i<=3;i++){const e=strongEvent(r,v,y+i,.7);if(e)c.push({year:y+i,...e})}return c.sort((a,b)=>b.confidence-a.confidence)[0]||null}
function wording(x,past=false){const m=monthScore(natal,input,x.year,x.event);const when=m.length?` 특히 ${m.join('월·')} 전후가 더 강합니다.`:'';const heads={career_change:'일의 자리가 바뀌는 쪽',role_pressure:'책임과 평가가 몰리는 쪽',independent_work:'내 방식으로 벌려는 쪽',cashflow_shift:'돈의 들어오고 나가는 방식이 바뀌는 쪽',contract_decision:'계약과 숫자를 두고 결정하는 쪽',relationship_shift:'가까운 관계를 다시 정하는 쪽',relationship_commit:'관계를 실제 약속으로 옮기는 쪽',relocation:'사는 곳이나 생활 반경이 바뀌는 쪽',family_duty:'가족 안에서 맡을 몫이 커지는 쪽',study_docs:'시험·자격·문서를 준비하는 쪽'};const title=past?`${x.year}년은 ‘${heads[x.event]}’이 다른 것보다 강합니다.`:`${x.year}년은 ‘${heads[x.event]}’을 먼저 봐야 합니다.`;return{title,body:`${EVENT_COPY[x.event]}이 다른 문제보다 더 뚜렷하게 겹칩니다.${when}`,months:m}}
function renderReading(reading,replay=false){const mount=$('#readingMount');const now=reading.now,future=reading.future,past=reading.past;let html='';if(now){const c=wording(now);html+=`<article class="hwPaper hwLead"><div class="hwEy">지금 가장 먼저 보이는 것</div><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></article>`}else html+=`<article class="hwPaper hwLead"><div class="hwEy">지금 흐름</div><h2>지금은 한 가지 문제를 억지로 찍지 않겠습니다.</h2><p>현재 계산에서는 특정 사건 하나가 다른 것보다 충분히 강하게 겹치지 않습니다. 이런 경우에는 넓은 말을 만들어내지 않는 편이 낫습니다.</p></article>`;
 if(past.length){for(const x of past){const c=wording(x,true);html+=`<article class="hwPaper"><div class="hwEy">지나온 흐름 · ${x.year}</div><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p><div class="hwTiming">이 해를 고른 이유는 한 가지 신호 때문이 아니라 서로 다른 근거가 ${x.evidenceCount}개 이상 겹쳤기 때문입니다.</div></article>`}}else html+=`<article class="hwPaper"><div class="hwEy">지나온 흐름</div><h2>최근 10년 중 억지로 한 해를 고르지는 않겠습니다.</h2><p>현재 기준으로는 ‘이 해에 이런 사건이 있었다’고 말할 만큼 신호가 충분히 겹치지 않습니다.</p></article>`;
 if(future){const c=wording(future);html+=`<article class="hwPaper"><div class="hwEy">가까운 미래</div><h2>${esc(c.title)}</h2><p>${esc(c.body)}</p></article>`}else html+=`<article class="hwPaper"><div class="hwEy">가까운 미래</div><h2>앞으로 3년 안에서는 한 사건을 강하게 단정하지 않겠습니다.</h2><p>특정 영역 하나가 충분히 튀지 않기 때문에, 질문을 받은 뒤 그 주제만 따로 좁혀 보는 편이 정확합니다.</p></article>`;
 mount.innerHTML=html;$('#replayNote').textContent=replay?'같은 명식의 첫 풀이를 그대로 다시 보여드리고 있습니다.':'첫 풀이가 끝났습니다. 이제 궁금한 주제를 고르세요.';renderQuestions()}
function renderQuestions(){const q=$('#questionMount');q.innerHTML=`<section class="hwPaper"><div class="hwEy">이제 질문하세요</div><h2>궁금한 것 하나를 고르세요.</h2><div class="hwGrid">${TOPICS.map(([id,l])=>`<button class="hwTopic" data-topic="${id}">${l}</button>`).join('')}</div><div id="topicPreview"></div></section>`;$$('.hwTopic').forEach(b=>b.onclick=()=>{$$('.hwTopic').forEach(x=>x.classList.remove('on'));b.classList.add('on');selectedTopic=b.dataset.topic;renderTopic(selectedTopic,b.textContent.trim())})}
function bestForTopic(topic){if(topic==='compatibility')return null;const wanted=TOPIC_EVENTS[topic]||[];const y=new Date().getFullYear(),cand=[];for(let i=0;i<=4;i++){const info=eventScores(natal,input,y+i);for(const r of info.ranked){if(wanted.includes(r.event)&&r.evidenceCount>=2)cand.push({year:y+i,...r})}}return cand.sort((a,b)=>b.confidence-a.confidence)[0]||null}
function renderTopic(topic,label){const box=$('#topicPreview');if(topic==='compatibility'){box.innerHTML=`<div class="hwPreview"><h3>궁합은 상대방 정보가 있어야 봅니다.</h3><p>한 사람 사주만 보고 잘 맞는다, 안 맞는다 말하지 않겠습니다. 상대방 생년월일과 태어난 시간이 필요합니다.</p></div>`;return}const best=bestForTopic(topic);if(!best||best.confidence<.55){box.innerHTML=`<div class="hwPreview"><div class="hwEy">${label} · 무료 풀이</div><h3>이 주제는 지금 명식만으로 강하게 단정하기 어렵습니다.</h3><p>억지로 좋은 해·나쁜 해를 만들지 않겠습니다. 심층 풀이에서는 이 주제만 따로 좁혀 시기별로 다시 비교합니다.</p></div>`;return}const months=monthScore(natal,input,best.year,best.event);box.innerHTML=`<div class="hwPreview"><div class="hwEy">${label} · 먼저 여기까지</div><h3>${best.year}년 전후를 먼저 봐야 합니다.</h3><p>${EVENT_COPY[best.event]}이 이 주제에서 가장 강하게 겹칩니다.${months.length?` 특히 ${months.join('월·')} 전후가 더 눈에 띕니다.`:''}</p><div class="hwWarn">여기까지는 무료로 봅니다. 아래부터는 같은 주제를 ‘움직일 때 / 기다릴 때 / 조심할 조건’으로 더 좁힙니다.</div></div><div class="hwBlur"><div class="hwBlurContent"><div class="hwLockedRow"><b>움직여도 되는 시기</b><p>같은 해 안에서도 밀어도 되는 때와 기다려야 하는 때를 나눕니다.</p></div><div class="hwLockedRow"><b>반드시 확인할 위험 신호</b><p>좋아 보이는 흐름에 같이 따라오는 경고 신호를 분리합니다.</p></div><div class="hwLockedRow"><b>앞으로 5년의 변화</b><p>한 해만 보지 않고 큰 흐름을 연결합니다.</p></div></div><div class="hwPaywall"><span>여기서부터 심층 풀이</span><h3>${label}, 중요한 내용은 지금부터입니다.</h3><strong>29,000원</strong><button id="unlock">이 풀이 끝까지 보기 →</button></div></div>`;$('#unlock').onclick=()=>{$('#checkoutTitle').textContent=`${label}, 끝까지 봅니다.`;$('#orderLabel').textContent=`${label} 심층 풀이`;show('checkout')}}
function paid(){const label=TOPICS.find(x=>x[0]===selectedTopic)?.[1]||'심층 풀이',best=bestForTopic(selectedTopic),y=new Date().getFullYear();let years='';for(let i=0;i<5;i++){const year=y+i,info=eventScores(natal,input,year),wanted=TOPIC_EVENTS[selectedTopic]||[],r=info.ranked.find(x=>wanted.includes(x.event)&&x.evidenceCount>=2);years+=`<div class="hwYear"><b>${year}</b><span>${r&&r.confidence>=.52?EVENT_COPY[r.event]:'이 주제에서는 큰 결정을 서두르기보다 상황을 확인하는 해'}</span></div>`}const m=best?monthScore(natal,input,best.year,best.event):[];$('#paidTitle').textContent=`${label} 전체 풀이`;$('#paidMount').innerHTML=`<article class="hwPaper hwLead"><div class="hwEy">01 · 결론</div><h2>${best&&best.confidence>=.55?`${best.year}년 전후가 가장 중요합니다.`:'한 해를 억지로 정답처럼 고르지는 않겠습니다.'}</h2><p>${best?EVENT_COPY[best.event]+'이 가장 강하게 겹칩니다.':'현재 신호가 충분히 한쪽으로 모이지 않습니다.'}</p></article><article class="hwPaper"><div class="hwEy">02 · 시기</div><h2>${m.length?`${m.join('월·')} 전후를 먼저 봅니다.`:'월 단위로 강하게 찍을 만큼 차이가 크지 않습니다.'}</h2><p>시기는 ‘좋다/나쁘다’ 한마디보다 실제 계약·이직·관계 상황과 함께 판단해야 합니다.</p></article><article class="hwPaper"><div class="hwEy">03 · 앞으로 5년</div><div class="hwFive">${years}</div></article><article class="hwPaper"><div class="hwEy">04 · 현실 체크</div><h2>사주보다 먼저 확인해야 할 것</h2><p>${selectedTopic==='realestate'?'가격·대출·잔금·계약 특약을 먼저 확인하세요.':selectedTopic==='investment'?'원금손실 가능성·현금흐름·계약조건을 먼저 확인하세요.':selectedTopic==='jobchange'?'제안받은 조건·연봉·퇴사 시점·현금 여유를 먼저 확인하세요.':'실제 상황의 조건과 상대방의 행동을 함께 확인하세요.'}</p></article>`;show('paid')}
async function submit(e){e.preventDefault();input=getInput();const err=valid(input);if(err){$('#notice').innerHTML=`<div class="hwWarn">${err}</div>`;return}profileKey=await makeProfileKey(input);if(!quota(profileKey)){$('#notice').innerHTML='<div class="hwWarn">오늘 무료로 새로 볼 수 있는 명식은 5개까지입니다. 이미 본 명식은 다시 볼 수 있습니다.</div>';return}const cacheKey='hyun13-reading-'+profileKey;let cached=null;try{cached=JSON.parse(localStorage.getItem(cacheKey)||'null')}catch{}show('loading');setTimeout(()=>{try{natal=lib.calculateFourPillars(input);if(cached?.version===VERSION){currentReading=cached.reading;renderReading(currentReading,true)}else{currentReading={now:selectNow(natal,input),past:selectPast(natal,input),future:selectFuture(natal,input),created:new Date().toISOString(),version:VERSION};localStorage.setItem(cacheKey,JSON.stringify({version:VERSION,reading:currentReading}));renderReading(currentReading,false)}const code=profileKey.toUpperCase();$('#sealMount').innerHTML=`<div class="hwSeal"><span>첫 풀이 기록</span><b>${new Date(currentReading.created).toLocaleDateString('ko-KR')} · ${code}</b><small>같은 명식은 다시 입력해도 이 첫 풀이를 바꾸지 않습니다.</small></div>`;show('result')}catch(err){console.error(err);show('landing');$('#notice').innerHTML='<div class="hwWarn">계산 중 오류가 났습니다. 입력값을 확인하고 다시 시도해주세요.</div>'}},350)}
style();setup();try{lib=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm')}catch(e){console.error(e);$('#notice').textContent='만세력 엔진을 불러오지 못했습니다. 새로고침 후 다시 시도해주세요.'}$('#f').addEventListener('submit',submit);$('#pay').onclick=paid;