const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const VERSION='14.0.0',DAILY_LIMIT=5;
const LONG={서울:126.9780,부산:129.0756,대구:128.6014,인천:126.7052,광주:126.8526,대전:127.3845,울산:129.3114,세종:127.2890,경기:127.0286,강원:127.7298,충북:127.4914,충남:126.6728,전북:127.1088,전남:126.4629,경북:128.5056,경남:128.6811,제주:126.5312};
const CLASH=['자오','축미','인신','묘유','진술','사해'],COMB=['자축','인해','묘술','진유','사신','오미'],HARM=['자미','축오','인사','묘진','신해','유술'],BREAK=['자유','묘오','진축','미술','인해','사신'];
const PUNISH=[['인','사','신'],['축','술','미']],SELF=['진','오','유','해'],TRI=[['신','자','진'],['해','묘','미'],['인','오','술'],['사','유','축']];
const STEM_COMB=['갑기','을경','병신','정임','무계'],STEM_CLASH=['갑경','을신','병임','정계'];
const HIDDEN={자:['계'],축:['기','계','신'],인:['갑','병','무'],묘:['을'],진:['무','을','계'],사:['병','무','경'],오:['정','기'],미:['기','정','을'],신:['경','임','무'],유:['신'],술:['무','신','정'],해:['임','갑']};
const STEM_ELEMENT={갑:'wood',을:'wood',병:'fire',정:'fire',무:'earth',기:'earth',경:'metal',신:'metal',임:'water',계:'water'};
const BRANCH_ELEMENT={자:'water',축:'earth',인:'wood',묘:'wood',진:'earth',사:'fire',오:'fire',미:'earth',신:'metal',유:'metal',술:'earth',해:'water'};
const GENERATES={wood:'fire',fire:'earth',earth:'metal',metal:'water',water:'wood'};
const CONTROLS={wood:'earth',earth:'water',water:'fire',fire:'metal',metal:'wood'};
const TOPICS=[['business','사업·창업'],['sidejob','부업·투잡'],['jobchange','이직·퇴사'],['promotion','직장·승진'],['money','재물·돈 흐름'],['investment','투자·계약'],['newlove','새 연애'],['reunion','재회'],['marriage','결혼 시기'],['compatibility','궁합'],['children','자녀·가족계획'],['relations','인간관계'],['exam','시험·자격'],['realestate','이사·부동산'],['family','가족 문제'],['annual','올해 전체운']];

// V14의 핵심: 넓은 생활영역이 아니라 구체 사건 후보를 먼저 만들고, 서로 다른 근거가 합의할 때만 출력한다.
const EVENTS=[
['job_change_consider','career','이직을 진지하게 고민','직장을 바로 옮긴 것보다, 지금 자리를 계속 가져갈지 처음으로 진지하게 흔들린 쪽',['month_disrupt','authority','output'],8.8],
['job_change_actual','career','실제 이직·이동','생각만 한 것이 아니라 소속이나 근무 환경을 실제로 바꾸는 쪽',['month_disrupt','dayun_month','authority'],10.5],
['resignation','career','퇴사·자리 정리','버티는 것보다 기존 자리에서 빠져나오는 결정을 하는 쪽',['month_disrupt','output','stem_clash'],10.8],
['role_change','career','보직·역할 변경','회사는 같아도 맡는 역할이나 책임 범위가 눈에 띄게 달라지는 쪽',['month_active','authority','dayun_authority'],9.6],
['promotion_eval','career','승진·평가 이슈','성과 자체보다 평가·직책·공적인 책임이 전면에 나오는 쪽',['authority','resource','month_active'],10.2],
['workload_spike','career','업무량·책임 급증','일이 많아지는 수준을 넘어 내가 책임져야 할 몫이 갑자기 커지는 쪽',['authority','month_active','pressure'],8.8],
['boss_conflict','career','상사·권한 갈등','업무 내용보다 윗사람·규칙·평가 기준 때문에 답답함이 커지는 쪽',['authority','month_disrupt','peer'],10.4],
['team_reorg','career','조직개편·팀 변화','사람 배치나 조직 구조가 바뀌면서 내 역할도 함께 흔들리는 쪽',['month_disrupt','peer','authority'],10.0],
['employment_contract_change','career','고용형태·계약 변경','정규·계약·프로젝트처럼 일하는 조건 자체를 다시 정하는 쪽',['contract','authority','month_active'],10.1],
['leave_return','career','휴직·복직·업무중단','일을 계속 밀어붙이기보다 잠시 멈추거나 다시 돌아오는 전환이 생기는 쪽',['resource','month_disrupt','pressure'],10.7],
['sidejob_start','business','부업 시작','본업 외에 따로 돈이 되는 일을 시험하거나 시작하는 쪽',['output','wealth','independence'],9.5],
['sidejob_income','business','부업 수입 발생','새 활동이 실제 소액이라도 반복 수입으로 연결되기 시작하는 쪽',['output','wealth','cashflow'],10.3],
['business_start','business','사업·독립 시작','회사나 기존 구조 밖에서 내 이름으로 일을 벌이는 쪽',['output','independence','contract'],10.4],
['business_expand','business','사업 확장','새 고객·상품·채널을 늘리면서 판을 키우는 쪽',['wealth','output','growth'],10.5],
['business_contract','business','사업 축소·정리','확장보다 비용·인력·일거리를 줄이며 구조를 정리하는 쪽',['wealth_pressure','break_signal','contract'],11.2],
['new_client','business','새 거래처·고객','새로운 외부 거래가 실제 매출 기회로 연결되는 쪽',['wealth','contract','combine_signal'],9.8],
['client_loss','business','거래처 이탈·매출원 변화','익숙한 거래나 매출원이 끊기거나 조건이 크게 달라지는 쪽',['wealth','break_signal','month_disrupt'],11.0],
['partnership_start','business','동업·협업 시작','혼자 하기보다 사람과 역할·돈을 나눠 새로운 일을 묶는 쪽',['peer','combine_signal','contract'],10.4],
['partnership_conflict','business','동업·협업 갈등','사람과 돈이 섞인 일에서 몫·책임 문제로 마찰이 생기는 쪽',['peer','wealth','break_signal'],10.8],
['sales_jump','business','매출·성과 급증','평소보다 외부 기회와 성과가 빠르게 커지는 쪽',['wealth','output','growth'],11.0],
['sales_drop','business','매출·성과 감소','들어오는 돈의 규모나 거래 빈도가 줄어 구조를 다시 짜는 쪽',['wealth_pressure','break_signal','cashflow'],11.2],
['income_stream_change','money','수입원 변화','월급·매출 등 기존 수입 방식과 다른 돈줄이 생기거나 비중이 바뀌는 쪽',['wealth','output','cashflow'],9.6],
['big_expense','money','큰 지출','평소 생활비가 아니라 목돈이 한 번에 빠져나가는 일이 생기는 쪽',['wealth_pressure','cashflow','break_signal'],10.4],
['loan_debt','money','대출·부채 발생','내 돈만으로 해결하기보다 대출·차입처럼 외부 자금을 끌어오는 쪽',['wealth_pressure','contract','pressure'],11.2],
['debt_repayment','money','대출·부채 정리','새로 벌리기보다 기존 빚이나 큰 고정비를 줄이는 쪽',['wealth','resource','closure'],10.8],
['deposit_move','money','보증금·목돈 이동','월급보다 보증금·계약금처럼 한 번에 큰 돈이 묶이거나 풀리는 쪽',['contract','wealth','home_active'],10.8],
['investment_entry','money','투자 진입','저축보다 변동성이 있는 자산이나 투자 판단에 돈을 넣는 쪽',['wealth','risk','contract'],11.4],
['investment_loss_risk','money','투자 손실·회수 압박','불리는 것보다 이미 넣은 돈의 회수나 손실 관리가 중요해지는 쪽',['wealth_pressure','risk','break_signal'],11.7],
['contract_payment','money','계약금·정산','거래 조건·정산일·계약금처럼 숫자를 확정해야 하는 쪽',['contract','wealth','document'],9.8],
['family_support_money','money','가족에 큰돈 지원','내 소비보다 가족 문제 때문에 목돈을 쓰거나 책임지는 쪽',['family_active','wealth_pressure','responsibility'],11.8],
['shared_money_conflict','money','공동지출·돈 갈등','배우자·동업자·가족과 돈의 몫을 두고 신경전이 생기는 쪽',['peer','wealth','day_active'],11.1],
['savings_rebuild','money','저축·현금흐름 재정비','돈을 크게 벌리는 것보다 새는 돈을 막고 고정비를 다시 잡는 쪽',['resource','cashflow','closure'],9.8],
['asset_purchase','money','큰 자산 구입','생활비가 아니라 집·차·사업설비처럼 오래 쓰는 자산에 돈을 넣는 쪽',['wealth','contract','home_active'],11.2],
['new_relationship','relationship','새 연애 시작','기존 인연보다 새로운 사람이 실제 관계로 이어지는 쪽',['day_combine','relationship_star','growth'],11.0],
['contact_restart','relationship','연락 재개','끝난 줄 알았던 인연과 다시 연락이 닿거나 대화가 재개되는 쪽',['day_repeat','combine_signal','relationship_star'],11.3],
['breakup_distance','relationship','관계 냉각·이별','가까운 사람과 거리를 두거나 관계의 형태를 끊어내는 쪽',['day_disrupt','break_signal','relationship_star'],11.0],
['reconciliation','relationship','재회 가능성','끊어진 관계가 다시 연결되되, 이전 문제를 그대로 두면 재차 흔들릴 수 있는 쪽',['day_combine','dayun_day','relationship_star'],12.2],
['commitment','relationship','관계 확정','애매한 관계를 약속·공식 관계처럼 현실적인 형태로 정하는 쪽',['day_combine','authority_or_wealth','contract'],11.3],
['marriage_talk','relationship','결혼 논의','연애 감정보다 일정·가족·집·돈 같은 현실 조건을 함께 맞추는 쪽',['day_combine','home_active','contract'],12.0],
['cohabitation','relationship','동거·합가','관계 변화가 실제 주거와 생활 패턴 변화까지 이어지는 쪽',['day_active','home_active','combine_signal'],11.8],
['spouse_conflict','relationship','배우자·연인 갈등','감정보다 생활·돈·역할 분담 때문에 가까운 관계의 마찰이 커지는 쪽',['day_disrupt','peer','wealth_pressure'],11.6],
['social_circle_change','relationship','인간관계 정리','친구·동료 가운데 계속 갈 사람과 멀어질 사람을 가르는 쪽',['peer','break_signal','day_or_year_active'],10.0],
['move_prepare','home','이사 준비','바로 옮기기보다 집을 알아보거나 생활권을 바꿀 준비가 먼저 시작되는 쪽',['home_active','resource','contract'],10.0],
['move_actual','home','실제 이사','생활 반경이나 주소가 실제로 달라지는 이동이 생기는 쪽',['home_disrupt','dayun_home','month_repeat'],11.6],
['independent_move','home','독립·분가','가족과 함께 살던 구조에서 빠져나와 내 생활공간을 따로 만드는 쪽',['home_disrupt','independence','day_active'],11.5],
['merge_household','home','합가·동거 이동','혼자 살던 구조보다 가족·연인과 생활공간을 합치는 쪽',['home_active','day_combine','combine_signal'],11.7],
['home_purchase_contract','home','주택 매수 계약','단순 이사보다 소유권·대출·계약이 같이 움직이는 쪽',['home_active','contract','wealth'],12.1],
['lease_contract','home','전월세 계약','집을 사는 것보다 임대차 조건·보증금·갱신이 핵심이 되는 쪽',['home_active','contract','deposit'],11.2],
['job_relocation','home','직장 때문에 이동','사는 곳 변화가 직장·근무지 변화와 같이 움직이는 쪽',['home_disrupt','month_disrupt','career_link'],11.6],
['family_relocation','home','가족 때문에 이동','내 일보다 가족 사정 때문에 생활권을 옮기는 쪽',['home_disrupt','family_active','responsibility'],12.0],
['parent_care','family','부모 돌봄·책임','부모 관련 실무나 돌봄에서 내가 맡아야 할 일이 커지는 쪽',['year_disrupt','resource','responsibility'],13.2],
['sibling_issue','family','형제·자매 문제','형제·자매와 역할·돈·거리 문제를 실제로 정리해야 하는 쪽',['year_disrupt','peer','family_active'],13.0],
['child_plan','family','자녀 계획 논의','임신 여부를 단정하는 것이 아니라 자녀 계획·양육 방향을 현실적으로 논의하는 쪽',['hour_active','resource','day_active'],13.3],
['family_finance','family','가족 재정 문제','가족 안의 돈·부담·지원 문제에서 내가 실제 의사결정을 하는 쪽',['family_active','wealth_pressure','responsibility'],13.1],
['family_role_shift','family','가족 내 역할 변화','부모·형제·자녀 사이에서 내가 맡는 역할이 이전과 달라지는 쪽',['year_or_hour_active','responsibility','dayun_family'],13.0],
['household_merge_family','family','가족 합가·분가','가족 구성 변화가 실제 거주 형태 변화로 이어지는 쪽',['family_active','home_active','contract'],13.4],
['cert_prepare','study','자격증 준비','막연한 공부보다 실제 자격·인증을 목표로 준비하는 쪽',['resource','authority','document'],13.0],
['exam_attempt','study','시험 응시·합격 판단','공부만 하는 것이 아니라 시험·선발·평가 결과를 실제로 받는 쪽',['resource','authority','public_eval'],13.5],
['important_document','study','중요 서류·행정','신분·계약·승인처럼 제출하고 확인받아야 할 문서가 중요한 쪽',['document','authority','contract'],13.0],
['license_admin','study','허가·신청·등록','사업·직장·생활에서 허가·등록·신청 절차를 처리하는 쪽',['document','authority','resource'],13.2],
['learning_restart','study','공부 재시작','당장 시험보다 새로운 분야를 배우거나 교육을 다시 시작하는 쪽',['resource','output','growth'],12.9],
['public_evaluation','study','심사·평가·선발','내 결과물이 외부 기준으로 심사되거나 선정 여부가 갈리는 쪽',['authority','public_eval','output'],13.2],
['project_launch','other','새 프로젝트 공개','준비해온 일을 실제 사람들에게 공개하거나 시작하는 쪽',['output','growth','public_eval'],10.0],
['public_visibility','other','노출·평판 증가','내 이름·성과·콘텐츠가 평소보다 더 많은 사람의 평가를 받는 쪽',['output','authority','public_eval'],10.6],
['plan_reset','other','장기 계획 재설계','당장 사건 하나보다 앞으로 몇 년의 방향을 다시 짜는 쪽',['resource','break_signal','dayun_shift'],10.2],
['major_decision','other','큰 선택','여러 선택지 중 하나를 버리고 하나를 확정해야 하는 쪽',['contract','break_signal','pressure'],10.4]
].map(([id,group,label,claim,signals,threshold])=>({id,group,label,claim,signals,threshold}));

const TOPIC_EVENT_GROUP={business:['business','money'],sidejob:['business','money'],jobchange:['career'],promotion:['career'],money:['money','business'],investment:['money'],newlove:['relationship'],reunion:['relationship'],marriage:['relationship','home'],children:['family'],relations:['relationship'],exam:['study'],realestate:['home','money'],family:['family','home'],annual:['career','business','money','relationship','home','other']};
let lib,input,natal,profileKey,currentReading,selectedTopic;
const pair=(a,b,list)=>list.includes(a+b)||list.includes(b+a);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const show=id=>{['landing','loading','result','checkout','paid'].forEach(x=>$('#'+x)?.classList.add('hide'));$('#'+id)?.classList.remove('hide');scrollTo(0,0)};
function style(){const s=document.createElement('style');s.textContent=`#readingMount,#questionMount,#sealMount,#paidMount{max-width:760px;margin:auto}.hwPaper{margin:14px 0;padding:22px 20px;background:linear-gradient(180deg,#f2eadb,#e8decb);color:#211811;border:1px solid rgba(151,120,82,.38);box-shadow:0 18px 45px rgba(0,0,0,.2)}.hwLead{border-top:3px solid #7d2a23}.hwEy{font-size:10px;font-weight:900;letter-spacing:.12em;color:#812e27;margin-bottom:8px}.hwPaper h2{margin:0 0 12px;font-family:Georgia,'Noto Serif KR',serif;font-size:22px;line-height:1.45}.hwPaper h3{margin:0 0 8px;font-size:18px;line-height:1.55}.hwPaper p{margin:0;font-size:14px;line-height:1.9;color:#50483f;word-break:keep-all}.hwTiming{margin-top:14px;padding:10px 12px;border-left:3px solid #8a3027;background:rgba(132,46,38,.07);font-size:12px;line-height:1.7}.hwGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:16px 0}.hwTopic{border:1px solid #ab987a;background:rgba(255,255,255,.28);padding:12px 8px;font-size:12px;font-weight:800;color:#30261f}.hwTopic.on{background:#752820;color:#f4eade}.hwPreview{margin-top:16px;padding-top:16px;border-top:1px solid rgba(112,82,55,.25)}.hwBlur{position:relative;margin-top:14px;overflow:hidden}.hwBlurContent{filter:blur(5px);opacity:.55;user-select:none;padding:8px 0 175px}.hwLockedRow{padding:14px 0;border-bottom:1px solid rgba(112,82,55,.17)}.hwPaywall{position:absolute;left:0;right:0;bottom:0;padding:62px 14px 18px;background:linear-gradient(180deg,rgba(235,225,207,0),#eadfca 36%,#e7dcc7);text-align:center}.hwPaywall button{width:100%;border:0;background:#74271f;color:#f6ecdf;padding:15px;font-weight:900}.hwSeal{margin:16px auto;padding:16px 18px;background:#120c0a;border:1px solid #3d2a22;color:#d8cab8}.hwSeal small,.hwSeal span{display:block;font-size:10px;color:#958679}.hwSeal b{display:block;margin:6px 0;font-family:monospace;color:#eadfce}.hwWhy{margin-top:12px}.hwWhy summary{cursor:pointer;font-size:12px;font-weight:800;color:#6f2b24}.hwWhy p{margin-top:8px!important;font-size:12px!important;line-height:1.75!important}.hwConf{display:inline-block;margin-top:8px;padding:3px 7px;border:1px solid #a98d72;font-size:10px;font-weight:800;color:#725c49}.hwFive{display:grid;gap:8px}.hwYear{display:grid;grid-template-columns:64px 1fr;gap:12px;padding:12px 0;border-bottom:1px solid rgba(112,82,55,.18)}.hwYear b{font-family:Georgia,serif;font-size:18px}.hwYear span{font-size:13px;line-height:1.7;color:#5b5046}.hwWarn{padding:12px;background:rgba(129,46,39,.06);border-left:3px solid #812e27;font-size:12px;line-height:1.75}.hide{display:none!important}@media(max-width:390px){.hwPaper{padding:19px 16px}.hwPaper h2{font-size:20px}}`;document.head.appendChild(s)}
function setup(){for(let i=0;i<24;i++)$('#hour').insertAdjacentHTML('beforeend',`<option value="${i}" ${i===12?'selected':''}>${String(i).padStart(2,'0')}시</option>`);$('#enterBtn').onclick=()=>$('#consult').scrollIntoView({behavior:'smooth'});$$('.sex').forEach(b=>b.onclick=()=>{$$('.sex').forEach(x=>x.classList.remove('on'));b.classList.add('on')});$$('.cal').forEach(b=>b.onclick=()=>{$$('.cal').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#calendar').value=b.dataset.cal;$('#leapWrap').classList.toggle('hide',b.dataset.cal!=='lunar')});$('#unknown').onchange=e=>{$('#hour').disabled=e.target.checked;$('#minute').disabled=e.target.checked};$('#back').onclick=()=>show('result');$('#restart').onclick=()=>location.reload()}
function getInput(){const unknown=$('#unknown').checked;return{year:+$('#year').value,month:+$('#month').value,day:+$('#day').value,hour:unknown?12:+$('#hour').value,minute:unknown?0:+$('#minute').value,gender:$('.sex.on')?.dataset.sex||'female',isLunar:$('#calendar').value==='lunar',isLeapMonth:$('#calendar').value==='lunar'&&$('#leap').checked,unknown,city:$('#city').value,name:$('#name').value.trim()||'당신',trueSolarTime:{longitude:LONG[$('#city').value]||126.978,applyEquationOfTime:true,applyHistoricalDst:true},dayBoundary:'midnight'} }
function valid(v){if(!v.year||v.year<1900||v.year>2100)return'출생연도를 확인해주세요.';if(v.month<1||v.month>12||v.day<1||v.day>31)return'생년월일을 확인해주세요.';if(!v.isLunar){const d=new Date(v.year,v.month-1,v.day);if(d.getFullYear()!==v.year||d.getMonth()!==v.month-1||d.getDate()!==v.day)return'존재하지 않는 날짜입니다.'}if(!v.unknown&&(v.minute<0||v.minute>59))return'태어난 시간을 확인해주세요.';return''}
async function hash(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function makeProfileKey(v){return(await hash(JSON.stringify([VERSION,v.year,v.month,v.day,v.unknown?'unknown':[v.hour,v.minute],v.city,v.gender,v.isLunar,v.isLeapMonth]))).slice(0,18)}
function quota(id){const k='hyun14-'+new Date().toISOString().slice(0,10);let a=[];try{a=JSON.parse(localStorage.getItem(k)||'[]')}catch{}if(a.includes(id))return true;if(a.length>=DAILY_LIMIT)return false;a.push(id);localStorage.setItem(k,JSON.stringify(a));return true}
function relation(a,b,natalBranches=[]){if(!a||!b)return null;if(pair(a,b,CLASH))return{type:'clash',w:6,disrupt:true};if(pair(a,b,HARM))return{type:'harm',w:3.6,disrupt:true};if(pair(a,b,BREAK))return{type:'break',w:3.1,disrupt:true};if(pair(a,b,COMB))return{type:'combine',w:3.1,combine:true};if(a===b&&SELF.includes(a))return{type:'self',w:3.2,disrupt:true};if((a==='자'&&b==='묘')||(a==='묘'&&b==='자'))return{type:'punish',w:4.0,disrupt:true};for(const g of PUNISH)if(g.includes(a)&&g.includes(b)&&g.some(x=>natalBranches.includes(x)&&x!==a&&x!==b))return{type:'punish',w:4.3,disrupt:true};for(const g of TRI)if(g.includes(b)){const rest=g.filter(x=>x!==b);if(rest.every(x=>natalBranches.includes(x)))return{type:'triad',w:4.7,combine:true}}if(a===b)return{type:'repeat',w:1.8,repeat:true};return null}
function stemRelation(a,b){if(!a||!b)return null;if(pair(a,b,STEM_COMB))return{type:'combine',w:2.8};if(pair(a,b,STEM_CLASH))return{type:'clash',w:3.4};return null}
function pparts(x){if(!x)return{};const g=x.korean||x.ganji||'';return{stem:x.heavenlyStem||g[0],branch:x.earthlyBranch||g[1]}}
function dayun(r,v,year){const age=year-v.year;return(r.luckPillars?.pillars||[]).find(x=>age>=x.age&&age<x.age+10)||null}
function tenGodGroup(g){if(['정관','편관'].includes(g))return'authority';if(['정재','편재'].includes(g))return'wealth';if(['식신','상관'].includes(g))return'output';if(['정인','편인'].includes(g))return'resource';if(['비견','겁재'].includes(g))return'peer';return'other'}
function strengthProfile(r,v){const dayEl=STEM_ELEMENT[r.day.heavenlyStem];let support=0,drain=0;const weightPos=[['month',2.4],['day',1.4],['year',1],['hour',v.unknown?0:1]];for(const [p,w] of weightPos){if(!w)continue;const br=r[p].earthlyBranch,el=BRANCH_ELEMENT[br];if(el===dayEl||GENERATES[el]===dayEl)support+=w;if(GENERATES[dayEl]===el||CONTROLS[dayEl]===el||CONTROLS[el]===dayEl)drain+=w*.72;for(const hs of HIDDEN[br]||[]){const h=STEM_ELEMENT[hs];if(h===dayEl||GENERATES[h]===dayEl)support+=w*.25;else drain+=w*.15}}for(const p of ['year','month',...(v.unknown?[]:['hour'])]){const el=STEM_ELEMENT[r[p].heavenlyStem];if(el===dayEl||GENERATES[el]===dayEl)support+=.55;else drain+=.38}const delta=support-drain;return{delta,state:delta>1.4?'strong':delta<-1.4?'weak':'balanced'}}
function annualFeatures(r,v,year){const y=lib.calculateFourPillars({year,month:7,day:1,hour:12,minute:0,gender:v.gender}).year;const yg1=lib.getTenGod(r.day.heavenlyStem,y.heavenlyStem),yg2=lib.getBranchTenGod(r.day.heavenlyStem,y.earthlyBranch);const sig={},reasons={};const add=(k,val,why)=>{sig[k]=(sig[k]||0)+val;(reasons[k]??=[]).push(why)};const natalBranches=[r.year.earthlyBranch,r.month.earthlyBranch,r.day.earthlyBranch,...(v.unknown?[]:[r.hour.earthlyBranch])];
 const godGroups=[tenGodGroup(yg1),tenGodGroup(yg2),...(HIDDEN[y.earthlyBranch]||[]).map(s=>tenGodGroup(lib.getTenGod(r.day.heavenlyStem,s)))];for(const g of godGroups){if(g==='authority'){add('authority',1.55,'책임·평가 신호');add('pressure',.65,'압박 신호');add('public_eval',.55,'외부 평가 신호')}if(g==='wealth'){add('wealth',1.55,'돈·거래 신호');add('cashflow',.55,'현금흐름 신호');add('contract',.45,'거래 조건 신호')}if(g==='output'){add('output',1.55,'성과·생산 신호');add('independence',.6,'독립 실행 신호');add('growth',.45,'확장 신호')}if(g==='resource'){add('resource',1.5,'준비·문서 신호');add('document',.65,'문서 신호')}if(g==='peer'){add('peer',1.45,'사람·경쟁 신호');add('independence',.4,'독립성 신호')}}
 const pos=[['year',r.year],['month',r.month],['day',r.day],...(v.unknown?[]:[['hour',r.hour]])];for(const [p,n] of pos){const br=relation(n.earthlyBranch,y.earthlyBranch,natalBranches),sr=stemRelation(n.heavenlyStem,y.heavenlyStem);if(br){const key=p+(br.disrupt?'_disrupt':br.combine?'_combine':br.repeat?'_repeat':'_active');add(key,br.w,`${p} 자리 ${br.type}`);add(p+'_active',br.w*.55,`${p} 자리 활성`);if(br.disrupt)add('break_signal',br.w*.55,'끊고 바꾸는 작용');if(br.combine)add('combine_signal',br.w*.55,'묶이고 정해지는 작용');if(p==='month'){add('career_link',br.w*.6,'직장·사회 자리');add('home_active',br.w*.35,'생활권 자리');if(br.disrupt)add('home_disrupt',br.w*.35,'생활권 변화')}if(p==='day'){add('relationship_star',br.w*.65,'가까운 관계 자리');add('home_active',br.w*.45,'생활 자리');if(br.disrupt)add('home_disrupt',br.w*.42,'생활 자리 변화')}if(p==='year'){add('family_active',br.w*.6,'가족·기반 자리');if(br.disrupt)add('responsibility',br.w*.25,'가족 책임 신호')}if(p==='hour'){add('family_active',br.w*.45,'후반 계획·자녀 자리');add('hour_active',br.w*.5,'후반 계획 자리')}}if(sr){add('stem_'+sr.type,sr.w,`${p} 천간 ${sr.type}`);if(sr.type==='clash')add('break_signal',sr.w*.3,'천간 충돌')}}
 const d=pparts(dayun(r,v,year));if(d.stem){const dg=tenGodGroup(lib.getTenGod(r.day.heavenlyStem,d.stem));add('dayun_'+dg,1.6,'10년 흐름의 '+dg);if(dg==='authority')add('dayun_authority',1.6,'10년 책임 흐름');if(dg==='wealth')add('dayun_wealth',1.6,'10년 재물 흐름');if(dg==='output')add('dayun_output',1.6,'10년 성과 흐름');if(dg==='resource')add('dayun_resource',1.6,'10년 준비 흐름');if(dg==='peer')add('dayun_peer',1.6,'10년 사람 흐름')}
 if(d.branch){for(const [p,n] of pos){const dr=relation(n.earthlyBranch,d.branch,natalBranches);if(dr){add('dayun_'+p,dr.w*.65,`10년 흐름이 ${p} 자리와 맞물림`);if(p==='month')add('dayun_month',dr.w*.65,'10년 흐름과 직장 자리 중첩');if(p==='day')add('dayun_day',dr.w*.65,'10년 흐름과 가까운 관계 자리 중첩');if(p==='year')add('dayun_family',dr.w*.65,'10년 흐름과 가족 자리 중첩');if(['month','day'].includes(p))add('dayun_home',dr.w*.4,'10년 흐름과 생활 자리 중첩')}}const yd=relation(d.branch,y.earthlyBranch,natalBranches);if(yd){add('dayun_shift',yd.w*.55,'10년 흐름과 해당 연도 중첩');if(yd.disrupt)add('pressure',yd.w*.35,'큰 흐름의 압박')}}
 const str=strengthProfile(r,v);if(str.state==='weak'&&((sig.authority||0)+(sig.wealth||0)>3)){add('wealth_pressure',.9,'감당해야 할 현실 부담');add('pressure',.8,'현실 압박')}if(str.state==='strong'&&(sig.output||0)>1.5)add('growth',.7,'실행력이 밖으로 나가는 흐름');if((sig.output||0)>1.4&&(sig.wealth||0)>1.4){add('cashflow',1.0,'성과와 돈 신호가 함께 움직임');add('growth',.7,'성과→수입 연결')}if((sig.authority||0)>1.4&&(sig.resource||0)>1.2){add('document',.9,'평가와 문서가 함께 움직임');add('public_eval',.7,'평가·인증 결합')}if((sig.peer||0)>1.3&&(sig.wealth||0)>1.3)add('wealth_pressure',.8,'사람과 돈이 함께 움직임');if((sig.wealth||0)>1.4&&(sig.authority||0)>1.4)add('contract',.8,'돈과 책임 조건이 함께 움직임');if((sig.resource||0)>1.4&&(sig.break_signal||0)>1)add('closure',.8,'정리·재설계 신호');if((sig.home_active||0)>1)add('deposit',.35,'주거와 목돈의 연결');if((sig.day_active||0)>1&&(sig.year_active||0)>1)add('day_or_year_active',.6,'가까운 관계와 기반이 함께 움직임');if((sig.year_active||0)>1||(sig.hour_active||0)>1)add('year_or_hour_active',.7,'가족·후반 계획 자리 활성');if((sig.authority||0)>1.2||(sig.wealth||0)>1.2)add('authority_or_wealth',.8,'현실 조건 신호');
 return{year,pillar:y.heavenlyStem+y.earthlyBranch,sig,reasons,strength:str,yearGods:[yg1,yg2]}}
function signalScore(f,key){return f.sig[key]||0}
function eventRaw(event,feat){let score=0;const hits=[];for(const k of event.signals){const v=signalScore(feat,k);if(v>0){score+=Math.min(4,v);hits.push(k)}}// 세부 사건별 추가 차등
 if(event.group==='career'){score+=(feat.sig.month_active||0)*.28+(feat.sig.dayun_month||0)*.22}
 if(event.group==='business'){score+=(feat.sig.output||0)*.22+(feat.sig.wealth||0)*.2}
 if(event.group==='money'){score+=(feat.sig.wealth||0)*.22+(feat.sig.contract||0)*.16}
 if(event.group==='relationship'){score+=(feat.sig.day_active||0)*.25+(feat.sig.relationship_star||0)*.18}
 if(event.group==='home'){score+=(feat.sig.home_active||0)*.27+(feat.sig.dayun_home||0)*.18}
 if(event.group==='family'){score+=(feat.sig.family_active||0)*.24+(feat.sig.responsibility||0)*.18}
 if(event.group==='study'){score+=(feat.sig.resource||0)*.22+(feat.sig.document||0)*.2}
 return{score,hits}}
function monthSupport(r,v,year,event){const rows=[];for(let m=1;m<=12;m++){const x=lib.calculateFourPillars({year,month:m,day:15,hour:12,minute:0,gender:v.gender}).month;const sg=lib.getTenGod(r.day.heavenlyStem,x.heavenlyStem),bg=lib.getBranchTenGod(r.day.heavenlyStem,x.earthlyBranch),s={authority:0,wealth:0,output:0,resource:0,peer:0,contract:0,break_signal:0,combine_signal:0,month_active:0,day_active:0,home_active:0,family_active:0,relationship_star:0};for(const g of [tenGodGroup(sg),tenGodGroup(bg)]){if(g in s)s[g]+=1.4;if(g==='wealth')s.contract+=.35}const natalBranches=[r.year.earthlyBranch,r.month.earthlyBranch,r.day.earthlyBranch,...(v.unknown?[]:[r.hour.earthlyBranch])];for(const [p,b] of [['month',r.month.earthlyBranch],['day',r.day.earthlyBranch],['year',r.year.earthlyBranch],...(v.unknown?[]:[['hour',r.hour.earthlyBranch]])]){const rel=relation(b,x.earthlyBranch,natalBranches);if(!rel)continue;if(p==='month'){s.month_active+=rel.w*.8;s.home_active+=rel.w*.3}if(p==='day'){s.day_active+=rel.w*.8;s.relationship_star+=rel.w*.45;s.home_active+=rel.w*.35}if(p==='year'||p==='hour')s.family_active+=rel.w*.45;if(rel.disrupt)s.break_signal+=rel.w*.45;if(rel.combine)s.combine_signal+=rel.w*.45}let val=0;for(const k of event.signals){const alias=k.startsWith('dayun_')?k.replace('dayun_',''):k;if(s[alias])val+=Math.min(2.2,s[alias])}if(event.group==='career')val+=s.month_active*.25;if(event.group==='relationship')val+=s.day_active*.25;if(event.group==='home')val+=s.home_active*.25;if(event.group==='family')val+=s.family_active*.2;rows.push({month:m,score:val})}rows.sort((a,b)=>b.score-a.score);const top=rows.slice(0,3),mean=rows.reduce((a,x)=>a+x.score,0)/12;const coherent=top[0]&&top[0].score>=Math.max(3.2,mean*1.55);return{coherent,months:coherent?top.filter(x=>x.score>=top[0].score*.78).slice(0,2).map(x=>x.month):[],strength:top[0]?.score||0}}
function confidenceCandidate(event,feat,prev,next,monthly){const raw=eventRaw(event,feat);let score=raw.score;const kinds=new Set();for(const h of raw.hits){if(h.startsWith('dayun_'))kinds.add('dayun');else if(['month_disrupt','month_active','day_disrupt','day_active','year_disrupt','year_active','hour_active','home_active','family_active','day_combine','day_repeat'].includes(h))kinds.add('natal-position');else if(['authority','wealth','output','resource','peer','relationship_star','authority_or_wealth'].includes(h))kinds.add('year-gods');else if(['contract','document','cashflow','growth','pressure','break_signal','combine_signal','public_eval','risk','closure'].includes(h))kinds.add('combined-signal');}
 const pr=eventRaw(event,prev).score,nx=eventRaw(event,next).score;let sequence='isolated';if(pr>=event.threshold*.55&&raw.score>=pr*1.05){score+=1.15;kinds.add('sequence');sequence='build'}if(nx>=event.threshold*.55&&raw.score>=nx*.95){score+=.8;kinds.add('sequence');if(sequence==='isolated')sequence='peak'}if(pr>=event.threshold*.5&&nx>=event.threshold*.5){score+=.7;kinds.add('sequence');sequence='middle'}if(monthly.coherent){score+=1.8;kinds.add('month')}
 const requiredKinds=(event.group==='family'||event.group==='study')?4:3;const threshold=event.threshold+(event.group==='relationship'?0.7:0);const conf=Math.max(0,Math.min(99,Math.round(42+(score-threshold)*8+kinds.size*5+(monthly.coherent?4:0))));return{event,year:feat.year,score,raw:raw.score,kinds:[...kinds],confidence:conf,months:monthly.months,sequence,passed:score>=threshold&&kinds.size>=requiredKinds&&conf>=72}}
function buildCandidates(r,v,start,end){const feats={};for(let y=start-1;y<=end+1;y++)feats[y]=annualFeatures(r,v,y);const prelim=[];for(let y=start;y<=end;y++)for(const e of EVENTS){const rr=eventRaw(e,feats[y]);if(rr.score>=e.threshold*.72)prelim.push({e,y,raw:rr.score})}prelim.sort((a,b)=>b.raw-a.raw);const selected=prelim.slice(0,Math.min(34,prelim.length));const out=[];for(const p of selected){const monthly=monthSupport(r,v,p.y,p.e),c=confidenceCandidate(p.e,feats[p.y],feats[p.y-1],feats[p.y+1],monthly);if(c.passed)out.push(c)}return out.sort((a,b)=>b.confidence-a.confidence||b.score-a.score)}
function dedupe(cands,max=2){const out=[],usedGroups=new Set(),usedClaims=[];for(const c of cands){if(out.length>=max)break;if(usedGroups.has(c.event.group))continue;const words=new Set(c.event.claim.split(/[· ,]/).filter(x=>x.length>1));let similar=false;for(const w of usedClaims){let overlap=0;for(const x of words)if(w.has(x))overlap++;if(overlap>=2){similar=true;break}}if(similar)continue;out.push(c);usedGroups.add(c.event.group);usedClaims.push(words)}return out}
function timingText(c){if(!c.months.length)return'월 단위로는 한두 달만 강하게 튀는 흐름이 아니라 연중에 걸쳐 보입니다.';return`양력 ${c.months.join('월·')} 전후가 같은 신호를 한 번 더 확인시켜 줍니다. 절기 기준이라 체감은 앞뒤로 약 1~2주 차이가 날 수 있습니다.`}
function sequenceText(c){if(c.sequence==='build')return'앞해에는 전조가 약하게 보이고, 이 해에 실제 선택이나 변화가 더 커지는 흐름입니다.';if(c.sequence==='middle')return'한 해만 뚝 떨어진 사건이라기보다 앞뒤 해를 잇는 변화의 한가운데에 가깝습니다.';if(c.sequence==='peak')return'이 해가 가장 강하고, 다음 해에는 결과를 정리하거나 자리잡는 흐름으로 이어집니다.';return'앞뒤 해보다 이 해 자체가 상대적으로 더 선명합니다.'}
function humanReason(c){const map={dayun:'10년 단위 큰 흐름', 'natal-position':'태어난 사주의 실제 자리 변화','year-gods':'그 해 들어오는 일·돈·관계 성격','combined-signal':'여러 신호의 동시 작용',sequence:'앞뒤 3년의 연결',month:'그 해 월별 재확인'};return c.kinds.map(k=>map[k]||k).join(' · ')}
function renderFirst(reading,replay=false){const past=reading.past,future=reading.future;let html=`<section class="hwPaper hwLead"><div class="hwEy">첫 풀이 원칙</div><h2>${past.length?'강한 과거만 짚었습니다.':'억지로 과거를 찍지 않았습니다.'}</h2><p>${past.length?'최근 여러 해 중 근거가 겹치는 사건만 남겼습니다. 같은 뜻의 문장은 반복하지 않았습니다.':'최근 흐름에서 특정 사건을 자신 있게 말할 만큼 근거가 겹치지 않아, 약한 추측은 뺐습니다.'}</p></section>`;for(const c of past){html+=`<section class="hwPaper"><div class="hwEy">${c.year}년 · 지나온 흐름</div><h2>${esc(c.event.label)}</h2><p><b>${c.year}년은 ${esc(c.event.claim)}</b>을 먼저 봅니다. ${sequenceText(c)}</p><div class="hwTiming">${timingText(c)}</div><span class="hwConf">근거 일치도 ${c.confidence}%</span><details class="hwWhy"><summary>왜 이 시기를 골랐는지 보기</summary><p>${esc(humanReason(c))}. 한 가지 신호만으로 사건을 단정하지 않고 서로 다른 근거가 겹친 경우만 표시했습니다.</p></details></section>`}
 html+=`<section class="hwPaper"><div class="hwEy">앞으로 먼저 볼 것</div>${future.length?future.map(c=>`<div style="margin-bottom:18px"><h2>${c.year}년 · ${esc(c.event.label)}</h2><p>${esc(c.event.claim)}이 다른 사건보다 먼저 올라옵니다. ${sequenceText(c)}</p><div class="hwTiming">${timingText(c)}</div><span class="hwConf">근거 일치도 ${c.confidence}%</span></div>`).join(''):`<h2>가까운 3년에서 한 사건을 억지로 찍지는 않겠습니다.</h2><p>현재 기준으로는 특정 사건 하나가 다른 신호를 압도하지 않습니다. 질문을 고르면 그 주제 안에서만 다시 좁혀 봅니다.</p>`}</section>`;$('#readingMount').innerHTML=html;$('#replayNote').textContent=replay?'전에 본 같은 명식입니다. V14는 같은 계산 결과를 그대로 다시 보여드립니다.':'고민을 받기 전에 근거가 겹치는 사건만 먼저 추렸습니다.';renderTopics()}
function candidatesForTopic(topic){if(topic==='compatibility')return[];const groups=TOPIC_EVENT_GROUP[topic]||[];const now=new Date().getFullYear();return buildCandidates(natal,input,now,now+5).filter(c=>groups.includes(c.event.group)).sort((a,b)=>b.confidence-a.confidence)}
function renderTopics(){const buttons=TOPICS.map(([id,label])=>`<button class="hwTopic" data-topic="${id}">${label}</button>`).join('');$('#questionMount').innerHTML=`<section class="hwPaper"><div class="hwEy">이제 질문을 고르세요</div><h2>첫 풀이와 별개로, 보고 싶은 문제만 좁혀 봅니다.</h2><div class="hwGrid">${buttons}</div><div id="topicPreview"></div></section>`;$$('.hwTopic').forEach(b=>b.onclick=()=>{selectedTopic=b.dataset.topic;$$('.hwTopic').forEach(x=>x.classList.toggle('on',x===b));renderTopicPreview(selectedTopic)})}
function renderTopicPreview(topic){const label=TOPICS.find(x=>x[0]===topic)?.[1]||'';if(topic==='compatibility'){$('#topicPreview').innerHTML=`<div class="hwPreview"><h3>궁합은 상대방의 생년월일시가 필요합니다.</h3><p>한 사람의 명식만으로 특정 상대와의 궁합을 아는 척하지 않습니다. 정식 버전에서는 상대 정보를 받은 뒤 두 명식을 함께 계산합니다.</p></div>`;return}const cands=candidatesForTopic(topic),top=cands[0];if(!top){$('#topicPreview').innerHTML=`<div class="hwPreview"><h3>${label}</h3><p>이 주제에서는 가까운 5년 안에 한 시기를 강하게 단정할 만큼 근거가 충분하지 않습니다. 약한 신호를 결제 유도로 과장하지 않겠습니다.</p></div>`;return}const second=cands.find(x=>x.event.id!==top.event.id&&x.year!==top.year);$('#topicPreview').innerHTML=`<div class="hwPreview"><div class="hwEy">${label} · 무료 공개</div><h3>${top.year}년, ${esc(top.event.label)} 쪽이 가장 먼저 잡힙니다.</h3><p>${esc(top.event.claim)}이 핵심입니다. ${sequenceText(top)}</p><div class="hwTiming">${timingText(top)}</div><div class="hwBlur"><div class="hwBlurContent"><div class="hwLockedRow"><b>${second?`${second.year}년 · ${esc(second.event.label)}`:'그다음 변곡 시기'}</b><p>${second?esc(second.event.claim):'첫 시기 다음에 무엇을 확인해야 하는지'}</p></div><div class="hwLockedRow"><b>움직여도 되는 달 / 멈춰볼 달</b><p>월별 흐름에서 같은 신호가 반복되는 구간을 분리합니다.</p></div><div class="hwLockedRow"><b>5년 흐름과 선택 기준</b><p>한 해만 보지 않고 앞뒤 연결까지 이어서 봅니다.</p></div></div><div class="hwPaywall"><span>현월당 심층 풀이</span><h3>답에 가까운 부분부터 더 좁혀 봅니다.</h3><strong>29,000원</strong><button id="unlock">이 풀이 끝까지 보기 →</button></div></div></div>`;$('#unlock').onclick=()=>{$('#checkoutTitle').textContent=label+' 심층 풀이';$('#orderLabel').textContent=label+' · 5년 흐름 · 월별 시기';show('checkout')}}
function renderPaid(){const label=TOPICS.find(x=>x[0]===selectedTopic)?.[1]||'심층 풀이',cands=candidatesForTopic(selectedTopic).slice(0,5);$('#paidTitle').textContent=label+' 전체 풀이';if(!cands.length){$('#paidMount').innerHTML=`<section class="hwPaper"><h2>강한 시기를 억지로 만들지 않았습니다.</h2><p>현재 엔진 기준으로 이 주제는 근거가 충분하지 않습니다. 실제 결제 버전에서는 이런 경우 결제 전 안내하거나 다른 질문으로 전환해야 합니다.</p></section>`;show('paid');return}const main=cands[0];$('#paidMount').innerHTML=`<section class="hwPaper hwLead"><div class="hwEy">먼저 결론</div><h2>${main.year}년 · ${esc(main.event.label)}</h2><p>${esc(main.event.claim)}이 가장 강합니다. ${sequenceText(main)}</p><div class="hwTiming">${timingText(main)}</div></section><section class="hwPaper"><div class="hwEy">향후 5년에서 강한 순서</div><div class="hwFive">${cands.map(c=>`<div class="hwYear"><b>${c.year}</b><span><strong>${esc(c.event.label)}</strong><br>${esc(c.event.claim)}<br><small>근거 일치도 ${c.confidence}%</small></span></div>`).join('')}</div></section><section class="hwPaper"><div class="hwEy">판단 기준</div><h2>사주만으로 결정을 대신하지 않습니다.</h2><p>현월당은 시기 후보를 좁혀주는 참고 도구입니다. 돈·계약·직장·부동산처럼 손실이 큰 결정은 실제 조건, 계약서, 현금흐름과 함께 확인하세요.</p></section>`;show('paid')}
function makeReading(){const now=new Date().getFullYear(),past=dedupe(buildCandidates(natal,input,now-9,now-1),2),future=dedupe(buildCandidates(natal,input,now,now+3),2);return{version:VERSION,createdAt:new Date().toISOString(),past:past.map(serialise),future:future.map(serialise)}}
function serialise(c){return{event:c.event,year:c.year,score:c.score,raw:c.raw,kinds:c.kinds,confidence:c.confidence,months:c.months,sequence:c.sequence,passed:c.passed}}
function revive(read){return{...read,past:(read.past||[]).map(x=>({...x,event:EVENTS.find(e=>e.id===x.event.id)||x.event})),future:(read.future||[]).map(x=>({...x,event:EVENTS.find(e=>e.id===x.event.id)||x.event}))}}
async function submit(e){e.preventDefault();input=getInput();const err=valid(input);if(err){$('#notice').innerHTML=`<div class="hwWarn">${err}</div>`;return}profileKey=await makeProfileKey(input);if(!quota(profileKey)){$('#notice').innerHTML=`<div class="hwWarn">오늘 무료로 새 명식을 볼 수 있는 횟수를 모두 사용했습니다. 이미 본 명식은 다시 볼 수 있습니다.</div>`;return}show('loading');await new Promise(r=>setTimeout(r,520));try{natal=lib.calculateFourPillars(input)}catch(err){console.error(err);show('landing');$('#notice').innerHTML=`<div class="hwWarn">만세력 계산 중 오류가 났습니다. 음력·윤달·날짜를 다시 확인해주세요.</div>`;return}const key='hyun14-reading-'+profileKey;let replay=false;try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.version===VERSION){currentReading=revive(saved);replay=true}}catch{}if(!currentReading){currentReading=makeReading();localStorage.setItem(key,JSON.stringify(currentReading))}renderFirst(currentReading,replay);const seal=await hash(profileKey+'|'+currentReading.createdAt+'|'+VERSION);$('#sealMount').innerHTML=`<section class="hwSeal"><small>첫 풀이 기록 · ${currentReading.createdAt.slice(0,10)}</small><b>${seal.slice(0,12).toUpperCase()}</b><span>같은 명식의 V14 첫 풀이는 다시 생성하지 않습니다.</span></section>`;show('result')}
async function init(){style();setup();try{lib=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm')}catch(e){console.error(e);alert('만세력 엔진을 불러오지 못했습니다. 새로고침 후 다시 시도해주세요.');return}$('#f').addEventListener('submit',submit);$('#pay').onclick=renderPaid}
init();