const $=s=>document.querySelector(s);
let LIB=null,lastRendered='';
const LONG={서울:126.9780,부산:129.0756,대구:128.6014,인천:126.7052,광주:126.8526,대전:127.3845,울산:129.3114,세종:127.2890,경기:127.0286,강원:127.7298,충북:127.4914,충남:126.6728,전북:127.1088,전남:126.4629,경북:128.5056,경남:128.6811,제주:126.5312};
const CLASH=['자오','축미','인신','묘유','진술','사해'],COMB=['자축','인해','묘술','진유','사신','오미'];
const pair=(a,b,list)=>list.includes(a+b)||list.includes(b+a);
const group=g=>['정재','편재'].includes(g)?'wealth':['식신','상관'].includes(g)?'output':['정관','편관'].includes(g)?'authority':['정인','편인'].includes(g)?'resource':['비견','겁재'].includes(g)?'peer':'other';
const GROUP_TXT={wealth:'돈·거래가 직접 움직이는 흐름',output:'내 결과가 돈이나 기회로 이어지는 흐름',authority:'직장·책임·평가 변화가 현실 조건과 연결되는 흐름',resource:'벌리기보다 준비·정리·기반을 다지는 흐름',peer:'사람과 돈, 몫과 경쟁이 함께 움직이는 흐름',other:'생활의 우선순위를 다시 잡는 흐름'};
const TOPIC={
'사업·창업':{core:'사업은 시작보다 “반복해서 돈이 되는 구조”가 잡히는 시기를 봐야 합니다.',good:'새 고객·새 상품·새 채널을 시험하고 작은 매출을 반복시키는 것',bad:'초기 반응만 보고 고정비·인력·재고를 먼저 크게 늘리는 것'},
'부업·투잡':{core:'부업은 많이 벌이는 것보다 하나가 두 번, 세 번 반복 수입으로 이어지는지를 봅니다.',good:'작은 단가라도 반복 구매·반복 의뢰가 생기는 일에 집중하는 것',bad:'본업이 힘들다는 이유만으로 검증 안 된 부업을 본업처럼 키우는 것'},
'이직·퇴사':{core:'이직은 나갈 수 있는 때보다 “나간 뒤 같은 문제가 반복되지 않는 때”를 보는 게 중요합니다.',good:'보상·역할·사람 중 퇴사 이유를 하나로 분명히 하고 움직이는 것',bad:'감정이 가장 큰 순간에 조건 확인 없이 사표부터 쓰는 것'},
'직장·승진':{core:'직장운은 직책보다 역할·평가·보상이 어떤 순서로 움직이는지를 봅니다.',good:'내가 만든 성과를 기록하고 평가 기준을 내 편으로 만드는 것',bad:'일만 늘었는데 보상과 권한이 따라오지 않는 구조를 오래 방치하는 것'},
'재물·돈 흐름':{core:'재물운은 “얼마가 들어오나”보다 돈이 들어오고 남는 구조가 언제 바뀌는지를 봐야 합니다.',good:'새 수입원과 반복 수입을 만들되 현금이 실제로 남는지 확인하는 것',bad:'수입이 늘었다는 이유만으로 고정비·대출·투입금을 같이 키우는 것'},
'투자·계약':{core:'투자·계약은 좋은 운보다 돈이 묶이는 기간과 빠져나올 조건을 먼저 봐야 합니다.',good:'회수 조건·해지 조건·현금 비중을 먼저 정하고 들어가는 것',bad:'시기가 좋다는 이유만으로 가격·계약서·손실 가능성을 건너뛰는 것'},
'새 연애':{core:'새 연애는 사람을 만나는 때보다 관계가 실제 생활 안으로 들어오는 때를 봅니다.',good:'연락 빈도보다 생활 리듬과 약속이 맞는 사람을 보는 것',bad:'초반 속도만 빠른 관계를 깊은 인연으로 단정하는 것'},
'재회':{core:'재회는 연락이 오는 때와 다시 만나도 되는 때를 나눠서 봐야 합니다.',good:'예전에 갈라진 이유가 실제로 달라졌는지 확인하는 것',bad:'그리움만으로 예전 관계 방식 그대로 돌아가는 것'},
'결혼 시기':{core:'결혼은 감정이 좋은 때보다 집·돈·일정·가족 조건이 함께 맞는 때가 중요합니다.',good:'주거·돈·일정 문제를 현실적으로 먼저 맞춰보는 것',bad:'관계가 좋다는 이유만으로 생활 조건을 뒤로 미루는 것'},
'자녀·가족계획':{core:'가족계획은 임신 여부를 단정하기보다 일·주거·돌봄 조건이 함께 맞춰지는 흐름을 봅니다.',good:'생활과 돌봄 계획을 실제 일정으로 바꾸는 것',bad:'건강·임신 가능성을 사주만으로 판단하는 것'},
'인간관계':{core:'인간관계는 새 사람보다 지금 곁에 있는 사람 중 누구를 남길지를 보는 흐름이 중요합니다.',good:'반복해서 에너지를 빼앗는 관계와 거리를 다시 잡는 것',bad:'외로움 때문에 끝난 관계를 억지로 붙잡는 것'},
'시험·자격':{core:'시험운은 공부량보다 준비가 실제 평가와 결과로 연결되는 시점을 봅니다.',good:'응시·제출·면접처럼 결과가 남는 일정에 맞춰 준비하는 것',bad:'준비만 길게 하고 실제 평가 일정을 계속 미루는 것'},
'이사·부동산':{core:'부동산은 이사운과 매수운을 같은 것으로 보면 안 됩니다.',good:'생활 이동인지 자산 매수인지 목적을 먼저 분리하는 것',bad:'이사 욕구를 곧바로 매수 타이밍으로 받아들이는 것'},
'가족 문제':{core:'가족운은 걱정보다 내가 실제 돈·시간·결정을 써야 하는 시기를 봅니다.',good:'내가 맡을 몫과 다른 가족이 맡을 몫을 분명히 하는 것',bad:'책임감 때문에 모든 문제를 혼자 떠안는 것'},
'올해 전체운':{core:'올해는 모든 영역을 한꺼번에 좋고 나쁨으로 자르기보다, 무엇이 먼저 움직이는지 순서를 보는 게 중요합니다.',good:'먼저 움직이는 영역에 힘을 몰아주는 것',bad:'일·돈·관계를 한 번에 다 바꾸려는 것'}
};
function input(){const unknown=$('#unknown')?.checked;return{year:+$('#year')?.value,month:+$('#month')?.value,day:+$('#day')?.value,hour:unknown?12:+($('#hour')?.value||12),minute:unknown?0:+($('#minute')?.value||0),gender:document.querySelector('.sex.on')?.dataset.sex||'female',isLunar:$('#calendar')?.value==='lunar',isLeapMonth:$('#calendar')?.value==='lunar'&&$('#leap')?.checked,city:$('#city')?.value||'서울',unknown}}
function annual(natal,v,year){const y=LIB.calculateFourPillars({year,month:7,day:1,hour:12,minute:0,gender:v.gender}).year;const a=group(LIB.getTenGod(natal.day.heavenlyStem,y.heavenlyStem)),b=group(LIB.getBranchTenGod(natal.day.heavenlyStem,y.earthlyBranch));const s={wealth:0,output:0,authority:0,resource:0,peer:0,move:0,relation:0,pressure:0};for(const g of [a,b])s[g]+=2;for(const [p,br] of [['year',natal.year.earthlyBranch],['month',natal.month.earthlyBranch],['day',natal.day.earthlyBranch],...(v.unknown?[]:[['hour',natal.hour.earthlyBranch]])]){if(pair(br,y.earthlyBranch,CLASH)){s.pressure+=1.8;if(p==='month')s.move+=2;if(p==='day'){s.move+=1;s.relation+=2}if(p==='year'||p==='hour')s.relation+=1}if(pair(br,y.earthlyBranch,COMB)){if(p==='day')s.relation+=1.8;if(p==='month')s.move+=.9}}
 return{year,pillar:y.heavenlyStem+y.earthlyBranch,groups:[a,b],s}}
function topicScore(r,label){const s=r.s;switch(label){case'재물·돈 흐름':return s.wealth*2+s.output*1.2+s.authority*.5+s.pressure*.35;case'사업·창업':case'부업·투잡':return s.output*1.8+s.wealth*1.5+s.peer*.6+s.move*.5;case'이직·퇴사':return s.authority*1.5+s.output*.8+s.move*1.5+s.pressure;case'직장·승진':return s.authority*2+s.resource+s.move*.6;case'투자·계약':return s.wealth*1.7+s.authority*.8+s.resource*.5+s.pressure*.4;case'새 연애':case'재회':case'결혼 시기':case'인간관계':return s.relation*2+s.wealth*(label==='새 연애'?.6:0)+s.authority*(label==='결혼 시기'?.7:0)+s.pressure*.4;case'이사·부동산':return s.move*2+s.wealth+s.resource*.5;case'가족 문제':case'자녀·가족계획':return s.relation*1.4+s.resource+s.pressure*.5;case'시험·자격':return s.resource*2+s.authority*1.3+s.output*.5;default:return Math.max(s.wealth,s.output,s.authority,s.resource,s.peer)+s.move+s.relation*.5}}
function monthRows(natal,v,label){const now=new Date(),rows=[];for(let i=0;i<12;i++){const d=new Date(now.getFullYear(),now.getMonth()+i,15),y=d.getFullYear(),m=d.getMonth()+1;const mp=LIB.calculateFourPillars({year:y,month:m,day:15,hour:12,minute:0,gender:v.gender}).month;const g1=group(LIB.getTenGod(natal.day.heavenlyStem,mp.heavenlyStem)),g2=group(LIB.getBranchTenGod(natal.day.heavenlyStem,mp.earthlyBranch));let push=0,pressure=0;for(const g of [g1,g2]){if(label==='재물·돈 흐름'&&g==='wealth')push+=2;if(label==='재물·돈 흐름'&&g==='output')push+=1.3;if(['사업·창업','부업·투잡'].includes(label)&&g==='output')push+=1.7;if(['이직·퇴사','직장·승진'].includes(label)&&g==='authority')push+=1.8;if(['시험·자격'].includes(label)&&g==='resource')push+=1.8;if(['새 연애','재회','결혼 시기','인간관계'].includes(label)&&['wealth','authority'].includes(g))push+=.8;if(g==='peer')pressure+=.6}
 for(const br of [natal.month.earthlyBranch,natal.day.earthlyBranch]){if(pair(br,mp.earthlyBranch,CLASH)){pressure+=1.5;if(['이직·퇴사','이사·부동산'].includes(label))push+=1}if(pair(br,mp.earthlyBranch,COMB))push+=.7}
 rows.push({y,m,push,pressure,net:push-pressure*.45})}return rows}
function dominant(r){return Object.entries(r.s).filter(([k])=>['wealth','output','authority','resource','peer'].includes(k)).sort((a,b)=>b[1]-a[1])[0]?.[0]||'other'}
function yearText(r,label){const d=dominant(r);if(label==='재물·돈 흐름'){if(d==='wealth')return'돈·거래 자체가 크게 움직이는 해입니다. 수입과 지출 모두 규모가 커질 수 있어 “얼마를 버느냐”보다 실제로 얼마가 남는지 봐야 합니다.';if(d==='output')return'내가 만든 결과가 돈으로 이어지는 힘이 커집니다. 부업·성과형 수입·새 채널처럼 기존 월급이나 매출 외의 통로를 만들기 좋습니다.';if(d==='authority')return'직장·책임·계약 조건이 돈과 연결됩니다. 승진·보상·계약 변경처럼 “내 역할의 가격”이 달라지는 쪽을 먼저 봅니다.';if(d==='resource')return'벌리기보다 돈의 기반을 정리하는 해입니다. 고정비·저축·부채·준비자금을 다시 잡는 것이 다음 해의 차이를 만듭니다.';if(d==='peer')return'사람과 돈이 같이 움직입니다. 공동지출·동업·가족 지원·경쟁 때문에 내 몫이 흐려지지 않게 기준을 세우는 게 중요합니다.'}
 return GROUP_TXT[d]+'. '+(r.s.pressure>2?'변화 폭이 큰 대신 서두르면 피로도 커질 수 있습니다.':'급하게 뒤집기보다 이 해의 성격에 맞춰 한 단계씩 움직이는 편이 좋습니다.')}
function moneyRoute(best){const d=dominant(best);return d==='output'?['내가 만든 결과에서 돈이 붙습니다.','부업·성과형 보상·콘텐츠·새 프로젝트처럼 “내가 직접 만든 결과”를 돈으로 바꾸는 통로가 가장 먼저 보입니다.']:d==='wealth'?['돈 그 자체가 움직이는 시기입니다.','거래·계약·매출·정산처럼 현금이 직접 오가는 일이 커질 수 있습니다. 들어오는 금액과 함께 빠져나가는 금액도 같이 확인해야 합니다.']:d==='authority'?['내 역할의 값이 달라지는 쪽입니다.','승진·보상·계약 조건·책임 범위처럼 일의 조건이 바뀌면서 돈이 따라오는 형태가 더 가깝습니다.']:d==='resource'?['돈을 모으는 힘보다 기반을 만드는 쪽이 먼저입니다.','저축·부채정리·고정비 조정·준비자금처럼 나중에 움직일 수 있는 현금을 만드는 것이 중요합니다.']:['사람과 돈을 분리해서 봐야 합니다.','공동지출·협업·가족·파트너와 얽힌 돈에서 내 몫과 책임을 분명히 하는 것이 재물운을 지키는 핵심입니다.']}
function render(label){if(!LIB||!label)return;const v=input();if(!v.year)return;let natal;try{natal=LIB.calculateFourPillars({...v,trueSolarTime:{longitude:LONG[v.city]||126.978,applyEquationOfTime:true,applyHistoricalDst:true},dayBoundary:'midnight'})}catch(e){console.error(e);return}
 const now=new Date().getFullYear(),years=[];for(let y=now;y<=now+4;y++){const r=annual(natal,v,y);r.score=topicScore(r,label);years.push(r)}years.sort((a,b)=>b.score-a.score);const best=years[0],guide=TOPIC[label]||TOPIC['올해 전체운'];const months=monthRows(natal,v,label),bestM=[...months].sort((a,b)=>b.net-a.net).slice(0,3),careM=[...months].sort((a,b)=>b.pressure-a.pressure).slice(0,2);const chrono=[...years].sort((a,b)=>a.year-b.year);const route=label==='재물·돈 흐름'?moneyRoute(best):[`${best.year}년이 이 문제에서 가장 눈에 들어옵니다.`,yearText(best,label)];
 $('#paidTitle').textContent=`${label} 전체 풀이`;
 $('#paidMount').innerHTML=`<section class="hwPaper hwLead"><div class="hwEy">01 · 먼저 결론</div><h2>${route[0]}</h2><p class="hwAnswer">${route[1]}</p><p style="margin-top:14px">${guide.core}</p></section>
 <section class="hwPaper"><div class="hwEy">02 · 지금 이 문제를 보는 기준</div><h2>${GROUP_TXT[dominant(annual(natal,v,now))]}</h2><p>${yearText(annual(natal,v,now),label)}</p><div class="hwTiming">지금은 <b>${guide.good}</b> 쪽을 우선하고, <b>${guide.bad}</b> 선택은 한 번 더 확인하는 편이 좋습니다.</div></section>
 <section class="hwPaper"><div class="hwEy">03 · 앞으로 5년</div><h2>${best.year}년을 중심으로 앞뒤 순서를 보세요.</h2><div class="hwFive">${chrono.map(r=>`<div class="hwYear"><b>${r.year}</b><span><strong>${dominant(r)==='wealth'?'돈·거래':dominant(r)==='output'?'성과·확장':dominant(r)==='authority'?'책임·평가':dominant(r)==='resource'?'준비·정리':'사람·경쟁'}</strong><br>${yearText(r,label)}</span></div>`).join('')}</div></section>
 <section class="hwPaper"><div class="hwEy">04 · 앞으로 12개월</div><h2>같은 해 안에서도 밀 때와 확인할 때가 다릅니다.</h2><div class="hwTiming"><b>움직임이 살아나는 달</b><br>${bestM.map(x=>`${x.y}년 ${x.m}월`).join(' · ')}</div><div class="hwTiming" style="margin-top:10px"><b>조건을 한 번 더 확인할 달</b><br>${careM.map(x=>`${x.y}년 ${x.m}월`).join(' · ')}</div><div class="hwFive" style="margin-top:16px">${months.map(x=>`<div class="hwYear"><b>${String(x.m).padStart(2,'0')}월</b><span>${x.net>=1.8?'밀어볼 수 있는 달입니다. 중요한 제안·실행·협상을 앞쪽에 두기 좋습니다.':x.pressure>=1.5?'속도보다 조건 확인이 먼저입니다. 돈·계약·사람 문제를 급하게 확정하지 않는 편이 좋습니다.':'크게 벌리기보다 준비와 정리를 이어가기 좋은 달입니다.'}</span></div>`).join('')}</div></section>
 ${label==='재물·돈 흐름'?`<section class="hwPaper"><div class="hwEy">05 · 돈이 들어오는 방식</div><h2>${route[0]}</h2><p>${route[1]}</p><p style="margin-top:14px">재물운에서 가장 중요한 건 “수입 증가”와 “자산 증가”를 같은 것으로 보지 않는 것입니다. 수입이 늘어도 고정비·대출·투입금이 같이 커지면 체감은 없을 수 있습니다.</p></section><section class="hwPaper"><div class="hwEy">06 · 돈이 빠질 수 있는 구간</div><h2>큰돈은 들어올 때보다 나갈 이유가 생겼을 때 더 빨리 움직입니다.</h2><p>${careM.map(x=>`${x.y}년 ${x.m}월`).join('·')} 전후에는 계약, 투자, 가족·주거, 사업비처럼 목돈이 한 번에 묶이는 선택을 특히 꼼꼼히 보세요. “쓸 수 있는 돈”과 “잃어도 되는 돈”을 같은 통장처럼 다루지 않는 게 중요합니다.</p></section>`:''}
 <section class="hwPaper"><div class="hwEy">${label==='재물·돈 흐름'?'07':'05'} · 실제 선택 기준</div><h2>사주보다 현실 조건을 마지막에 한 번 더 대조하세요.</h2><p><b>밀어도 되는 쪽:</b> ${guide.good}</p><p style="margin-top:10px"><b>멈춰볼 쪽:</b> ${guide.bad}</p><p style="margin-top:14px">현월당의 시기는 결정을 대신하는 답이 아니라, 무엇을 먼저 확인해야 하는지 순서를 좁혀주는 참고입니다. 돈·계약·부동산처럼 손실이 큰 결정은 현금흐름과 실제 계약조건을 함께 확인하세요.</p></section>`;
 $('#paidMount').dataset.fullPaid=label;lastRendered=label;}
function selected(){const t=$('#checkoutTitle')?.textContent?.trim()||'';return t.replace(/\s*심층 풀이\s*$/,'')}
function install(){const s=document.createElement('style');s.textContent=`#paidMount .hwAnswer{font-size:18px!important;line-height:1.9!important;color:#251911!important}#paidMount .hwPaper{margin-bottom:14px}#paidMount .hwTiming b{color:#3d261d}`;document.head.appendChild(s);const ob=new MutationObserver(()=>{const paid=$('#paid');if(!paid||paid.classList.contains('hide'))return;const label=selected();if(label&&($('#paidMount')?.dataset.fullPaid!==label))setTimeout(()=>render(label),30)});ob.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});$('#pay')?.addEventListener('click',()=>setTimeout(()=>render(selected()),60));}
(async()=>{try{LIB=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm');install()}catch(e){console.error(e)}})();