const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let lib16=null,lastKey='';

const STEM_META={
갑:{n:'갑목',m:'큰 나무',a:'한번 방향을 잡으면 쉽게 꺾이지 않고, 시간이 걸려도 자기 방식으로 키워가는 힘이 강합니다.',b:'대신 내 기준이 분명한 만큼 바뀐 환경에 맞춰 방향을 틀 때까지 시간이 필요한 편입니다.'},
을:{n:'을목',m:'덩굴과 풀',a:'사람과 환경을 읽고 빈틈을 찾아 들어가는 감각이 좋습니다. 정면 돌파보다 연결하고 조율하면서 결과를 만드는 힘이 있습니다.',b:'주변 상황을 많이 읽기 때문에 결정을 오래 끌거나 마음속 피로가 쌓이기 쉽습니다.'},
병:{n:'병화',m:'큰 불과 햇빛',a:'움직일 때는 빠르고, 내가 가진 것을 밖으로 보여주면서 판을 만드는 힘이 강합니다.',b:'확신이 생긴 뒤에는 속도가 빠른 대신, 마음이 식었을 때는 한 번에 방향을 바꾸는 면도 있습니다.'},
정:{n:'정화',m:'촛불과 등불',a:'겉으로 크게 드러내기보다 필요한 곳을 정확히 비추는 힘이 있습니다. 사람과 분위기의 미묘한 차이를 잘 읽는 편입니다.',b:'섬세한 만큼 마음에 걸리는 일이 생기면 오래 생각하고 혼자 정리하는 시간이 필요합니다.'},
무:{n:'무토',m:'큰 땅과 산',a:'쉽게 흔들리기보다 버티고 쌓는 힘이 강합니다. 한 번 맡은 일은 끝까지 책임지려는 면이 있습니다.',b:'참는 힘이 강한 대신 이미 한계가 왔는데도 오래 버티다가 한 번에 정리하는 모습이 나올 수 있습니다.'},
기:{n:'기토',m:'밭과 흙',a:'현실적인 감각이 좋고, 사람과 일을 실제로 굴러가게 만드는 힘이 있습니다.',b:'챙겨야 할 것이 많아질수록 내 몫을 뒤로 미루기 쉬워서, 어느 순간 피로가 몰리는 편입니다.'},
경:{n:'경금',m:'단단한 쇠',a:'기준이 분명하고 불필요한 것을 잘라내는 힘이 있습니다. 결정해야 할 때는 생각보다 과감합니다.',b:'내 기준이 강해질수록 타협이 답답하게 느껴질 수 있어 사람과의 힘겨루기를 조심할 필요가 있습니다.'},
신:{n:'신금',m:'세공된 금속',a:'정확함과 완성도를 중시하고, 작은 차이를 놓치지 않는 편입니다. 제대로 만들고 인정받는 데 강점이 있습니다.',b:'기준이 높아 스스로 만족하기 어렵고, 잘하고 있어도 부족한 점부터 보는 경향이 생기기 쉽습니다.'},
임:{n:'임수',m:'큰 물',a:'한곳에 갇히기보다 흐름을 읽고 새로운 길을 찾는 힘이 있습니다. 경험이 쌓일수록 선택지가 넓어지는 편입니다.',b:'가능성이 많이 보이는 만큼 한 길에 오래 머무르는 것이 답답하게 느껴질 때가 있습니다.'},
계:{n:'계수',m:'비와 이슬',a:'겉보다 속을 잘 보고, 필요한 정보를 모아 판단하는 힘이 있습니다. 조용히 준비하다가 때가 오면 움직이는 편입니다.',b:'생각이 깊어질수록 걱정까지 함께 커질 수 있어 결정할 때 기준을 단순하게 잡는 것이 중요합니다.'}
};
const SEASON={인:'봄의 시작',묘:'봄의 한가운데',진:'봄의 끝',사:'여름의 시작',오:'여름의 한가운데',미:'여름의 끝',신:'가을의 시작',유:'가을의 한가운데',술:'가을의 끝',해:'겨울의 시작',자:'겨울의 한가운데',축:'겨울의 끝'};
const GOD_GROUP={정관:'authority',편관:'authority',정재:'wealth',편재:'wealth',식신:'output',상관:'output',정인:'resource',편인:'resource',비견:'peer',겁재:'peer'};
const GROUP_COPY={
authority:{t:'책임과 평가가 앞에 서는 흐름',b:'지금은 하고 싶은 것만 보기보다 내가 맡아야 할 일, 밖에서 나를 평가하는 기준, 공식적인 자리와 책임이 중요해지는 때입니다.'},
wealth:{t:'돈과 현실 조건이 앞에 서는 흐름',b:'좋고 싫음보다 실제로 얼마가 들어오고 나가는지, 어떤 조건을 감당할 수 있는지가 선택의 기준이 되기 쉬운 때입니다.'},
output:{t:'내가 만든 결과를 밖으로 꺼내는 흐름',b:'준비만 하던 것보다 실제로 만들고 보여주고 시작하는 힘이 커집니다. 일의 방식이나 수입원을 바꾸고 싶은 마음도 함께 올라올 수 있습니다.'},
resource:{t:'정리하고 준비하는 흐름',b:'무작정 벌리기보다 필요한 지식과 문서, 사람의 도움, 앞으로 쓸 기반을 먼저 챙길수록 유리한 때입니다.'},
peer:{t:'내 선택과 사람 문제가 함께 움직이는 흐름',b:'내 방식대로 가고 싶은 마음이 커지고, 동시에 주변 사람과 역할·돈·거리 문제를 다시 정해야 하는 일이 생기기 쉽습니다.'}
};

const TOPIC_DETAIL={
'사업·창업':{lead:'사업운은 “할 수 있느냐”보다 어떤 방식으로 시작해야 오래 버티는지를 먼저 봅니다.',a:'초반에는 규모보다 반복해서 팔 수 있는 구조가 중요합니다. 한 번 크게 터지는 것보다 같은 방식으로 다시 매출을 만들 수 있는지가 훨씬 중요합니다.',b:'직장을 함께 가져가고 있다면 바로 끊기보다, 먼저 작은 수입이 반복되는지 확인한 뒤 판을 키우는 편이 안정적입니다.',q:['내 이름으로 돈이 붙는 시기','사업을 키워도 되는 시기','비용과 사람을 줄여야 하는 시기']},
'부업·투잡':{lead:'부업운은 여러 개를 건드리는 것보다 하나가 실제 돈으로 이어지는 시점을 보는 게 핵심입니다.',a:'처음에는 금액이 작아도 괜찮습니다. 중요한 건 같은 행동을 반복했을 때 두 번째, 세 번째 수입이 생기는지입니다.',b:'본업이 흔들릴수록 부업을 급하게 키우고 싶어질 수 있지만, 본업을 버리기 전에 부업의 반복성을 확인하는 편이 좋습니다.',q:['첫 수입이 붙기 쉬운 시기','본업보다 커질 수 있는 구간','접어야 할 부업과 남길 부업']},
'이직·퇴사':{lead:'이직운은 “나가도 되나”보다 왜 나가려는지를 먼저 갈라야 정확해집니다.',a:'사람 때문에 힘든지, 보상 때문에 힘든지, 일 자체가 끝난 건지에 따라 같은 이직이라도 결과가 달라집니다.',b:'감정이 가장 큰 순간에 움직이면 새 직장에서도 같은 문제가 반복될 수 있습니다. 내 기준이 분명해지는 때가 실제 이동보다 먼저 옵니다.',q:['퇴사 결정을 해도 되는 시기','옮긴 뒤 자리잡기 좋은 시기','지금 회사에서 마지막으로 확인할 것']},
'직장·승진':{lead:'직장운은 단순히 승진 여부보다 내 역할과 책임이 어느 방향으로 커지는지를 봅니다.',a:'직책이 먼저 오기도 하고, 일만 먼저 늘어난 뒤 나중에 보상이 따라오기도 합니다. 둘을 구분해서 봐야 합니다.',b:'평가가 강한 시기에는 잘하는 것보다 무엇을 내 성과로 남길지가 중요합니다.',q:['평가가 좋아지는 시기','역할이 커지는 시기','자리 이동과 승진 중 어느 쪽이 먼저인지']},
'재물·돈 흐름':{lead:'재물운은 큰돈 한 번보다 돈이 들어오고 남는 구조가 어떻게 바뀌는지를 봅니다.',a:'수입이 늘어도 같은 시기에 지출과 투입이 커지면 체감은 없을 수 있습니다. 그래서 들어오는 돈과 빠져나가는 돈을 따로 봐야 합니다.',b:'새 수입원, 목돈 이동, 계약, 큰 지출은 각각 다른 시기에 움직일 수 있습니다.',q:['돈이 붙는 시기','목돈이 빠질 수 있는 시기','새 수입원이 열리기 쉬운 때']},
'투자·계약':{lead:'투자와 계약은 “좋은 운”보다 돈이 묶이는 방식과 빠져나올 수 있는 조건을 먼저 봅니다.',a:'사주에서 돈의 움직임이 커지는 것과 실제 투자수익이 나는 것은 같은 말이 아닙니다. 큰돈이 움직이는 시기일수록 현실 조건을 더 꼼꼼히 봐야 합니다.',b:'계약에서는 금액보다 기간·해지·회수 조건을 먼저 확인하는 편이 맞습니다.',q:['큰돈을 움직이기 전 확인할 시기','계약을 서두르지 말아야 할 구간','현금 비중을 높여둘 때']},
'새 연애':{lead:'새 연애는 만남의 수보다 한 사람이 실제 생활 안으로 들어오는지를 봅니다.',a:'연락이 시작되는 시기와 관계가 자리잡는 시기는 다를 수 있습니다.',b:'빠르게 가까워지는 인연일수록 생활 방식과 약속을 맞추는 과정이 중요합니다.',q:['새 사람이 들어오기 쉬운 시기','관계가 깊어지는 구간','초반에 거를 신호']},
'재회':{lead:'재회운은 연락이 다시 닿는 것과 실제로 다시 만나는 것을 따로 봅니다.',a:'다시 연락이 와도 예전에 갈라졌던 이유가 그대로면 관계는 오래가기 어렵습니다.',b:'재회 가능성을 볼 때는 상대의 움직임보다 두 사람 관계의 조건이 바뀌는 시점을 함께 봐야 합니다.',q:['연락이 다시 열릴 수 있는 시기','재회를 결정해도 되는 시기','같은 문제를 반복할 가능성']},
'결혼 시기':{lead:'결혼운은 감정이 가장 좋은 때보다 현실 조건이 같이 맞는 때가 더 중요합니다.',a:'집·돈·일정·가족 문제 중 하나가 계속 막히면 결혼 이야기가 나와도 실제 진행은 늦어질 수 있습니다.',b:'관계 확정과 실제 혼인·주거 변화가 같은 해에 오지 않을 수도 있습니다.',q:['결혼 이야기가 구체화되는 시기','집과 돈이 맞춰지는 때','서두르지 않는 편이 좋은 구간']},
'자녀·가족계획':{lead:'자녀운은 임신을 단정하는 것이 아니라 가족계획이 실제 생활 조건과 맞물리는 흐름을 봅니다.',a:'일·주거·돌봄·경제 조건이 맞춰지는 시기를 함께 봐야 합니다.',b:'건강과 임신 가능성은 반드시 의료적 확인이 우선입니다.',q:['가족계획이 구체화되는 때','생활 조건이 맞춰지는 구간','일과 돌봄이 부딪히기 쉬운 시기']},
'인간관계':{lead:'인간관계운은 사람을 많이 만나는 것보다 누구와 계속 갈지를 가르는 과정에 가깝습니다.',a:'같이 일하는 사람, 오래된 친구, 가까운 지인 사이에서 역할과 거리가 다시 정리될 수 있습니다.',b:'이때 억지로 모든 관계를 유지하려 하면 오히려 피로가 커질 수 있습니다.',q:['새 인맥이 열리는 시기','정리되는 관계가 생기기 쉬운 때','사람 때문에 돈·일이 흔들리는 구간']},
'시험·자격':{lead:'시험운은 공부를 많이 하는 시기와 실제 결과를 확인받는 시기를 나눠 봅니다.',a:'준비가 잘 되는 달과 시험·심사 결과가 나오는 달이 다를 수 있습니다.',b:'자격·승인·서류처럼 외부 기준을 통과해야 하는 일이 있다면 결과가 남는 시기를 보는 것이 중요합니다.',q:['준비 효율이 좋은 시기','시험·심사 결과를 받는 때','일정 변경을 조심할 구간']},
'이사·부동산':{lead:'이사운과 집을 사는 운은 같은 것으로 보지 않습니다.',a:'생활 때문에 주소를 옮기는 흐름과 자산 때문에 매수하는 흐름은 따로 움직일 수 있습니다.',b:'직장·관계·가족 중 무엇 때문에 이동하는지에 따라 좋은 시점도 달라집니다.',q:['실제 이동이 강해지는 시기','계약을 진행하기 좋은 구간','매수보다 임차가 나은 시기']},
'가족 문제':{lead:'가족운은 걱정이 많아지는 때보다 내가 실제로 맡고 결정해야 하는 일이 생기는 때를 봅니다.',a:'부모·형제·자녀 가운데 누구와 돈·시간·생활 문제를 함께 정리하게 되는지가 중요합니다.',b:'가족 문제는 감정만으로 해결되지 않는 경우가 많아서 현실적인 역할 분담을 함께 봐야 합니다.',q:['가족 책임이 커지는 시기','돈이 함께 움직이는 구간','합가·분가 같은 생활 변화']},
'올해 전체운':{lead:'올해는 모든 운이 한꺼번에 좋아지고 나빠지는 해가 아닙니다. 먼저 움직이는 것과 나중에 따라오는 것을 나눠 봐야 합니다.',a:'일이 먼저 움직이고 돈이 뒤따를 수도 있고, 관계가 바뀐 뒤 생활환경이 달라질 수도 있습니다.',b:'올해는 한 가지 사건보다 순서를 아는 것이 중요합니다.',q:['올해 가장 먼저 움직이는 영역','돈과 일의 순서','하반기에 크게 달라질 부분']}
};

function currentInput(){const unknown=$('#unknown')?.checked;return{year:+$('#year')?.value,month:+$('#month')?.value,day:+$('#day')?.value,hour:unknown?12:+$('#hour')?.value,minute:unknown?0:+$('#minute')?.value,unknown,gender:$('.sex.on')?.dataset.sex||'female',isLunar:$('#calendar')?.value==='lunar',isLeapMonth:$('#calendar')?.value==='lunar'&&$('#leap')?.checked,city:$('#city')?.value||'서울'} }
function gName(p){return p?.heavenlyStem&&p?.earthlyBranch?p.heavenlyStem+p.earthlyBranch:''}
function groupFromGod(g){return GOD_GROUP[g]||'resource'}
function annualTheme(natal,year){const y=lib16.calculateFourPillars({year,month:7,day:1,hour:12,minute:0,gender:'male'}).year;const a=groupFromGod(lib16.getTenGod(natal.day.heavenlyStem,y.heavenlyStem)),b=groupFromGod(lib16.getBranchTenGod(natal.day.heavenlyStem,y.earthlyBranch));if(a===b)return{year,pillar:gName(y),title:GROUP_COPY[a].t,body:GROUP_COPY[a].b};const A=GROUP_COPY[a],B=GROUP_COPY[b];return{year,pillar:gName(y),title:`${A.t.replace(' 흐름','')}과 ${B.t.replace(' 흐름','')}이 함께 오는 해`,body:`${A.b} 동시에 ${B.b} 두 흐름이 겹치기 때문에 한 가지만 밀어붙이기보다 순서를 정하는 것이 중요합니다.`}}
function activeDayun(natal,input){const age=new Date().getFullYear()-input.year;return(natal.luckPillars?.pillars||[]).find(x=>age>=x.age&&age<x.age+10)||null}
function dayunText(natal,d){if(!d)return null;const k=d.korean||d.ganji||'',stem=d.heavenlyStem||k[0],branch=d.earthlyBranch||k[1];if(!stem)return null;const g1=groupFromGod(lib16.getTenGod(natal.day.heavenlyStem,stem)),g2=branch?groupFromGod(lib16.getBranchTenGod(natal.day.heavenlyStem,branch)):g1;const A=GROUP_COPY[g1],B=GROUP_COPY[g2];return{ganji:(stem||'')+(branch||''),title:g1===g2?A.t:`${A.t.replace(' 흐름','')}과 ${B.t.replace(' 흐름','')}이 같이 깔린 10년`,body:g1===g2?A.b:`${A.b} ${B.b} 이 두 가지가 같이 움직여, 한쪽만 해결하면 다른 쪽이 다시 선택을 요구하기 쉬운 시기입니다.`}}
function buildBase(natal,input){const dm=STEM_META[natal.day.heavenlyStem]||STEM_META.갑;const season=SEASON[natal.month.earthlyBranch]||'계절이 바뀌는 때';const timeText=input.unknown?'태어난 시간을 모르는 상태라 시간 기둥은 세부 해석에서 제외했습니다.':`태어난 시간까지 포함해 네 기둥을 함께 봤습니다.`;return`<section class="hwPaper hwLead"><div class="hwEy">사주의 기본 결</div><h2>${dm.n} · ${dm.m}의 기운을 타고났습니다.</h2><p>${dm.a}</p><p style="margin-top:12px">${dm.b}</p><div class="hwTiming">${season}에 태어나 이 기운이 어떤 방식으로 쓰이는지를 월의 흐름과 함께 봅니다. ${timeText}</div><details class="hwWhy"><summary>내 명식 보기</summary><p>년주 ${gName(natal.year)} · 월주 ${gName(natal.month)} · 일주 ${gName(natal.day)}${input.unknown?'':` · 시주 ${gName(natal.hour)}`}</p></details></section>`}
function mergePastCards(){const cards=$$('#readingMount .hwPaper').filter(c=>/년 · 지나온 흐름/.test(c.querySelector('.hwEy')?.textContent||''));const years={};for(const c of cards){const year=(c.querySelector('.hwEy')?.textContent.match(/\d{4}/)||[])[0];if(!year)continue;(years[year]??=[]).push({title:c.querySelector('h2')?.textContent||'',body:c.querySelector('p')?.textContent||'',timing:c.querySelector('.hwTiming')?.textContent||'',why:c.querySelector('.hwWhy p')?.textContent||''})}return years}
function buildPast(years){const keys=Object.keys(years).sort();if(!keys.length)return`<section class="hwPaper"><div class="hwEy">지나온 흐름</div><h2>최근 몇 년은 한 번에 뒤집히기보다, 서서히 방향을 바꿔온 쪽에 가깝습니다.</h2><p>큰 사건 하나보다 일·돈·관계 가운데 하나를 오래 끌고 오면서 기준이 달라졌을 가능성을 먼저 봅니다. 지금의 고민도 갑자기 생겼다기보다 그 흐름 위에 올라와 있는 것으로 읽는 편이 맞습니다.</p></section>`;return keys.map(year=>{const arr=years[year];const title=arr.length>1?`${year}년, 한 가지가 아니라 일과 현실 조건이 함께 움직인 해입니다.`:arr[0].title;const paras=arr.map(x=>x.body).filter(Boolean).join(' ');const timings=[...new Set(arr.map(x=>x.timing).filter(Boolean))].join(' ');return`<section class="hwPaper"><div class="hwEy">${year}년 · 지나온 변곡</div><h2>${title}</h2><p>${paras}</p>${timings?`<div class="hwTiming">${timings}</div>`:''}<p style="margin-top:14px">이 해를 떠올릴 때는 결과 하나보다, 그 전과 후에 내 기준이 어떻게 달라졌는지를 같이 보세요. 같은 자리에 있어도 책임·보상·사람을 대하는 방식이 달라졌다면 이 흐름과 더 가깝습니다.</p></section>`}).join('')}
function buildNow(natal,input){const now=new Date().getFullYear(),a=annualTheme(natal,now),d=dayunText(natal,activeDayun(natal,input));return`<section class="hwPaper"><div class="hwEy">지금의 중심 · ${now}</div><h2>${a.title}</h2><p>${a.body}</p>${d?`<div class="hwTiming"><b>지금 10년의 바탕</b><br>${d.title}. ${d.body}</div>`:''}<p style="margin-top:14px">그래서 지금은 눈앞의 사건 하나만 보기보다, 내가 앞으로 어떤 방식으로 일하고 돈을 벌고 사람을 남길지를 같이 정해야 하는 구간으로 보는 편이 맞습니다.</p></section>`}
function buildThree(natal){const now=new Date().getFullYear();const rows=[1,2,3].map(i=>annualTheme(natal,now+i));return`<section class="hwPaper"><div class="hwEy">앞으로 3년의 흐름</div><h2>앞으로는 해마다 역할이 다르게 바뀝니다.</h2><p>좋은 해·나쁜 해로 자르기보다, 각 해에 무엇을 먼저 해야 하는지를 보는 것이 더 중요합니다.</p><div class="hwFive">${rows.map(r=>`<div class="hwYear"><b>${r.year}</b><span><strong>${r.title}</strong><br>${r.body}</span></div>`).join('')}</div><div class="hwTiming">정확한 월과 선택 시점은 아래에서 보고 싶은 주제를 고르면 그 문제 안에서 다시 좁혀 봅니다.</div></section>`}
function rebuildReading(){if(!lib16)return;const mount=$('#readingMount');if(!mount||mount.dataset.v16==='1'||!mount.children.length)return;const input=currentInput();if(!input.year)return;let natal;try{natal=lib16.calculateFourPillars({...input,trueSolarTime:undefined,dayBoundary:'midnight'})}catch{return}const years=mergePastCards();mount.innerHTML=buildBase(natal,input)+buildPast(years)+buildNow(natal,input)+buildThree(natal);mount.dataset.v16='1';const hero=$('#result .resultHero h1');if(hero)hero.innerHTML='태어난 사주와 지나온 흐름을<br>차례로 풀어보겠습니다.';const rp=$('#replayNote');if(rp)rp.textContent='먼저 타고난 결을 보고, 지나온 변곡과 지금의 흐름을 이어서 봅니다.'}
function showCheckout(label){['landing','loading','result','paid'].forEach(id=>$('#'+id)?.classList.add('hide'));$('#checkout')?.classList.remove('hide');$('#checkoutTitle').textContent=`${label} 심층 풀이`;$('#orderLabel').textContent=`${label} · 시기 · 선택 기준 · 5년 흐름`;scrollTo(0,0)}
function enrichTopic(){const box=$('#topicPreview');if(!box||box.dataset.v16==='1'||!box.innerHTML.trim())return;const label=$('.hwTopic.on')?.textContent?.trim();if(!label||label==='궁합')return;const guide=TOPIC_DETAIL[label];if(!guide)return;const existingH=box.querySelector('h3')?.textContent||'';const existingP=box.querySelector('p')?.textContent||'';const year=(existingH.match(/\d{4}/)||[])[0];const originalBlur=box.querySelector('.hwBlur');const locked=originalBlur?originalBlur.outerHTML:`<div class="hwBlur"><div class="hwBlurContent"><div class="hwLockedRow"><b>가장 중요한 연도와 월</b><p>이 문제에서 실제 움직임이 커지는 시기를 연도와 월로 좁혀 봅니다.</p></div><div class="hwLockedRow"><b>움직일 때와 멈춰볼 때</b><p>같은 해 안에서도 밀어도 되는 구간과 다시 확인할 구간을 나눕니다.</p></div><div class="hwLockedRow"><b>앞으로 5년의 순서</b><p>한 번의 선택이 다음 흐름에 어떻게 이어지는지 봅니다.</p></div></div><div class="hwPaywall"><span>현월당 심층 풀이</span><h3>시기와 선택 기준까지 이어서 봅니다.</h3><strong>29,000원</strong><button class="v16Unlock">이 풀이 끝까지 보기 →</button></div></div>`;box.innerHTML=`<div class="hwPreview"><div class="hwEy">${label} · 첫 해석</div><h3>${guide.lead}</h3><p>${guide.a}</p><p style="margin-top:12px">${guide.b}</p>${year?`<div class="hwTiming">현재 흐름에서 특히 ${year}년 전후가 눈에 들어옵니다. 이 시기의 앞뒤를 함께 봐야 실제 선택 시점이 더 선명해집니다.</div>`:''}<div class="hwOpen" style="margin-top:16px"><b>이 문제에서 이어서 볼 세 가지</b><br>① ${guide.q[0]}<br>② ${guide.q[1]}<br>③ ${guide.q[2]}</div>${locked}</div>`;box.dataset.v16='1';const btn=box.querySelector('.v16Unlock');if(btn)btn.onclick=()=>showCheckout(label);const old=box.querySelector('#unlock');if(old){old.textContent='이 풀이 끝까지 보기 →'}}
function installStyle(){const s=document.createElement('style');s.textContent=`#readingMount .hwPaper p+p{margin-top:10px}.hwOpen{padding:14px 15px;background:rgba(126,45,36,.06);border-left:3px solid #7e2d24;font-size:13px;line-height:1.9;color:#574a40}.hwOpen b{display:block;margin-bottom:4px;color:#30231d}.hwFive{margin-top:14px}`;document.head.appendChild(s)}
async function init16(){installStyle();try{lib16=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm')}catch(e){console.error(e);return}const ob=new MutationObserver(()=>{queueMicrotask(()=>{rebuildReading();enrichTopic()})});ob.observe(document.body,{childList:true,subtree:true});rebuildReading();enrichTopic()}
init16();