const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let LIB17=null;
const LONG={서울:126.9780,부산:129.0756,대구:128.6014,인천:126.7052,광주:126.8526,대전:127.3845,울산:129.3114,세종:127.2890,경기:127.0286,강원:127.7298,충북:127.4914,충남:126.6728,전북:127.1088,전남:126.4629,경북:128.5056,경남:128.6811,제주:126.5312};
const CLASH=['자오','축미','인신','묘유','진술','사해'],COMB=['자축','인해','묘술','진유','사신','오미'],HARM=['자미','축오','인사','묘진','신해','유술'];
const pair=(a,b,list)=>list.includes(a+b)||list.includes(b+a);
const GOD_GROUP={정재:'wealth',편재:'wealth',식신:'output',상관:'output',정관:'authority',편관:'authority',정인:'resource',편인:'resource',비견:'peer',겁재:'peer'};
const GROUP_NAME={wealth:'돈·현실',output:'결과·표현',authority:'책임·평가',resource:'준비·기반',peer:'사람·경쟁'};
const DAY_META={갑:['큰 나무','한번 방향을 잡으면 쉽게 꺾이지 않는 힘이 있지만, 방향을 바꿀 때는 충분히 납득할 이유가 필요한 편입니다.'],을:['풀과 덩굴','주변 흐름을 빠르게 읽고 연결하는 감각이 좋지만, 선택지가 많아질수록 결정을 오래 끌 수 있습니다.'],병:['큰 불과 햇빛','움직일 때는 빠르고 밖으로 드러나는 성과를 만드는 힘이 있지만, 확신이 꺾이면 방향을 크게 틀 수 있습니다.'],정:['촛불과 등불','작은 차이를 잘 읽고 필요한 곳에 집중하는 힘이 있지만, 마음에 걸린 일을 오래 품는 편입니다.'],무:['큰 땅과 산','버티고 쌓는 힘이 강하지만, 이미 한계가 왔는데도 오래 참고 있다가 한 번에 정리할 수 있습니다.'],기:['밭과 흙','현실적으로 일을 굴리고 챙기는 힘이 좋지만, 남의 몫까지 떠안으면 내 자원이 먼저 마를 수 있습니다.'],경:['단단한 쇠','기준이 분명하고 정리할 때 과감하지만, 내 기준이 너무 강해지면 타협이 답답해질 수 있습니다.'],신:['세공된 금속','완성도와 정확성을 높이는 힘이 좋지만, 충분히 잘하고 있어도 부족한 점부터 볼 수 있습니다.'],임:['큰 물','흐름을 읽고 새 길을 찾는 힘이 좋지만, 가능성이 너무 많이 보이면 한 길을 오래 끌고 가기 답답해질 수 있습니다.'],계:['비와 이슬','정보를 모아 조용히 준비하는 힘이 좋지만, 생각이 깊어질수록 걱정도 함께 커질 수 있습니다.']};

const PACK={
'재물·돈 흐름':{family:'money',desire:'돈을 더 많이 버는 것보다, 실제로 남는 돈이 언제부터 달라지는지 알고 싶을 때 보는 풀이입니다.',core:'지금의 재물 문제는 수입 하나가 아니라 수입원·고정비·목돈·계약이 어떤 순서로 움직이는지가 핵심입니다.',strength:'성과를 돈으로 바꾸는 통로를 하나 더 만드는 힘',weak:'들어오는 돈이 늘면 나가는 돈과 투입금까지 같이 키우는 것',mistake:'매출·연봉·입금액을 곧바로 “내 돈이 늘었다”로 받아들이는 것',gain:'새 수입원, 반복 수입, 보상·정산, 계약에서 들어오는 돈을 따로 봅니다.',risk:'큰 지출, 대출, 투자금, 가족·주거에 묶이는 돈을 따로 봅니다.',people:'돈은 혼자 움직이지 않습니다. 상사·고객·파트너·가족 가운데 누구와 돈의 조건을 맞추는지가 결과를 바꿀 수 있습니다.',docs:'계약·정산·대출·보상은 말보다 숫자와 조건이 남습니다. 금액보다 지급일·기간·해지·회수 조건을 먼저 확인하는 편이 좋습니다.',scenarios:[['A. 현재 수입원 유지','지금 버는 방식을 유지하면서 새 통로를 작게 붙이는 선택. 안정성은 높지만 변화 속도는 느립니다.'],['B. 새 수입원 확대','부업·성과형 보상·새 고객처럼 두 번째 돈줄의 비중을 키우는 선택. 반복성이 확인될 때 힘이 붙습니다.'],['C. 큰돈을 먼저 움직임','투자·대출·자산 매입처럼 목돈부터 움직이는 선택. 기회보다 회수 조건을 먼저 봐야 합니다.']],actions:['최근 3개월 고정비와 변동비를 분리해 실제 남는 돈을 계산하기','지금 수입 외에 반복 가능한 두 번째 수입 후보를 하나만 고르기','대출·투자·계약은 “최악의 경우 얼마까지 잃을 수 있는가”를 먼저 적기'],follow:['내 사주에서 돈이 붙는 방식은 월급형·사업형·투자형 중 어디에 가까운가?','향후 12개월 중 목돈을 가장 조심해야 할 달은 언제인가?','부업이나 사업으로 수입원을 늘린다면 어느 시점부터 비중을 키워도 되는가?']},
'사업·창업':{family:'business',desire:'사업을 시작해도 되는지보다, 어떤 구조로 시작해야 오래 버티는지 알고 싶을 때 보는 풀이입니다.',core:'사업은 시작일보다 반복해서 팔리는 구조와 현금이 남는 구조가 먼저 잡혀야 합니다.',strength:'내가 만든 결과를 밖에 내놓고 새 판을 만드는 힘',weak:'초기 반응을 장기 수요로 착각해 고정비를 너무 빨리 늘리는 것',mistake:'매출이 생기기 전에 사람·재고·사무실부터 크게 만드는 것',gain:'고객·상품·채널 가운데 무엇이 실제 반복 매출을 만드는지 봅니다.',risk:'고정비·인력·동업·광고비가 매출보다 먼저 커지는 구간을 봅니다.',people:'사업운은 사람운과 붙습니다. 고객을 데려오는 사람과 비용만 늘리는 사람을 구분하는 것이 중요합니다.',docs:'동업·용역·광고·임대차는 좋은 관계보다 역할·정산·해지 조건을 문서로 남기는 것이 우선입니다.',scenarios:[['A. 직장 유지 + 검증','본업을 유지한 채 작은 상품·서비스로 수요를 먼저 확인합니다.'],['B. 단계적 독립','반복 매출이 확인된 뒤 시간과 자원을 사업 쪽으로 옮깁니다.'],['C. 즉시 전환','퇴사·투자부터 하고 사업에 전력하는 선택. 현금 버틸 기간이 충분할 때만 검토합니다.']],actions:['팔 수 있는 것 하나를 한 문장으로 정리하기','이번 달 실제로 돈을 낼 고객 10명에게 먼저 제안하기','6개월 고정비를 계산하고 버틸 현금 기간 확인하기'],follow:['첫 반복매출이 붙기 쉬운 시기는 언제인가?','사업 확장과 비용 축소 중 어느 쪽을 먼저 해야 하는가?','동업·채용·외주 중 사람을 붙여도 되는 시기는 언제인가?']},
'부업·투잡':{family:'business',desire:'부업이 잠깐의 용돈인지, 앞으로 커질 두 번째 수입원인지 알고 싶을 때 보는 풀이입니다.',core:'부업은 종류보다 반복성이 먼저입니다. 한 번 번 돈보다 같은 행동으로 두 번째 돈이 들어오는지가 중요합니다.',strength:'기존 경험을 새 수입으로 바꾸는 힘',weak:'본업 스트레스를 피하려고 부업을 너무 많이 벌이는 것',mistake:'조회수·문의·매출 한 번을 안정적인 부수입으로 착각하는 것',gain:'작은 단가라도 반복되는 수입과 재구매·재의뢰를 봅니다.',risk:'시간 부족, 본업 성과 하락, 초기 장비·광고비 과투입을 봅니다.',people:'부업은 소개와 재구매에서 빨리 자랍니다. 내 시간을 덜 쓰면서 다시 찾아오는 사람을 만드는 것이 중요합니다.',docs:'겸업 규정·세금·정산 조건을 먼저 확인해 본업과 충돌하지 않도록 하는 편이 좋습니다.',scenarios:[['A. 취미형','시간을 정해 소액 수입만 만드는 방식.'],['B. 성장형','반복 고객과 반복 수입을 쌓아 비중을 키우는 방식.'],['C. 전환형','부업을 본업으로 바꾸는 방식. 생활비를 감당할 반복 수입 확인이 선행돼야 합니다.']],actions:['부업 후보를 하나만 남기기','4주 동안 같은 방식으로 최소 3회 판매·수익 실험하기','본업을 버리지 않아도 가능한 시간 한도를 정하기'],follow:['부업이 본업보다 커질 수 있는 시기는 언제인가?','지금 하고 있는 여러 부업 중 무엇을 남겨야 하는가?','퇴사를 고민할 만큼 부업 비중을 키워도 되는 때는 언제인가?']},
'이직·퇴사':{family:'career',desire:'지금 회사를 떠나는 게 맞는지, 떠난 뒤 더 나아질 수 있는지 알고 싶을 때 보는 풀이입니다.',core:'이직은 “갈 수 있나”보다 왜 나가려는지와 다음 자리에서 무엇이 달라져야 하는지를 먼저 봐야 합니다.',strength:'기준이 선명해졌을 때 과감하게 자리를 바꾸는 힘',weak:'감정이 가장 큰 순간에 다음 조건을 확인하지 않고 움직이는 것',mistake:'사람 문제·보상 문제·일 자체의 문제를 모두 “회사 문제” 하나로 묶는 것',gain:'새 자리에서 역할·보상·성장 중 무엇이 실제로 개선되는지 봅니다.',risk:'같은 문제를 다른 회사에서 반복하는 이동을 조심합니다.',people:'상사와 조직문화는 직무만큼 중요합니다. 사람 문제로 떠난다면 다음 회사의 의사결정 구조를 먼저 봐야 합니다.',docs:'연봉·직책·수습·성과급·근무지·퇴직 조건은 말이 아니라 오퍼레터와 계약서로 확인해야 합니다.',scenarios:[['A. 현직 유지','조건 개선 가능성을 한 번 더 확인합니다.'],['B. 이직','다음 자리의 조건이 최소 두 가지 이상 분명히 개선될 때 움직입니다.'],['C. 퇴사 후 탐색','회복과 방향 재설계가 필요할 때 선택하되 생활비 버틸 기간을 먼저 확보합니다.']],actions:['퇴사 이유를 사람·보상·일·성장 중 하나로 우선순위 정하기','다음 회사에서 반드시 달라져야 할 조건 3개 적기','현재 자리에서 마지막으로 협상할 조건 하나 정하기'],follow:['퇴사 결정을 내려도 되는 시기는 언제인가?','이직 후 자리잡기 좋은 달은 언제인가?','현 직장에서 보상 협상을 먼저 해볼 시기는 언제인가?']},
'직장·승진':{family:'career',desire:'일은 늘어나는데 보상과 직책도 따라올지, 언제 내 성과를 인정받기 쉬운지 알고 싶을 때 보는 풀이입니다.',core:'직장운은 일의 양보다 역할·평가·보상이 어떤 순서로 붙는지를 봅니다.',strength:'책임이 커질수록 내 이름으로 성과를 남기는 힘',weak:'일만 더 맡고 권한과 보상은 나중으로 미루는 구조',mistake:'열심히 한 일과 회사가 인정하는 성과를 같은 것으로 보는 것',gain:'평가·직책·보상·핵심 프로젝트가 붙는 순서를 봅니다.',risk:'책임만 커지고 조건은 그대로인 시기를 오래 끌지 않는 것이 중요합니다.',people:'승진은 성과만으로 끝나지 않고 의사결정권자가 그 성과를 어떻게 인식하는지도 중요합니다.',docs:'평가 기준·KPI·보상조건을 가능한 한 숫자와 기록으로 남겨야 합니다.',scenarios:[['A. 현 역할 강화','현재 자리에서 성과와 영향력을 쌓습니다.'],['B. 내부 이동','더 좋은 팀·역할로 옮겨 평가판을 바꿉니다.'],['C. 외부 이동','내 역할의 시장가격이 더 높은 곳으로 이동합니다.']],actions:['최근 6개월 성과를 숫자 3개로 정리하기','평가권자가 중요하게 보는 기준 확인하기','늘어난 책임과 원하는 보상을 한 문장으로 연결하기'],follow:['평가가 가장 잘 붙는 시기는 언제인가?','내부 이동과 외부 이직 중 어느 쪽이 먼저 열리는가?','보상 협상을 꺼내기 좋은 달은 언제인가?']},
'투자·계약':{family:'money',desire:'큰돈을 움직이기 전에 지금이 들어갈 때인지, 기다릴 때인지 판단하고 싶을 때 보는 풀이입니다.',core:'투자·계약은 좋은 운보다 손실 한도와 빠져나올 조건을 먼저 봐야 합니다.',strength:'조건이 맞을 때 결정을 실제 행동으로 옮기는 힘',weak:'기회가 보이면 위험 조건을 뒤로 미루는 것',mistake:'돈이 움직이는 시기를 “수익이 보장되는 시기”로 착각하는 것',gain:'현금이 들어오는 기회와 자산을 늘리는 기회를 구분합니다.',risk:'회수 지연·대출·레버리지·해지 불가 조건을 따로 봅니다.',people:'공동투자·소개·지인 추천은 관계와 돈을 분리해서 판단해야 합니다.',docs:'계약서·등기·상환·해지·위약금은 사주보다 먼저 확인할 현실 조건입니다.',scenarios:[['A. 현금 유지','기회를 기다리며 유동성을 확보합니다.'],['B. 분할 진입','한 번에 넣지 않고 확인하면서 비중을 늘립니다.'],['C. 큰 규모 진입','손실 한도와 회수 계획이 이미 있는 경우에만 검토합니다.']],actions:['최대 손실 한도를 숫자로 정하기','계약에서 빠져나올 조건 먼저 읽기','한 번에 넣을 금액과 분할할 금액 나누기'],follow:['큰돈을 움직이기 상대적으로 편한 시기는 언제인가?','회수와 현금 확보를 우선해야 하는 달은 언제인가?','계약을 서두르지 말아야 할 구간은 언제인가?']},
'새 연애':{family:'relationship',desire:'새 사람이 들어오는 시기뿐 아니라 그 관계가 실제로 오래갈 수 있는지 알고 싶을 때 보는 풀이입니다.',core:'새 연애는 만남의 수보다 한 사람이 생활 안으로 들어오는 속도와 지속성을 봅니다.',strength:'상대와 리듬이 맞을 때 관계를 자연스럽게 깊게 만드는 힘',weak:'초반의 강한 감정을 장기적인 궁합으로 착각하는 것',mistake:'연락 빈도만 보고 관계의 안정성을 판단하는 것',gain:'새 만남·관계 심화·공식화의 시기를 나눠 봅니다.',risk:'빠르게 가까워졌다가 생활 조건에서 부딪히는 패턴을 조심합니다.',people:'소개·일·취미·지인 연결처럼 사람이 들어오는 통로가 중요한 시기가 있습니다.',docs:'연애에서는 문서보다 약속이 현실이 되는지, 말과 행동이 일치하는지를 봐야 합니다.',scenarios:[['A. 천천히 확인','만남을 이어가며 생활 리듬을 확인합니다.'],['B. 적극적으로 만남 확대','새 인연을 만날 접점을 늘립니다.'],['C. 한 사람에 집중','상대의 행동이 꾸준할 때 관계를 깊게 가져갑니다.']],actions:['내가 원하는 관계 조건 3개 적기','새 만남 통로 하나 늘리기','초반 4주 동안 말보다 반복 행동 관찰하기'],follow:['새 사람이 들어오기 쉬운 시기는 언제인가?','관계가 깊어지는 달은 언제인가?','초반에 특히 조심해야 할 관계 패턴은 무엇인가?']},
'재회':{family:'relationship',desire:'연락이 다시 오는지보다, 다시 만나도 같은 이유로 헤어지지 않을지 알고 싶을 때 보는 풀이입니다.',core:'재회는 연락 재개와 관계 복원을 따로 봐야 합니다.',strength:'조건이 달라졌을 때 관계를 새 방식으로 다시 만들 수 있는 힘',weak:'그리움 때문에 예전에 갈라진 이유를 작게 보는 것',mistake:'연락이 왔다는 사실을 관계 회복의 증거로 받아들이는 것',gain:'연락·만남·관계 재정립이 각각 언제 열리는지 봅니다.',risk:'과거 갈등 조건이 그대로인데 감정만 다시 커지는 시기를 조심합니다.',people:'주변 사람의 의견보다 두 사람이 실제로 달라진 행동이 있는지가 중요합니다.',docs:'재회에서는 약속보다 바뀐 행동과 반복되는 패턴이 더 중요합니다.',scenarios:[['A. 연락만 확인','감정 결론 없이 대화부터 확인합니다.'],['B. 다시 만나보기','갈라진 이유에 대한 합의가 있을 때 제한적으로 시작합니다.'],['C. 관계 종료','조건이 그대로라면 다시 열지 않는 선택도 포함합니다.']],actions:['헤어진 원인을 한 문장으로 적기','그 원인이 지금 실제로 달라졌는지 증거 찾기','연락이 와도 바로 관계를 확정하지 않을 기준 정하기'],follow:['연락이 다시 열리기 쉬운 때는 언제인가?','재회를 결정해도 되는 시기는 언제인가?','같은 갈등이 반복되기 쉬운 달은 언제인가?']},
'결혼 시기':{family:'relationship',desire:'좋아하는 마음을 실제 결혼으로 옮기기 좋은 때와 현실 조건을 맞출 순서를 알고 싶을 때 보는 풀이입니다.',core:'결혼은 감정만이 아니라 집·돈·일정·가족 조건이 같이 움직여야 현실이 됩니다.',strength:'관계를 실제 약속과 생활로 옮기는 힘',weak:'감정이 좋다는 이유로 돈과 생활 조건을 뒤로 미루는 것',mistake:'결혼 이야기와 실제 혼인·주거 변화를 같은 시점으로 보는 것',gain:'관계 확정·상견례·주거·혼인 흐름을 나눠 봅니다.',risk:'한쪽의 일·돈 문제가 정리되지 않은 채 일정만 앞당기는 것을 조심합니다.',people:'결혼은 두 사람뿐 아니라 가족과 생활권의 영향을 함께 받습니다.',docs:'주거계약·대출·혼인 관련 행정은 감정보다 현실 일정을 먼저 맞춰야 합니다.',scenarios:[['A. 관계 확정 우선','결혼 의사를 먼저 맞추고 조건을 하나씩 정리합니다.'],['B. 주거·돈 우선','집과 재정 계획을 먼저 잡고 일정을 확정합니다.'],['C. 일정 우선','날짜를 먼저 정하고 나머지를 맞춥니다. 압박이 커질 수 있어 여유가 필요합니다.']],actions:['결혼의 가장 큰 현실 장애물 하나 고르기','주거·예산·일정 우선순위 합의하기','양가와 조율할 문제를 두 사람 사이에서 먼저 정리하기'],follow:['결혼 이야기가 구체화되기 쉬운 시기는 언제인가?','집과 돈이 같이 움직이는 시기는 언제인가?','서두르지 않는 편이 좋은 달은 언제인가?']},
'인간관계':{family:'relationship',desire:'새 사람보다 지금 곁에 있는 사람 가운데 누구를 남기고 누구와 거리를 둬야 하는지 보고 싶을 때의 풀이입니다.',core:'인간관계는 사람 수보다 에너지를 주고받는 구조를 봅니다.',strength:'필요한 사람과 관계를 오래 가져가는 힘',weak:'책임감이나 미안함 때문에 이미 끝난 관계를 오래 끄는 것',mistake:'모든 사람에게 같은 거리와 같은 에너지를 쓰는 것',gain:'도움이 되는 관계·협업·새 연결이 열리는 때를 봅니다.',risk:'돈·일·감정이 섞여 관계가 복잡해지는 구간을 봅니다.',people:'이 주제 자체가 사람의 문제라서, 반복해서 나를 지치게 하는 유형을 구분하는 것이 가장 중요합니다.',docs:'돈이나 일을 함께 한다면 친분과 계약을 분리하는 편이 좋습니다.',scenarios:[['A. 관계 유지','현재 관계를 유지하되 경계를 분명히 합니다.'],['B. 거리 조절','연락과 역할을 줄여 에너지 소모를 낮춥니다.'],['C. 관계 정리','반복 손실이 크면 끝내는 선택도 필요합니다.']],actions:['나를 살리는 사람 3명과 지치게 하는 사람 3명 적기','돈·일이 섞인 관계 하나 분리하기','거절해야 할 부탁 하나 미리 정하기'],follow:['새로운 도움이 되는 사람이 들어오기 쉬운 때는 언제인가?','관계를 정리하기 좋은 시기는 언제인가?','사람 때문에 돈이나 일이 흔들리기 쉬운 달은 언제인가?']},
'이사·부동산':{family:'home',desire:'사는 곳을 바꾸는 흐름과 집을 사는 흐름을 구분해 실제 선택 순서를 보고 싶을 때의 풀이입니다.',core:'이사와 매수는 같은 운이 아닙니다. 생활 이동과 자산 결정을 분리해서 봐야 합니다.',strength:'필요한 때 생활 기반을 실제로 옮기는 힘',weak:'이사하고 싶은 마음을 곧바로 매수 타이밍으로 받아들이는 것',mistake:'입지·대출·등기보다 “지금 사고 싶다”는 감정을 먼저 두는 것',gain:'생활권 개선·주거 안정·자산 매입의 시기를 나눠 봅니다.',risk:'대출·보증금·계약금이 동시에 묶이는 구간을 봅니다.',people:'배우자·가족·직장 위치가 주거 선택에 미치는 영향을 함께 봐야 합니다.',docs:'등기·대출·임대차·특약·보증보험 같은 현실 서류가 사주보다 우선입니다.',scenarios:[['A. 이사만','생활환경을 바꾸되 자산 매수는 미룹니다.'],['B. 실거주 매수','생활 필요와 자금 조건이 같이 맞을 때 검토합니다.'],['C. 투자 매수','생활과 분리해 수익·대출·회수 조건만으로 판단합니다.']],actions:['이사 목적을 생활·직장·자산 중 하나로 정하기','감당 가능한 월 주거비·대출 상한 적기','관심 지역 3곳의 실제 거래가격과 이동시간 비교하기'],follow:['이사하기 편한 시기는 언제인가?','매수와 전월세 중 어느 선택이 더 자연스러운 흐름인가?','계약을 특히 꼼꼼히 봐야 할 달은 언제인가?']},
'가족 문제':{family:'family',desire:'가족 걱정이 아니라 내가 실제로 어디까지 책임져야 하는지 보고 싶을 때의 풀이입니다.',core:'가족운은 감정보다 돈·시간·돌봄·결정의 몫이 어디로 쏠리는지를 봅니다.',strength:'필요할 때 가족을 실질적으로 챙기는 힘',weak:'책임감 때문에 다른 가족의 몫까지 혼자 떠안는 것',mistake:'도와주는 것과 대신 살아주는 것을 구분하지 못하는 것',gain:'가족 안에서 역할을 다시 나누고 관계를 안정시키는 시기를 봅니다.',risk:'돈·돌봄·주거가 한 사람에게 몰리는 구간을 봅니다.',people:'가족 문제는 누가 옳으냐보다 누가 무엇을 맡을지 분명히 하는 것이 중요합니다.',docs:'재산·대출·상속·보증처럼 법률·금융 문제가 섞이면 반드시 실제 문서와 전문가 검토를 함께 해야 합니다.',scenarios:[['A. 내가 직접 해결','빠르지만 내 부담이 커질 수 있습니다.'],['B. 역할 분담','가족별로 돈·시간·실무를 나눕니다.'],['C. 외부 도움','전문가·기관·서비스를 이용해 가족 안의 소모를 줄입니다.']],actions:['내가 맡을 일과 맡지 않을 일을 각각 적기','가족 문제의 돈 규모를 실제 숫자로 확인하기','필요하면 제3자 전문가 도움을 받을 항목 정하기'],follow:['가족 책임이 커지기 쉬운 시기는 언제인가?','가족과 돈 문제가 겹치기 쉬운 달은 언제인가?','합가·분가처럼 생활 구조가 바뀌기 쉬운 때는 언제인가?']},
'자녀·가족계획':{family:'family',desire:'자녀 문제를 운으로 단정하기보다 가족계획이 현실 조건과 언제 맞물리는지 보고 싶을 때의 풀이입니다.',core:'자녀운은 임신 여부를 예언하는 것이 아니라 생활·주거·돌봄·일의 조건이 가족계획과 어떻게 맞는지를 봅니다.',strength:'가족을 위해 생활 구조를 실제로 조정하는 힘',weak:'불확실성을 줄이려고 사주 결과 하나에 너무 큰 의미를 두는 것',mistake:'의학적 가능성과 명리 흐름을 같은 것으로 보는 것',gain:'가족계획을 실제 일정으로 옮기기 편한 생활 흐름을 봅니다.',risk:'일·주거·재정 부담이 한꺼번에 커지는 구간을 봅니다.',people:'배우자와 역할·휴직·돌봄 계획을 실제로 나누는 것이 중요합니다.',docs:'건강·임신 가능성은 의료진과 확인하고, 휴직·지원제도는 공식 조건을 따로 확인해야 합니다.',scenarios:[['A. 계획 시작','생활·건강·재정 준비를 시작합니다.'],['B. 조건 정비','주거·일·돌봄 문제를 먼저 정리합니다.'],['C. 일정 조정','의학적·현실적 조건에 따라 계획 시점을 유연하게 조정합니다.']],actions:['배우자와 돌봄·휴직 역할 나누기','출산·육아 예상 고정비 계산하기','건강 관련 사항은 의료진과 별도로 확인하기'],follow:['가족계획을 현실적으로 준비하기 편한 시기는 언제인가?','주거와 가족계획이 같이 움직이는 때는 언제인가?','일과 돌봄 부담이 커질 수 있는 구간은 언제인가?']},
'시험·자격':{family:'study',desire:'공부를 오래 하는 것보다 실제 시험·심사·합격 결과가 언제 움직이는지 보고 싶을 때의 풀이입니다.',core:'시험운은 공부량보다 준비→응시→평가의 연결이 중요합니다.',strength:'기준이 있을 때 집중해서 결과를 만드는 힘',weak:'준비가 부족하다는 생각 때문에 실제 응시를 계속 미루는 것',mistake:'공부하는 시기와 합격 결과가 나오는 시기를 하나로 보는 것',gain:'집중·응시·평가·문서 결과의 시기를 나눠 봅니다.',risk:'완벽주의와 일정 지연으로 기회를 놓치는 구간을 봅니다.',people:'선생·멘토·면접관·심사자처럼 외부 기준을 이해하는 것이 도움이 됩니다.',docs:'접수·응시자격·제출서류·마감일을 명리보다 먼저 확인해야 합니다.',scenarios:[['A. 빠른 응시','현재 준비 수준으로 먼저 결과를 확인합니다.'],['B. 보완 후 응시','약점을 보완한 뒤 다음 기회를 노립니다.'],['C. 목표 변경','현재 시험보다 실제 목적에 가까운 다른 자격·전형을 고릅니다.']],actions:['시험일을 먼저 확정하고 역산 계획 세우기','실전 모의평가로 현재 점수 확인하기','서류·자격·마감조건 체크하기'],follow:['집중력이 붙기 쉬운 시기는 언제인가?','실제 응시·면접에 유리한 달은 언제인가?','결과가 늦어질 수 있는 구간은 언제인가?']},
'올해 전체운':{family:'annual',desire:'올해 모든 일을 좋다·나쁘다로 자르기보다 무엇이 먼저 움직이고 무엇을 뒤로 미뤄야 하는지 보고 싶을 때의 풀이입니다.',core:'올해는 일·돈·관계·이동이 같은 속도로 움직이지 않습니다. 순서를 잡는 것이 핵심입니다.',strength:'우선순위를 정하면 한 영역의 변화가 다른 영역까지 이어지는 힘',weak:'한 번에 인생 여러 영역을 같이 바꾸려는 것',mistake:'좋은 달에는 모든 걸 하고, 조심할 달에는 아무것도 하지 않는 식으로 단순화하는 것',gain:'올해 가장 먼저 열리는 영역과 그다음 영역을 봅니다.',risk:'여러 변화가 겹쳐 체력·돈·관계가 동시에 소모되는 구간을 봅니다.',people:'올해의 중요한 변화는 사람을 통해 시작되거나 사람 때문에 속도가 바뀔 수 있습니다.',docs:'큰돈·직장·부동산·법률 결정은 실제 조건을 함께 확인해야 합니다.',scenarios:[['A. 한 가지 집중','가장 먼저 움직이는 영역 하나에 힘을 몰아줍니다.'],['B. 두 단계 진행','상반기와 하반기의 목표를 나눕니다.'],['C. 전면 변화','여러 영역을 동시에 바꾸는 선택. 자원 여유가 충분할 때만 검토합니다.']],actions:['올해 가장 바꾸고 싶은 것 하나만 고르기','돈·시간·관계 자원 중 가장 부족한 것 확인하기','앞으로 90일 한 가지 목표만 숫자로 정하기'],follow:['올해 가장 먼저 움직이는 영역은 무엇인가?','올해 가장 강한 달과 조심할 달은 언제인가?','올해의 선택이 내년에는 어떤 결과로 이어지는가?']}
};
const FALLBACK=PACK['올해 전체운'];

function getInput(){const u=$('#unknown')?.checked;return{year:+$('#year')?.value,month:+$('#month')?.value,day:+$('#day')?.value,hour:u?12:+($('#hour')?.value||12),minute:u?0:+($('#minute')?.value||0),gender:$('.sex.on')?.dataset.sex||'female',isLunar:$('#calendar')?.value==='lunar',isLeapMonth:$('#calendar')?.value==='lunar'&&$('#leap')?.checked,city:$('#city')?.value||'서울',unknown:u,trueSolarTime:{longitude:LONG[$('#city')?.value||'서울']||126.978,applyEquationOfTime:true,applyHistoricalDst:true},dayBoundary:'midnight'} }
function topic(){return($('#checkoutTitle')?.textContent||'올해 전체운').replace(/\s*심층 풀이\s*$/,'').trim()||'올해 전체운'}
function gg(g){return GOD_GROUP[g]||'resource'}
function rel(a,b){if(pair(a,b,CLASH))return{type:'충',w:2.4,pressure:true};if(pair(a,b,HARM))return{type:'해',w:1.4,pressure:true};if(pair(a,b,COMB))return{type:'합',w:1.5,combine:true};if(a===b)return{type:'반복',w:.8};return null}
function annual(natal,v,year){const y=LIB17.calculateFourPillars({year,month:7,day:1,hour:12,minute:0,gender:v.gender}).year;const groups=[gg(LIB17.getTenGod(natal.day.heavenlyStem,y.heavenlyStem)),gg(LIB17.getBranchTenGod(natal.day.heavenlyStem,y.earthlyBranch))];const s={wealth:0,output:0,authority:0,resource:0,peer:0,move:0,relation:0,pressure:0,combine:0};groups.forEach(g=>s[g]+=2);for(const [pos,br] of [['year',natal.year.earthlyBranch],['month',natal.month.earthlyBranch],['day',natal.day.earthlyBranch],...(v.unknown?[]:[['hour',natal.hour.earthlyBranch]])]){const r=rel(br,y.earthlyBranch);if(!r)continue;if(r.pressure)s.pressure+=r.w;if(r.combine)s.combine+=r.w;if(pos==='month')s.move+=r.w*1.1;if(pos==='day'){s.relation+=r.w*1.25;s.move+=r.w*.55}if(pos==='year'||pos==='hour')s.relation+=r.w*.55}return{year,pillar:y.heavenlyStem+y.earthlyBranch,groups,s,dominant:Object.entries(s).filter(([k])=>['wealth','output','authority','resource','peer'].includes(k)).sort((a,b)=>b[1]-a[1])[0]?.[0]||'resource'} }
function weight(f){return f==='money'?{wealth:2.2,output:1.4,authority:.8,resource:.5,peer:.5,move:.5,relation:.2,pressure:.35}:f==='business'?{wealth:1.5,output:2,authority:.6,resource:.4,peer:.8,move:.6,relation:.2,pressure:.35}:f==='career'?{wealth:.5,output:.7,authority:2.2,resource:1.1,peer:.6,move:1.2,relation:.2,pressure:.65}:f==='relationship'?{wealth:.4,output:.3,authority:.6,resource:.3,peer:.7,move:.4,relation:2.4,pressure:.5}:f==='home'?{wealth:1,output:.3,authority:.5,resource:.8,peer:.3,move:2.2,relation:.8,pressure:.5}:f==='family'?{wealth:.5,output:.3,authority:.5,resource:1,peer:.6,move:.6,relation:2,pressure:.6}:f==='study'?{wealth:.2,output:.7,authority:1.6,resource:2.2,peer:.2,move:.3,relation:.1,pressure:.4}:{wealth:1,output:1,authority:1,resource:1,peer:1,move:.7,relation:.7,pressure:.4}}
function topicScore(r,f){const w=weight(f);return Object.entries(w).reduce((a,[k,v])=>a+(r.s[k]||0)*v,0)}
function activeDayun(natal,v){const age=new Date().getFullYear()-v.year;return(natal.luckPillars?.pillars||[]).find(x=>age>=x.age&&age<x.age+10)||null}
function dayunCopy(natal,v,p){const d=activeDayun(natal,v);if(!d)return'지금의 10년 흐름은 한 가지 사건보다 선택의 기준을 새로 세우는 과정에 가깝습니다.';const k=d.korean||d.ganji||'',stem=d.heavenlyStem||k[0],branch=d.earthlyBranch||k[1];const a=stem?gg(LIB17.getTenGod(natal.day.heavenlyStem,stem)):'resource',b=branch?gg(LIB17.getBranchTenGod(natal.day.heavenlyStem,branch)):a;return`지금 10년의 바탕에는 ${GROUP_NAME[a]}와 ${GROUP_NAME[b]}의 성격이 함께 깔립니다. 그래서 ${p.core} 눈앞의 한 번의 결과보다 이 기준을 몇 년 동안 반복해서 지키는지가 더 중요합니다.`}
function annualFamilyText(r,p,stage){const d=r.dominant,f=p.family;const map={
 money:{wealth:'현금·거래·정산처럼 돈 자체의 움직임이 커집니다.',output:'내가 만든 결과가 수입으로 연결되기 쉬워집니다.',authority:'직책·보상·계약 조건이 돈과 연결되기 쉽습니다.',resource:'벌리기보다 저축·부채·고정비 같은 기반을 정리하는 쪽이 중요합니다.',peer:'사람과 돈의 몫이 함께 움직여 공동지출·협업 비용을 조심해야 합니다.'},
 business:{wealth:'고객·매출·거래가 전면에 나옵니다.',output:'상품·콘텐츠·서비스를 실제로 내놓고 반응을 확인하기 좋습니다.',authority:'사업의 규칙·계약·책임을 정비해야 규모를 키울 수 있습니다.',resource:'확장보다 시스템·지식·기반을 먼저 다지는 편이 좋습니다.',peer:'동업·협업·경쟁 구도가 중요해집니다.'},
 career:{wealth:'보상과 연봉처럼 역할의 가격이 중요해집니다.',output:'내가 만든 결과와 성과를 밖으로 보여주는 일이 중요합니다.',authority:'책임·평가·직책이 직접적으로 움직입니다.',resource:'배움·문서·준비가 다음 자리로 연결되는 기반이 됩니다.',peer:'동료·상사·조직 안의 역할 경쟁이 선택에 영향을 줍니다.'},
 relationship:{wealth:'관계가 감정만이 아니라 현실적인 시간·돈·생활 조건으로 들어옵니다.',output:'표현과 대화가 관계의 속도를 바꿉니다.',authority:'관계를 공식화하거나 책임을 정하는 문제가 중요해집니다.',resource:'새 관계보다 내 마음과 생활을 정리하는 과정이 먼저일 수 있습니다.',peer:'친구·지인·주변 사람을 통한 연결이나 비교가 커질 수 있습니다.'},
 home:{wealth:'보증금·계약금·대출처럼 집과 돈이 같이 움직일 가능성이 커집니다.',output:'생활방식을 바꾸려는 욕구가 실제 이동 준비로 이어질 수 있습니다.',authority:'계약·직장·공식 조건 때문에 생활권이 바뀔 수 있습니다.',resource:'집을 사기보다 자금·정보·조건을 모으는 준비가 중요합니다.',peer:'배우자·가족·동거인과 주거 조건을 맞추는 일이 중요합니다.'},
 family:{wealth:'가족 문제와 돈의 책임이 같이 움직일 수 있습니다.',output:'가족 안에서 내 의견을 분명히 하고 역할을 재조정할 필요가 있습니다.',authority:'내가 책임져야 할 가족의 몫이 커질 수 있습니다.',resource:'돌봄·지원·준비를 정리하는 과정이 중요합니다.',peer:'형제·배우자 등 가까운 사람과 역할을 나누는 문제가 중요합니다.'},
 study:{wealth:'비용을 들여 배우거나 자격을 실제 수입과 연결하는 판단이 중요합니다.',output:'배운 것을 시험·과제·면접처럼 밖으로 보여줘야 합니다.',authority:'시험·심사·평가 같은 공식 결과가 중요해집니다.',resource:'집중·학습·자료·문서 준비가 가장 잘 맞는 성격입니다.',peer:'경쟁자보다 내 점수와 기준을 객관적으로 확인하는 것이 중요합니다.'},
 annual:{wealth:'돈과 현실조건이 먼저 움직입니다.',output:'성과와 실행이 앞에 섭니다.',authority:'책임과 평가가 앞에 섭니다.',resource:'준비와 기반 정리가 앞에 섭니다.',peer:'사람과 역할 조정이 앞에 섭니다.'}}
 const base=(map[f]||map.annual)[d]||map.annual[d];const stageText={peak:'이 5년 안에서는 가장 큰 변곡으로 보는 해라, 선택을 미루기보다 조건을 확인하고 결론을 내는 쪽이 맞습니다.',rise:'앞선 준비를 실제 행동으로 옮기기 좋은 해입니다. 다만 처음부터 전부 바꾸기보다 반응을 확인하면서 비중을 키우세요.',test:'움직임은 있지만 결과보다 검증이 중요한 해입니다. 조건을 고쳐 잡으면 다음 해의 선택이 쉬워집니다.',build:'눈에 띄는 결과보다 기반을 만드는 해입니다. 급하게 결론을 내리기보다 준비와 정리를 해두는 편이 유리합니다.',close:'앞선 몇 년의 결과를 정리하고 남길 것과 버릴 것을 가르는 해입니다.'};return `${base} ${stageText[stage]}`}
function monthProfile(natal,v,date,p){const y=date.getFullYear(),m=date.getMonth()+1,mp=LIB17.calculateFourPillars({year:y,month:m,day:15,hour:12,minute:0,gender:v.gender}).month;const groups=[gg(LIB17.getTenGod(natal.day.heavenlyStem,mp.heavenlyStem)),gg(LIB17.getBranchTenGod(natal.day.heavenlyStem,mp.earthlyBranch))];const s={wealth:0,output:0,authority:0,resource:0,peer:0,move:0,relation:0,pressure:0,combine:0};groups.forEach(g=>s[g]+=1.6);for(const [pos,br] of [['month',natal.month.earthlyBranch],['day',natal.day.earthlyBranch],['year',natal.year.earthlyBranch]]){const r=rel(br,mp.earthlyBranch);if(!r)continue;if(r.pressure)s.pressure+=r.w;if(r.combine)s.combine+=r.w;if(pos==='month')s.move+=r.w;if(pos==='day')s.relation+=r.w}const r={year:y,month:m,groups,s,dominant:Object.entries(s).filter(([k])=>['wealth','output','authority','resource','peer'].includes(k)).sort((a,b)=>b[1]-a[1])[0]?.[0]||'resource'};r.score=topicScore(r,p.family);return r}
function monthText(r,p,rank){const d=r.dominant;const base={wealth:'돈·조건·정산을 숫자로 확인하기 좋은 달',output:'제안·실행·표현을 앞쪽에 두기 좋은 달',authority:'책임·평가·계약 조건을 분명히 해야 하는 달',resource:'속도를 늦추고 준비·정리·검토에 힘을 주기 좋은 달',peer:'사람과 역할·몫을 조정해야 하는 달'}[d];let detail=rank==='top'?'이 달은 앞으로 12개월 중 이 주제의 움직임이 상대적으로 크게 올라옵니다. 중요한 행동을 잡는다면 준비를 끝낸 뒤 실제 실행으로 옮기는 후보가 됩니다.':rank==='caution'?'기회가 없다는 뜻이 아니라, 속도보다 조건 확인이 먼저입니다. 특히 사람·돈·계약이 동시에 걸리면 한 번 더 확인하세요.':'큰 결론보다 다음 선택을 위한 한 단계에 알맞습니다. 작은 실행이나 점검을 쌓는 쪽이 좋습니다.';if(r.s.pressure>1.5)detail+=' 예상보다 변수나 마찰이 생길 수 있어 여유 시간을 남겨두세요.';if(r.s.combine>1)detail+=' 반대로 흩어진 조건을 하나로 묶어 확정하기에는 도움이 되는 면도 있습니다.';return{title:base,body:detail}}
function pastSnippets(){const arr=[];$$('#readingMount .hwPaper').forEach(c=>{const ey=c.querySelector('.hwEy')?.textContent||'';if(!/지나온 변곡/.test(ey))return;arr.push({ey,title:c.querySelector('h2')?.textContent||'',body:c.querySelector('p')?.textContent||''})});return arr.slice(0,2)}
function page(n,title,headline,body,extra=''){return`<section class="v17Page" id="v17p${n}"><div class="v17Num">${String(n).padStart(2,'0')} / 32</div><div class="v17Kicker">${title}</div><h2>${headline}</h2><div class="v17Body">${body}</div>${extra}</section>`}
function ptxt(...xs){return xs.filter(Boolean).map(x=>`<p>${x}</p>`).join('')}
function renderPaid17(){if(!LIB17)return;const label=topic(),p=PACK[label]||FALLBACK,v=getInput();let natal;try{natal=LIB17.calculateFourPillars(v)}catch(e){console.error(e);return}const now=new Date(),thisYear=now.getFullYear();const years=[0,1,2,3,4].map(i=>annual(natal,v,thisYear+i));years.forEach(r=>r.score=topicScore(r,p.family));const sorted=[...years].sort((a,b)=>b.score-a.score);years.forEach((r,i)=>{const rank=sorted.indexOf(r);r.stage=rank===0?'peak':rank===1?'rise':rank===2?'test':i===4?'close':'build'});const months=[];for(let i=0;i<12;i++)months.push(monthProfile(natal,v,new Date(now.getFullYear(),now.getMonth()+i,15),p));const ms=[...months].sort((a,b)=>b.score-a.score),topSet=new Set(ms.slice(0,3).map(x=>`${x.year}-${x.month}`)),cautionSet=new Set(ms.slice(-2).map(x=>`${x.year}-${x.month}`));const dm=DAY_META[natal.day.heavenlyStem]||DAY_META.갑,dayun=dayunCopy(natal,v,p),past=pastSnippets();const best=sorted[0],caution=sorted[sorted.length-1];const quarter=(start)=>months.slice(start,start+3).map(r=>{const key=`${r.year}-${r.month}`,rank=topSet.has(key)?'top':cautionSet.has(key)?'caution':'mid',m=monthText(r,p,rank);return`<div class="v17Month"><b>${String(r.month).padStart(2,'0')}월</b><span><strong>${m.title}</strong><br>${m.body}</span></div>`}).join('');const annualRows=years.map(r=>`<div class="v17Year"><b>${r.year}</b><span><strong>${r.stage==='peak'?'핵심 변곡':r.stage==='rise'?'확장':r.stage==='test'?'검증':r.stage==='close'?'정리':'준비'} · ${GROUP_NAME[r.dominant]}</strong><br>${annualFamilyText(r,p,r.stage)}</span></div>`).join('');const scenarioCards=p.scenarios.map(([a,b])=>`<div class="v17Scenario"><b>${a}</b><p>${b}</p></div>`).join('');const actionList=p.actions.map((x,i)=>`<div class="v17Action"><b>${i+1}</b><span>${x}</span></div>`).join('');const followList=p.follow.map((x,i)=>`<div class="v17Question"><b>Q${i+1}</b><span>${x}</span></div>`).join('');const bestMonths=ms.slice(0,3).map(x=>`${x.year}.${String(x.month).padStart(2,'0')}`).join(' · '),careMonths=ms.slice(-2).map(x=>`${x.year}.${String(x.month).padStart(2,'0')}`).join(' · ');
 let html=`<nav class="v17Toc"><button id="v17TocBtn">32장 목차 보기</button><div id="v17TocList" class="hide">${['결론','질문의 본질','타고난 선택방식','강점','취약점','반복실수','지난 흐름','10년 바탕','올해의 중심','상반기·하반기','첫 움직임','그다음 움직임',String(thisYear),String(thisYear+1),String(thisYear+2),String(thisYear+3),String(thisYear+4),'5년 핵심창','주의창','12개월 1','12개월 2','12개월 3','12개월 4','들어오는 길','빠지는 길','사람','계약·문서','A/B/C','선택기준','30일 행동','다음 질문','봉인 요약'].map((x,i)=>`<a href="#v17p${i+1}">${String(i+1).padStart(2,'0')} ${x}</a>`).join('')}</div></nav>`;
 html+=page(1,'먼저 결론',`${label}, 지금은 “좋다·나쁘다”보다 순서를 보는 게 먼저입니다.`,ptxt(p.desire,p.core),`<div class="v17Summary"><b>밀어볼 것</b><span>${p.strength}</span><b>멈춰볼 것</b><span>${p.weak}</span></div>`);
 html+=page(2,'이 질문의 본질','당장 하나의 답보다, 무엇을 먼저 확인해야 하는지가 더 중요합니다.',ptxt(`이 질문에서 가장 흔한 실수는 ${p.mistake}`,`현월당은 결과를 대신 결정하기보다, ${label}에서 어떤 조건을 먼저 확인할지 순서를 잡아주는 방식으로 풀이합니다.`));
 html+=page(3,'타고난 선택 방식',`${dm[0]}의 기운은 이 문제를 이렇게 다루는 편입니다.`,ptxt(dm[1],`그래서 ${label}에서는 내 성향이 장점으로 쓰이는 순간과 과해지는 순간을 나눠 볼 필요가 있습니다.`));
 html+=page(4,'내가 잘하는 쪽',p.strength,ptxt(`이 사주의 장점은 상황이 맞았을 때 ${p.strength}을 실제 행동으로 옮길 수 있다는 점입니다.`,`다만 장점은 조건이 맞을 때 힘이 됩니다. 준비가 덜 된 상태에서 속도만 높이면 같은 힘이 부담으로 바뀔 수 있습니다.`));
 html+=page(5,'내가 놓치기 쉬운 쪽',p.weak,ptxt(`이 주제에서는 특히 ${p.weak}을 경계해야 합니다.`,`결과가 좋아 보일수록 반대쪽 조건을 하나 더 확인해 두면 운의 좋은 부분을 현실에서 더 오래 가져갈 수 있습니다.`));
 html+=page(6,'반복하기 쉬운 실수',p.mistake,ptxt(`이 패턴이 반복되면 “운이 안 좋았다”기보다 같은 선택 구조가 다른 시기에 되풀이될 수 있습니다.`,`앞으로의 시기를 볼 때는 좋은 때를 찾는 것만큼, 이 실수를 피할 기준을 먼저 세워두는 것이 중요합니다.`));
 html+=page(7,'지나온 흐름과 연결',past.length?`${past[0].ey.replace(/\s*·.*/,'')} 전후의 선택이 지금 질문과 이어집니다.`:'지금의 고민은 갑자기 생긴 것보다 이전 선택의 연장선에 가깝습니다.',past.length?ptxt(...past.map(x=>`${x.title} ${x.body}`),`지나온 변곡을 맞고 틀림만으로 끝내지 말고, 그때 무엇을 선택했고 무엇을 미뤘는지를 떠올려보세요. 지금의 질문이 왜 생겼는지 연결점이 보일 수 있습니다.`):ptxt('최근 몇 년은 한 사건보다 기준이 서서히 바뀌어온 흐름에 가깝습니다.','지금은 그 변화가 실제 선택으로 넘어갈 준비를 하는 시점으로 보는 편이 맞습니다.'));
 html+=page(8,'지금 10년의 바탕','한 해보다 더 길게 깔린 배경이 있습니다.',ptxt(dayun,`이 배경은 매년 같은 사건을 만든다는 뜻이 아니라, 여러 선택 가운데 어떤 종류의 문제가 반복해서 중요해지는지를 보여주는 바탕으로 봅니다.`));
 html+=page(9,`${thisYear}년의 중심`,`${GROUP_NAME[years[0].dominant]}이 먼저 앞에 서는 해입니다.`,ptxt(annualFamilyText(years[0],p,years[0].stage),`올해는 모든 것을 한꺼번에 바꾸기보다 ${p.core}`));
 html+=page(10,'상반기와 하반기','같은 해라도 앞과 뒤의 역할은 다르게 봐야 합니다.',ptxt('상반기는 이미 해온 선택의 결과와 조건을 확인하는 성격이 강하고, 하반기로 갈수록 다음 행동을 실제로 정해야 하는 일이 늘어날 수 있습니다.',`특히 ${bestMonths} 전후는 이 주제에서 움직임을 크게 느끼기 쉬운 후보라, 그 전에 현실 조건을 정리해 두는 편이 좋습니다.`));
 html+=page(11,'무엇이 먼저 움직이나',p.gain,ptxt(p.gain,`먼저 작은 변화가 보이고 그다음 규모가 커지는 순서로 보는 편이 안전합니다. 처음 나타나는 신호보다 “두 번 반복되는가”를 확인하세요.`));
 html+=page(12,'그다음 무엇을 봐야 하나',p.risk,ptxt(p.risk,`좋은 흐름과 부담은 동시에 올 수 있습니다. 하나가 좋아졌다고 다른 조건까지 자동으로 좋아지는 것은 아니므로 반대편 비용을 같이 계산해야 합니다.`));
 years.forEach((r,i)=>{html+=page(13+i,`${r.year}년`,`${r.year}년은 ${r.stage==='peak'?'이 5년의 핵심 변곡':r.stage==='rise'?'실행과 확장':r.stage==='test'?'조건을 확인하는 검증':r.stage==='close'?'앞선 결과를 정리하는 마무리':'기반을 만드는 준비'}의 해로 봅니다.`,ptxt(annualFamilyText(r,p,r.stage),`이 해의 중심은 ${GROUP_NAME[r.dominant]}입니다. 같은 ${label} 안에서도 앞뒤 해와 역할이 다르기 때문에 한 문장을 반복해서 적용하지 않습니다.`))});
 html+=page(18,'5년 중 가장 중요한 창',`${best.year}년을 가장 먼저 표시해두세요.`,ptxt(`${best.year}년은 향후 5년 안에서 ${label} 관련 움직임이 상대적으로 가장 크게 겹치는 해입니다.`,`${bestMonths} 전후가 월 단위 후보로도 올라옵니다. 그때 갑자기 결정하기보다 그 전에 필요한 조건을 준비해두는 방식이 좋습니다.`),`<div class="v17Map">${annualRows}</div>`);
 html+=page(19,'5년 중 더 천천히 볼 창',`${caution.year}년은 속도보다 확인이 먼저입니다.`,ptxt(`${caution.year}년은 이 주제를 못 한다는 해가 아니라, 다른 해보다 준비·정리·조건 확인의 비중을 높이는 편이 맞습니다.`,`특히 ${careMonths} 전후에는 ${p.weak}을 한 번 더 확인하세요.`));
 html+=page(20,'앞으로 12개월 · 첫 3개월','처음 3개월은 방향을 잡는 구간입니다.',ptxt('바로 큰 결론을 내리기보다 어떤 조건이 실제로 달라지는지 확인하세요.'),`<div class="v17Months">${quarter(0)}</div>`);
 html+=page(21,'앞으로 12개월 · 4~6개월','준비한 것을 실제 행동으로 옮길 후보가 보입니다.',ptxt('첫 분기에 확인한 조건 가운데 살아남은 것만 키우는 편이 좋습니다.'),`<div class="v17Months">${quarter(3)}</div>`);
 html+=page(22,'앞으로 12개월 · 7~9개월','성과와 비용을 함께 점검하는 구간입니다.',ptxt('잘되는 것만 보지 말고 그 결과를 얻기 위해 얼마를 쓰고 있는지 같이 확인하세요.'),`<div class="v17Months">${quarter(6)}</div>`);
 html+=page(23,'앞으로 12개월 · 10~12개월','다음 해로 가져갈 것을 고르는 구간입니다.',ptxt('새로운 일을 더 늘리기보다 이미 만든 것 중 반복해서 남길 수 있는 것을 고르는 편이 좋습니다.'),`<div class="v17Months">${quarter(9)}</div>`);
 html+=page(24,'기회가 들어오는 길','좋은 운은 “기회”라는 이름보다 구체적인 통로로 들어옵니다.',ptxt(p.gain,`내가 기대한 모양과 다르게 들어와도 같은 결과로 이어질 수 있습니다. 그래서 기회의 이름보다 실제로 무엇이 반복되고 커지는지를 보세요.`));
 html+=page(25,'손실이 생기는 길','나갈 돈·시간·감정도 함께 봐야 합니다.',ptxt(p.risk,`특히 이 주제에서는 ${p.weak}이 손실의 시작이 되기 쉽습니다. 좋은 선택을 찾는 것보다 감당할 수 없는 선택을 제거하는 것부터 하세요.`));
 html+=page(26,'사람이 끼치는 영향','혼자 결정하는 문제처럼 보여도 사람의 영향이 큽니다.',ptxt(p.people,`내가 통제할 수 있는 조건과 상대가 결정하는 조건을 분리해두면 불확실성이 훨씬 줄어듭니다.`));
 html+=page(27,'계약·문서·현실 조건','마지막에는 종이에 남는 조건을 확인해야 합니다.',ptxt(p.docs,`사주는 현실 확인을 대신하지 않습니다. 오히려 언제 무엇을 더 꼼꼼히 확인해야 하는지 우선순위를 좁히는 참고로 쓰는 편이 좋습니다.`));
 html+=page(28,'세 가지 선택 시나리오','같은 사주라도 선택에 따라 결과의 모양은 달라집니다.',ptxt('아래 세 가지 중 무엇이 정답이라고 단정하기보다, 현재 내가 감당할 수 있는 위험과 원하는 속도를 기준으로 비교해보세요.'),`<div class="v17Scenarios">${scenarioCards}</div>`);
 html+=page(29,'실제 선택 기준','밀어도 되는 조건과 멈춰볼 조건을 동시에 두세요.',ptxt(`<b>밀어볼 쪽:</b> ${p.strength}`,`<b>멈춰볼 쪽:</b> ${p.weak}`,`둘 중 하나만 보는 순간 판단이 한쪽으로 기울 수 있습니다. 좋은 흐름이 와도 현실 조건이 맞지 않으면 규모를 줄여 실행하는 방법이 있습니다.`));
 html+=page(30,'앞으로 30일','운을 기다리는 대신 지금 할 수 있는 세 가지부터 움직이세요.',ptxt('다음 30일은 결과를 확정하는 기간이 아니라, 앞으로 좋은 시기가 왔을 때 바로 움직일 수 있게 현실 조건을 정리하는 기간으로 쓰는 편이 좋습니다.'),`<div class="v17Actions">${actionList}</div>`);
 html+=page(31,'이 풀이 다음에 생길 질문','한 질문을 깊게 보면 보통 다음 세 질문이 남습니다.',ptxt('현월당의 다음 풀이가 필요하다면 아래 중 정말 필요한 질문 하나만 고르는 편이 좋습니다. 전부 볼 필요는 없습니다.'),`<div class="v17Questions">${followList}</div>`);
 html+=page(32,'첫 심층 풀이 봉인','오늘의 결론은 여기까지입니다.',ptxt(`${label}에서 가장 중요한 결론은 “${p.core}”입니다.`,`가장 먼저 표시할 해는 ${best.year}년, 앞으로 12개월에서 먼저 체크할 달은 ${bestMonths}입니다. 반대로 ${careMonths} 전후에는 조건을 한 번 더 확인하세요.`,`같은 명식과 같은 주제로 다시 봤을 때 오늘의 핵심 결론이 임의로 바뀌지 않도록 이 풀이를 기준 기록으로 남기는 방향이 현월당의 원칙입니다.`),`<div class="v17Seal"><span>玄月堂 深層記錄</span><b>${label}</b><small>${new Date().toLocaleDateString('ko-KR')} · ${natal.year.heavenlyStem}${natal.year.earthlyBranch}/${natal.month.heavenlyStem}${natal.month.earthlyBranch}/${natal.day.heavenlyStem}${natal.day.earthlyBranch}</small></div>`);
 $('#paidMount').innerHTML=html;$('#paidTitle').textContent=`${label} · 32장 심층 풀이`;$('#paid .resultHero p').textContent='첫 풀이에서 보인 흐름을 32개의 서로 다른 질문으로 나누어 깊게 풀었습니다.';['landing','loading','result','checkout'].forEach(id=>$('#'+id)?.classList.add('hide'));$('#paid')?.classList.remove('hide');scrollTo(0,0);const b=$('#v17TocBtn'),l=$('#v17TocList');if(b&&l)b.onclick=()=>l.classList.toggle('hide')}
function styles(){const s=document.createElement('style');s.textContent=`#paidMount{max-width:820px;margin:auto}.v17Toc{position:sticky;top:0;z-index:8;background:#120c0a;border-bottom:1px solid #493127;padding:10px 14px}.v17Toc button{width:100%;border:1px solid #765343;background:#1a100d;color:#e9ddcd;padding:12px;font-weight:800}.v17TocList{max-height:55vh;overflow:auto;display:grid;grid-template-columns:1fr 1fr;gap:2px;padding:8px 0}.v17TocList a{font-size:11px;color:#cdbca7;text-decoration:none;padding:7px 8px;border-bottom:1px solid #30231d}.v17Page{min-height:520px;margin:0;padding:34px 30px 42px;background:linear-gradient(180deg,#f2eadb,#e8deca);color:#231914;border-top:1px solid #bba98c;border-bottom:14px solid #d3c8b2;box-sizing:border-box}.v17Num{font-family:Georgia,serif;font-size:11px;letter-spacing:.12em;color:#8b2e27}.v17Kicker{margin-top:8px;font-size:12px;font-weight:900;color:#8b2e27;letter-spacing:.08em}.v17Page h2{font-family:Georgia,'Noto Serif KR',serif;font-size:27px;line-height:1.5;margin:18px 0 22px;word-break:keep-all}.v17Body p{font-size:15px;line-height:2;margin:0 0 15px;color:#51483f;word-break:keep-all}.v17Summary{display:grid;grid-template-columns:90px 1fr;gap:10px;margin-top:20px;padding:16px;background:rgba(130,45,36,.06);border-left:3px solid #842c24;font-size:13px;line-height:1.7}.v17Map,.v17Months,.v17Scenarios,.v17Actions,.v17Questions{margin-top:22px}.v17Year,.v17Month{display:grid;grid-template-columns:72px 1fr;gap:12px;padding:14px 0;border-bottom:1px solid rgba(112,82,55,.2)}.v17Year>b,.v17Month>b{font-family:Georgia,serif;font-size:20px}.v17Year span,.v17Month span{font-size:13px;line-height:1.8;color:#5b5046}.v17Scenario{padding:16px;margin:9px 0;background:rgba(126,45,36,.05);border-left:3px solid #8b2e27}.v17Scenario b{font-size:14px}.v17Scenario p{font-size:13px;line-height:1.8;margin:7px 0 0;color:#5b5046}.v17Action,.v17Question{display:grid;grid-template-columns:42px 1fr;gap:12px;align-items:start;padding:14px 0;border-bottom:1px solid rgba(112,82,55,.2)}.v17Action b,.v17Question b{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#7c2a22;color:#f4e9da;font-size:11px}.v17Action span,.v17Question span{font-size:14px;line-height:1.8}.v17Seal{margin-top:28px;padding:22px;background:#140d0a;color:#d8c9b7;border:1px solid #4b3328;text-align:center}.v17Seal span,.v17Seal small,.v17Seal b{display:block}.v17Seal span{font-family:Georgia,serif;letter-spacing:.14em}.v17Seal b{margin:12px 0;font-size:16px;color:#f0e4d4}.v17Seal small{color:#9f8b78}.hide{display:none!important}@media(max-width:520px){.v17Page{min-height:72vh;padding:28px 20px 36px}.v17Page h2{font-size:24px}.v17Body p{font-size:14px;line-height:1.95}.v17TocList{grid-template-columns:1fr}.v17Year,.v17Month{grid-template-columns:58px 1fr}}`;document.head.appendChild(s)}
async function init17(){styles();try{LIB17=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm')}catch(e){console.error(e);return}const pay=$('#pay');if(pay){pay.onclick=e=>{e.preventDefault();renderPaid17()};pay.textContent='테스트로 32장 전체 풀이 열기'}}
init17();