const $18=s=>document.querySelector(s),$$18=s=>[...document.querySelectorAll(s)];
let M18=null;
const G18={정재:'wealth',편재:'wealth',식신:'output',상관:'output',정관:'authority',편관:'authority',정인:'resource',편인:'resource',비견:'peer',겁재:'peer'};
const N18={wealth:'돈·현실',output:'결과·실행',authority:'책임·평가',resource:'준비·기반',peer:'사람·몫'};
const CL18=['자오','축미','인신','묘유','진술','사해'],CO18=['자축','인해','묘술','진유','사신','오미'],HA18=['자미','축오','인사','묘진','신해','유술'];
const pair18=(a,b,list)=>list.includes(a+b)||list.includes(b+a);
function in18(){const unknown=$18('#unknown')?.checked;return{year:+$18('#year')?.value,month:+$18('#month')?.value,day:+$18('#day')?.value,hour:unknown?12:+($18('#hour')?.value||12),minute:unknown?0:+($18('#minute')?.value||0),gender:document.querySelector('.sex.on')?.dataset.sex||'female',isLunar:$18('#calendar')?.value==='lunar',isLeapMonth:$18('#calendar')?.value==='lunar'&&$18('#leap')?.checked,unknown}}
function topic18(){return ($18('.hwTopic.on')?.textContent||$18('#paidTitle')?.textContent?.split(' · ')[0]||'재물·돈 흐름').trim()}
function group18(g){return G18[g]||'resource'}
function catFromTitle18(t=''){if(/돈|정산|현실/.test(t))return'wealth';if(/제안|실행|표현|결과|밀어/.test(t))return'output';if(/책임|평가|계약/.test(t))return'authority';if(/사람|역할|몫|경쟁/.test(t))return'peer';return'resource'}
function prof18(natal,v,d){const mp=M18.calculateFourPillars({year:d.getFullYear(),month:d.getMonth()+1,day:15,hour:12,minute:0,gender:v.gender}).month;const g1=group18(M18.getTenGod(natal.day.heavenlyStem,mp.heavenlyStem)),g2=group18(M18.getBranchTenGod(natal.day.heavenlyStem,mp.earthlyBranch));let pressure=0,combine=0;const natalBranches=[natal.month.earthlyBranch,natal.day.earthlyBranch,...(v.unknown?[]:[natal.hour.earthlyBranch]),natal.year.earthlyBranch].filter(Boolean);for(const br of natalBranches){if(pair18(br,mp.earthlyBranch,CL18))pressure+=1.4;if(pair18(br,mp.earthlyBranch,HA18))pressure+=.7;if(pair18(br,mp.earthlyBranch,CO18))combine+=1}return{year:d.getFullYear(),month:d.getMonth()+1,pillar:mp.heavenlyStem+mp.earthlyBranch,g1,g2,pressure,combine}}
function rangeLabel18(g){const a=g[0],b=g[g.length-1];if(g.length===1)return`${a.year}년 ${a.month}월`;if(a.year===b.year)return`${a.year}년 ${a.month}월~${b.month}월`;return`${a.year}년 ${a.month}월~${b.year}년 ${b.month}월`}
function topicUse18(topic,cat){const map={
'재물·돈 흐름':{wealth:'매출·연봉·정산·계약금처럼 실제 금액이 움직이는 항목을 숫자로 확인하는 데 쓰는 구간입니다.',output:'제안·판매·협상·실행처럼 돈이 들어올 통로를 직접 만드는 행동에 힘을 싣는 구간입니다.',authority:'보상·연봉·대출심사·계약조건처럼 제도와 책임이 돈에 영향을 주는 항목을 확인하는 구간입니다.',resource:'새 투입보다 현금흐름·고정비·대출·계약서를 정리해 손실 가능성을 줄이는 구간입니다.',peer:'가족·파트너·고객과 돈의 몫, 정산, 역할을 분리해 두는 것이 중요한 구간입니다.'},
'사업·창업':{wealth:'매출과 현금회수 여부를 확인하는 구간입니다.',output:'상품을 내놓고 제안·판매·테스트를 실제로 돌리기 좋은 구간입니다.',authority:'계약·책임·채용·사업자 조건을 정비하는 구간입니다.',resource:'상품·원가·고정비·운영 구조를 다시 짜는 구간입니다.',peer:'동업·채용·외주에서 역할과 몫을 분명히 해야 하는 구간입니다.'},
'부업·투잡':{wealth:'부수입이 실제 현금으로 남는지 확인하는 구간입니다.',output:'콘텐츠·제안·판매를 반복해 두 번째 수입원을 시험하기 좋은 구간입니다.',authority:'본업 규정·세금·계약 조건을 먼저 확인하는 구간입니다.',resource:'시간·도구·준비 비용을 정리하는 구간입니다.',peer:'소개·협업·수익배분 조건을 분명히 해야 하는 구간입니다.'},
'이직·퇴사':{wealth:'연봉·보상·생활비 조건을 비교하는 구간입니다.',output:'지원·면접·협상처럼 밖으로 움직이는 행동을 늘리기 좋은 구간입니다.',authority:'직책·평가·오퍼·계약조건이 핵심이 되는 구간입니다.',resource:'이력서·포트폴리오·자격·생활비를 준비하는 구간입니다.',peer:'상사·동료·조직문화 문제를 따로 확인해야 하는 구간입니다.'}
};return(map[topic]||map['재물·돈 흐름'])[cat]||'이 구간의 중심 신호에 맞춰 현실 조건을 확인하는 편이 좋습니다.'}
function why18(g,topic){const ps=g.map(x=>x.profile),signals=ps.flatMap(x=>[x.g1,x.g2]),cnt={wealth:0,output:0,authority:0,resource:0,peer:0};signals.forEach(x=>cnt[x]=(cnt[x]||0)+1);const top=Object.entries(cnt).sort((a,b)=>b[1]-a[1])[0];const pressure=ps.reduce((a,b)=>a+b.pressure,0),combine=ps.reduce((a,b)=>a+b.combine,0);const cat=g[0].cat;let relation='';if(pressure>=g.length*1.2)relation='출생 명식과 부딪히거나 어긋나는 신호도 함께 잡혀, 좋은 기회가 보여도 속도를 올릴수록 변수까지 같이 커질 수 있습니다.';else if(combine>=1)relation='출생 명식과 서로 묶이는 신호가 있어, 흩어진 조건을 한쪽으로 모으거나 이미 준비한 일을 확정하는 데 힘이 붙는 편입니다.';else relation='출생 명식과의 강한 충돌이 두드러지지 않아, 이 구간은 월 자체의 성격을 비교적 그대로 쓰는 편으로 봅니다.';const dominant=`이 구간의 월별 위·아래 기운 ${signals.length}개를 나눠보면 ‘${N18[top[0]]}’ 성격이 ${top[1]}개로 가장 자주 잡힙니다.`;const meaning=cat==='resource'?'그래서 “아무것도 하지 말라”는 뜻이 아니라, 새 판을 크게 벌이기 전에 자료·현금·조건·순서를 정리해 다음 실행의 실패 확률을 낮추는 쪽에 무게를 둔 것입니다.':cat==='output'?'그래서 단순히 운이 좋다는 뜻이 아니라, 준비해 둔 것을 밖으로 꺼내 제안·실행·협상으로 연결했을 때 결과를 확인하기 쉬운 구간으로 본 것입니다.':cat==='wealth'?'그래서 돈이 저절로 들어온다는 뜻이 아니라, 수입·지출·계약·정산처럼 금액이 직접 움직이는 일이 늘기 쉬워 숫자를 실제로 확인해야 하는 구간으로 본 것입니다.':cat==='authority'?'그래서 무조건 승진하거나 계약된다는 뜻이 아니라, 책임·평가·규정·계약조건이 결과를 좌우하기 쉬워 문서와 조건을 먼저 보는 구간으로 본 것입니다.':'그래서 사람을 많이 만나라는 뜻이 아니라, 사람과 역할·몫·경쟁이 결과에 개입하기 쉬워 관계보다 조건을 먼저 분리해 보는 구간으로 본 것입니다.';return`${dominant} ${relation} ${meaning} ${topicUse18(topic,cat)}`}
function detail18(g){return g.map(x=>`${x.year}.${String(x.month).padStart(2,'0')} ${x.profile.pillar} → 위 ${N18[x.profile.g1]} / 아래 ${N18[x.profile.g2]}${x.profile.pressure?` · 충돌 신호 ${x.profile.pressure.toFixed(1)}`:''}${x.profile.combine?` · 결합 신호 ${x.profile.combine.toFixed(1)}`:''}`).join('<br>')}
function setPage18(n,kicker,title,body,extra=''){const p=$18(`#v17p${n}`);if(!p)return;p.innerHTML=`<div class="v17Num">${String(n).padStart(2,'0')} / 32</div><div class="v17Kicker">${kicker}</div><h2>${title}</h2><div class="v17Body">${body}</div>${extra}`;p.dataset.v18='1'}
function rebuild18(){const p20=$18('#v17p20');if(!p20||p20.dataset.v18==='1'||!M18)return;const old=$$18('#v17p20 .v17Month, #v17p21 .v17Month, #v17p22 .v17Month, #v17p23 .v17Month');if(old.length<12)return;const v=in18();let natal;try{natal=M18.calculateFourPillars(v)}catch(e){console.error(e);return}const now=new Date(),rows=old.slice(0,12).map((el,i)=>{const d=new Date(now.getFullYear(),now.getMonth()+i,15),title=el.querySelector('strong')?.textContent?.trim()||'',body=(el.querySelector('span')?.textContent||'').replace(title,'').trim();return{year:d.getFullYear(),month:d.getMonth()+1,title,body,cat:catFromTitle18(title),sig:`${title}|${body}`,profile:prof18(natal,v,d)}});const groups=[];for(const r of rows){const last=groups[groups.length-1];if(last&&last[0].sig===r.sig)last.push(r);else groups.push([r])}const topic=topic18();const cards=groups.map(g=>`<article class="v18Range"><div class="v18RangeHead"><b>${rangeLabel18(g)}</b><span>${g[0].title}</span></div><p>${why18(g,topic)}</p><details class="v18Why"><summary>왜 이렇게 봤는지 계산 근거 보기</summary><div>${detail18(g)}</div></details></article>`).join('');setPage18(20,'앞으로 12개월 · 흐름 묶어보기','같은 해석이 이어지는 달은 한 구간으로 묶었습니다.',`<p>월마다 같은 문장을 반복하면 정보량이 많아 보일 뿐 실제 판단에는 도움이 되지 않습니다. 같은 성격이 연속되는 달은 하나의 구간으로 묶고, 왜 그런 해석이 나왔는지 계산 근거와 현실 의미를 함께 설명합니다.</p>`,`<div class="v18Ranges">${cards}</div>`);
const push=groups.filter(g=>['output','wealth'].includes(g[0].cat));const cautious=groups.filter(g=>!['output','wealth'].includes(g[0].cat));setPage18(21,'밀어볼 수 있는 구간','“밀어볼 수 있다”는 말에는 조건이 있습니다.',`<p>현월당에서 밀어볼 수 있다고 쓰는 건 단순히 좋은 달이라는 뜻이 아닙니다. 결과·실행 또는 돈·현실 성격이 앞에 서고, 출생 명식과의 충돌이 감당 가능한 수준일 때 실제 행동의 우선순위를 올려볼 수 있다는 뜻입니다.</p>`,`<div class="v18Ranges">${(push.length?push:groups.slice(0,1)).map(g=>`<article class="v18Range"><div class="v18RangeHead"><b>${rangeLabel18(g)}</b><span>${g[0].title}</span></div><p>${why18(g,topic)}</p><div class="v18Do"><b>이때 실제로 할 일</b><span>${topicUse18(topic,g[0].cat)}</span></div></article>`).join('')}</div>`);
setPage18(22,'준비·확인이 먼저인 구간','“준비와 정리”는 쉬라는 뜻이 아닙니다.',`<p>준비·기반, 책임·평가, 사람·몫 성격이 강하거나 명식과의 충돌 신호가 겹치면 실행 자체를 막는 게 아니라 실행 전에 틀릴 수 있는 조건을 먼저 제거하는 쪽으로 풉니다. 즉 속도를 늦추는 이유가 있어야만 ‘확인’이라고 표시합니다.</p>`,`<div class="v18Ranges">${(cautious.length?cautious:groups.slice(-1)).map(g=>`<article class="v18Range"><div class="v18RangeHead"><b>${rangeLabel18(g)}</b><span>${g[0].title}</span></div><p>${why18(g,topic)}</p><div class="v18Do"><b>이때 먼저 확인할 것</b><span>${topicUse18(topic,g[0].cat)}</span></div></article>`).join('')}</div>`);
setPage18(23,'12개월 실제 사용법','좋은 달을 기다리지 말고 구간마다 역할을 다르게 쓰세요.',`<p>앞으로 12개월을 한 줄의 길로 보면, 어떤 구간은 준비하고 어떤 구간은 실행하고 어떤 구간은 돈과 계약을 확인하는 역할을 맡습니다. 아래 순서를 캘린더에 그대로 표시해 두는 편이 월별 문장 12개를 외우는 것보다 실용적입니다.</p>`,`<div class="v18Timeline">${groups.map((g,i)=>`<div><b>${i+1}</b><span><strong>${rangeLabel18(g)} · ${g[0].title}</strong><br>${topicUse18(topic,g[0].cat)}</span></div>`).join('')}</div>`);const toc=$18('#v17TocList');if(toc){const a20=toc.querySelector('a[href="#v17p20"]'),a21=toc.querySelector('a[href="#v17p21"]'),a22=toc.querySelector('a[href="#v17p22"]'),a23=toc.querySelector('a[href="#v17p23"]');if(a20)a20.textContent='20 12개월 구간';if(a21)a21.textContent='21 밀어볼 구간';if(a22)a22.textContent='22 확인할 구간';if(a23)a23.textContent='23 실제 사용법'} }
function css18(){const s=document.createElement('style');s.textContent=`.v18Ranges{margin-top:22px}.v18Range{padding:18px 16px;margin:12px 0;background:rgba(126,45,36,.055);border-left:3px solid #8b2e27}.v18RangeHead{display:flex;gap:10px;align-items:baseline;flex-wrap:wrap}.v18RangeHead b{font-family:Georgia,'Noto Serif KR',serif;font-size:18px;color:#2c201a}.v18RangeHead span{font-size:12px;font-weight:800;color:#8b2e27}.v18Range>p{font-size:14px;line-height:1.95;color:#51483f;margin:12px 0 0;word-break:keep-all}.v18Why{margin-top:14px;border-top:1px solid rgba(95,70,50,.18);padding-top:12px}.v18Why summary{font-size:12px;font-weight:800;color:#6f5143;cursor:pointer}.v18Why div{margin-top:10px;font-size:11px;line-height:1.9;color:#75675c}.v18Do{margin-top:14px;padding:12px;background:rgba(255,255,255,.28);display:grid;gap:5px}.v18Do b{font-size:12px;color:#392a22}.v18Do span{font-size:13px;line-height:1.75;color:#5d5046}.v18Timeline{margin-top:20px}.v18Timeline>div{display:grid;grid-template-columns:34px 1fr;gap:12px;padding:14px 0;border-bottom:1px solid rgba(112,82,55,.2)}.v18Timeline>div>b{width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:#7c2a22;color:#f4e9da;font-size:11px}.v18Timeline span{font-size:13px;line-height:1.8;color:#5b5046}.v18Timeline strong{color:#2f211b}@media(max-width:520px){.v18Range{padding:16px 14px}.v18RangeHead{display:block}.v18RangeHead span{display:block;margin-top:5px}}`;document.head.appendChild(s)}
async function init18(){css18();try{M18=await import('https://cdn.jsdelivr.net/npm/manseryeok@2.0.0/+esm')}catch(e){console.error(e);return}const mount=$18('#paidMount');if(!mount)return;const obs=new MutationObserver(()=>setTimeout(rebuild18,0));obs.observe(mount,{childList:true,subtree:true});setTimeout(rebuild18,100)}
init18();